"""
convert_to_c.py - Convert XGBoost JSON Models to C Headers for ESP32-S3

Parses trained XGBoost models (JSON format) and generates embedded C headers
with tree structures and normalization constants for on-device inference.

Usage (run from the ml/ directory):
    python convert_to_c.py --model ./model/ --output ../other/firmware/components/ml/include/model_data.h
"""

import os
import json
import argparse
import xgboost as xgb
import numpy as np
from typing import List, Dict, Any


# ============================================
# CONFIGURATION
# ============================================

FEATURE_NAMES = [
    'temp_current', 'humidity_current', 'pressure_current',
    'wind_speed_current', 'pm25_current', 'co2_current',
    'lightning_dist_current', 'temp_humidity_ratio', 'pressure_trend',
    'heat_index', 'dew_point', 'fire_risk_index', 'flood_risk_index',
    'lightning_threat',
]

HAZARD_CLASSES = ['wildfire', 'flood', 'storm', 'air_quality']
NUM_FEATURES = len(FEATURE_NAMES)
NUM_CLASSES = len(HAZARD_CLASSES)

# Firmware constraints
MAX_TREES_PER_CLASS = 16
MAX_DEPTH = 4
MAX_NODES_PER_TREE = 31  # 2^(MAX_DEPTH+1) - 1


# ============================================
# TREE PARSING
# ============================================

def parse_xgb_tree(tree_dict: Dict) -> List[Dict]:
    """Parse a single XGBoost tree JSON into flat node list (pre-order)."""
    nodes = []

    def traverse(node: Dict, idx: int):
        if idx >= MAX_NODES_PER_TREE:
            return

        if 'leaf' in node:
            # Leaf node
            nodes.append({
                'feature_idx': -1,
                'threshold': 0.0,
                'left_child': -1,
                'right_child': -1,
                'leaf_value': node['leaf'],
            })
        else:
            # Split node
            feature_name = node.get('split', '')
            feature_idx = FEATURE_NAMES.index(feature_name) if feature_name in FEATURE_NAMES else 0
            threshold = node.get('split_condition', 0.0)

            current_idx = len(nodes)
            left_idx = current_idx + 1

            # Placeholder for right child (will fix after left subtree)
            nodes.append({
                'feature_idx': feature_idx,
                'threshold': threshold,
                'left_child': left_idx,
                'right_child': -1,  # Will fix after left subtree
                'leaf_value': 0.0,
            })

            # Traverse left
            if 'children' in node and len(node['children']) > 0:
                traverse(node['children'][0], left_idx)

            # Fix right child index
            right_idx = len(nodes)
            nodes[current_idx]['right_child'] = right_idx

            # Traverse right
            if 'children' in node and len(node['children']) > 1:
                traverse(node['children'][1], right_idx)

    traverse(tree_dict, 0)
    return nodes


def load_model_trees(model_dir: str, max_trees: int = MAX_TREES_PER_CLASS) -> Dict[str, List[List[Dict]]]:
    """Load all XGBoost models and convert to tree node lists."""
    trees_by_class = {}

    for cls in HAZARD_CLASSES:
        model_path = os.path.join(model_dir, f'xgboost_{cls}.json')
        if not os.path.exists(model_path):
            print(f"Warning: {model_path} not found, skipping")
            trees_by_class[cls] = []
            continue

        model = xgb.Booster()
        model.load_model(model_path)

        dump = model.get_dump(dump_format='json')
        class_trees = []

        for i, tree_json in enumerate(dump):
            if i >= max_trees:
                break
            tree_dict = json.loads(tree_json)
            nodes = parse_xgb_tree(tree_dict)
            class_trees.append(nodes)

        trees_by_class[cls] = class_trees
        print(f"  {cls}: loaded {len(class_trees)} trees (max nodes: {max(len(t) for t in class_trees)})")

    return trees_by_class


# ============================================
# C CODE GENERATION
# ============================================

def generate_model_header(trees_by_class: Dict, norm_stats: Dict, output_path: str):
    """Generate model_data.h with tree structures and inference functions."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, 'w') as f:
        # Header
        f.write("/**\n")
        f.write(" * model_data.h - Auto-generated XGBoost model for ESP32-S3\n")
        f.write(" * Generated by convert_to_c.py - DO NOT EDIT\n")
        f.write(" */\n\n")
        f.write("#ifndef MODEL_DATA_H\n")
        f.write("#define MODEL_DATA_H\n\n")
        f.write("#include <stdint.h>\n\n")

        # Model configuration
        f.write("// Model configuration\n")
        f.write(f"#define NUM_CLASSES {NUM_CLASSES}\n")
        f.write(f"#define NUM_FEATURES {NUM_FEATURES}\n")
        f.write(f"#define MAX_NODES_PER_TREE {MAX_NODES_PER_TREE}\n")

        for cls in HAZARD_CLASSES:
            n = len(trees_by_class.get(cls, []))
            f.write(f"#define {cls.upper()}_NUM_TREES {n}\n")
        f.write("\n")

        # Node structure
        f.write("// XGBoost tree node\n")
        f.write("typedef struct {\n")
        f.write("    int8_t  feature_idx;   // -1 for leaf\n")
        f.write("    float   threshold;     // split threshold\n")
        f.write("    int16_t left_child;    // index of left child\n")
        f.write("    int16_t right_child;   // index of right child\n")
        f.write("    float   leaf_value;    // leaf prediction\n")
        f.write("} __attribute__((packed)) xgb_node_t;\n\n")

        f.write("typedef struct {\n")
        f.write("    uint8_t num_nodes;\n")
        f.write("    xgb_node_t nodes[MAX_NODES_PER_TREE];\n")
        f.write("} xgb_tree_t;\n\n")

        # Feature names
        f.write("// Feature names (for debugging)\n")
        f.write("static const char *FEATURE_NAMES[NUM_FEATURES] = {\n")
        for name in FEATURE_NAMES:
            f.write(f'    "{name}",\n')
        f.write("};\n\n")

        # Generate trees for each class
        for cls in HAZARD_CLASSES:
            class_trees = trees_by_class.get(cls, [])
            upper = cls.upper()

            f.write(f"// {cls.upper()} model ({len(class_trees)} trees)\n")

            for t_idx, tree in enumerate(class_trees):
                num_nodes = len(tree)
                f.write(f"static const xgb_tree_t {upper}_TREE_{t_idx} = {{\n")
                f.write(f"    .num_nodes = {num_nodes},\n")
                f.write("    .nodes = {\n")

                for node in tree:
                    f.write("        {")
                    f.write(f" .feature_idx = {node['feature_idx']},")
                    f.write(f" .threshold = {node['threshold']:.6f}f,")
                    f.write(f" .left_child = {node['left_child']},")
                    f.write(f" .right_child = {node['right_child']},")
                    f.write(f" .leaf_value = {node['leaf_value']:.6f}f")
                    f.write(" },\n")

                # Pad remaining nodes
                for _ in range(num_nodes, MAX_NODES_PER_TREE):
                    f.write("        { .feature_idx = -1, .threshold = 0, .left_child = -1, .right_child = -1, .leaf_value = 0 },\n")

                f.write("    }\n")
                f.write("};\n\n")

            # Tree pointer array
            f.write(f"static const xgb_tree_t *{upper}_TREES[{len(class_trees)}] = {{\n")
            for t_idx in range(len(class_trees)):
                f.write(f"    &{upper}_TREE_{t_idx},\n")
            f.write("};\n\n")

        # Normalization constants
        f.write("// Feature normalization (z-score from training data)\n")
        f.write(f"static const float NORM_MEAN[NUM_FEATURES] = {{\n")
        for i, val in enumerate(norm_stats['mean']):
            f.write(f"    {val:.6f}f,  // {FEATURE_NAMES[i]}\n")
        f.write("};\n\n")

        f.write(f"static const float NORM_STD[NUM_FEATURES] = {{\n")
        for i, val in enumerate(norm_stats['std']):
            f.write(f"    {val:.6f}f,  // {FEATURE_NAMES[i]}\n")
        f.write("};\n\n")

        # Inline inference functions
        f.write("// ============================================\n")
        f.write("// Inference Functions (inline for performance)\n")
        f.write("// ============================================\n\n")

        f.write("// Z-score normalization (in-place)\n")
        f.write("static inline void normalize_features(float *features, int num_features) {\n")
        f.write("    int n = num_features < NUM_FEATURES ? num_features : NUM_FEATURES;\n")
        f.write("    for (int i = 0; i < n; i++) {\n")
        f.write("        features[i] = (features[i] - NORM_MEAN[i]) / NORM_STD[i];\n")
        f.write("    }\n")
        f.write("}\n\n")

        f.write("// Sigmoid activation\n")
        f.write("static inline float sigmoid(float x) {\n")
        f.write("    if (x > 50.0f) return 1.0f;\n")
        f.write("    if (x < -50.0f) return 0.0f;\n")
        f.write("    return 1.0f / (1.0f + expf(-x));\n")
        f.write("}\n\n")

        f.write("// Single tree inference (iterative, no recursion)\n")
        f.write("static inline float xgb_tree_inference(const xgb_tree_t *tree, const float *features) {\n")
        f.write("    if (tree->num_nodes == 0) return 0.0f;\n")
        f.write("    int16_t node_idx = 0;\n")
        f.write("    \n")
        f.write("    while (node_idx >= 0 && node_idx < tree->num_nodes) {\n")
        f.write("        const xgb_node_t *node = &tree->nodes[node_idx];\n")
        f.write("        \n")
        f.write("        if (node->feature_idx < 0) {\n")
        f.write("            return node->leaf_value;\n")
        f.write("        }\n")
        f.write("        \n")
        f.write("        if (features[node->feature_idx] < node->threshold) {\n")
        f.write("            node_idx = node->left_child;\n")
        f.write("        } else {\n")
        f.write("            node_idx = node->right_child;\n")
        f.write("        }\n")
        f.write("    }\n")
        f.write("    return 0.0f;\n")
        f.write("}\n\n")

        f.write("// Full model inference for all 4 hazard classes\n")
        f.write("static inline void xgb_model_inference(\n")
        f.write("    const float *features_raw,\n")
        f.write("    float *output_wildfire,\n")
        f.write("    float *output_flood,\n")
        f.write("    float *output_storm,\n")
        f.write("    float *output_air_quality\n")
        f.write(") {\n")
        f.write("    // Normalize features\n")
        f.write("    float features[NUM_FEATURES];\n")
        f.write("    for (int i = 0; i < NUM_FEATURES; i++) {\n")
        f.write("        features[i] = features_raw[i];\n")
        f.write("    }\n")
        f.write("    normalize_features(features, NUM_FEATURES);\n\n")

        for cls in HAZARD_CLASSES:
            upper = cls.upper()
            f.write(f"    // {cls}\n")
            f.write(f"    float sum_{cls} = 0.0f;\n")
            f.write(f"    for (int i = 0; i < {upper}_NUM_TREES; i++) {{\n")
            f.write(f"        sum_{cls} += xgb_tree_inference({upper}_TREES[i], features);\n")
            f.write(f"    }}\n")
            f.write(f"    float prob_{cls} = sigmoid(sum_{cls});\n\n")

        f.write("    *output_wildfire     = prob_wildfire;\n")
        f.write("    *output_flood        = prob_flood;\n")
        f.write("    *output_storm        = prob_storm;\n")
        f.write("    *output_air_quality  = prob_air_quality;\n")
        f.write("}\n\n")

        f.write("#endif // MODEL_DATA_H\n")


def generate_normalization_header(norm_stats: Dict, output_path: str):
    """Generate normalization.h with just mean/std arrays."""
    norm_path = os.path.join(os.path.dirname(output_path), 'normalization.h')

    with open(norm_path, 'w') as f:
        f.write("/**\n")
        f.write(" * normalization.h - Feature normalization for Edge AI Weather Station\n")
        f.write(" * Auto-generated from training data\n")
        f.write(" */\n\n")
        f.write("#ifndef NORMALIZATION_H\n")
        f.write("#define NORMALIZATION_H\n\n")
        f.write("#include <stdint.h>\n\n")

        f.write(f"static const float NORM_MEAN[{NUM_FEATURES}] = {{\n")
        for i, val in enumerate(norm_stats['mean']):
            f.write(f"    {val:.6f}f,  // {FEATURE_NAMES[i]}\n")
        f.write("};\n\n")

        f.write(f"static const float NORM_STD[{NUM_FEATURES}] = {{\n")
        for i, val in enumerate(norm_stats['std']):
            f.write(f"    {val:.6f}f,  // {FEATURE_NAMES[i]}\n")
        f.write("};\n\n")

        f.write("// Normalize feature vector in-place\n")
        f.write("static inline void normalize_features(float *features, int num_features) {\n")
        f.write(f"    int n = num_features < {NUM_FEATURES} ? num_features : {NUM_FEATURES};\n")
        f.write("    for (int i = 0; i < n; i++) {\n")
        f.write("        features[i] = (features[i] - NORM_MEAN[i]) / NORM_STD[i];\n")
        f.write("    }\n")
        f.write("}\n\n")

        f.write("#endif // NORMALIZATION_H\n")

    print(f"Generated normalization header: {norm_path}")


def generate_metadata_header(output_path: str):
    """Generate model_metadata.h with feature/class names and thresholds."""
    meta_path = os.path.join(os.path.dirname(output_path), 'model_metadata.h')

    with open(meta_path, 'w') as f:
        f.write("/**\n")
        f.write(" * model_metadata.h - Model metadata for debugging\n")
        f.write(" * Auto-generated\n")
        f.write(" */\n\n")
        f.write("#ifndef MODEL_METADATA_H\n")
        f.write("#define MODEL_METADATA_H\n\n")

        f.write("static const char *FEATURE_NAMES[14] = {\n")
        for name in FEATURE_NAMES:
            f.write(f'    "{name}",\n')
        f.write("};\n\n")

        f.write("static const char *HAZARD_CLASS_NAMES[4] = {\n")
        for name in HAZARD_CLASSES:
            f.write(f'    "{name}",\n')
        f.write("};\n\n")

        f.write("static const float ALERT_THRESHOLDS[4] = {\n")
        f.write("    0.70f,  // wildfire\n")
        f.write("    0.70f,  // flood\n")
        f.write("    0.75f,  // storm\n")
        f.write("    0.65f,  // air_quality\n")
        f.write("};\n\n")

        f.write("#endif // MODEL_METADATA_H\n")

    print(f"Generated metadata header: {meta_path}")


# ============================================
# MAIN
# ============================================

def main():
    parser = argparse.ArgumentParser(description='Convert XGBoost models to C headers')
    parser.add_argument('--model', type=str, required=True, help='Model directory with xgboost_*.json')
    parser.add_argument('--output', type=str, required=True, help='Output C header path')
    parser.add_argument('--max-trees', type=int, default=MAX_TREES_PER_CLASS, help='Max trees per class')
    args = parser.parse_args()

    # Load normalization stats
    norm_path = os.path.join(args.model, 'normalization.json')
    if not os.path.exists(norm_path):
        print(f"Error: {norm_path} not found. Run train_model.py first.")
        return 1

    with open(norm_path) as f:
        norm_stats = json.load(f)

    # Load and parse trees
    trees_by_class = load_model_trees(args.model, args.max_trees)

    if not any(trees_by_class.values()):
        print("Error: No model trees loaded!")
        return 1

    # Generate headers
    generate_model_header(trees_by_class, norm_stats, args.output)
    generate_normalization_header(norm_stats, args.output)
    generate_metadata_header(args.output)

    print("\nConversion complete!")
    print(f"  Model data:     {args.output}")
    print(f"  Normalization:  {os.path.join(os.path.dirname(args.output), 'normalization.h')}")
    print(f"  Metadata:       {os.path.join(os.path.dirname(args.output), 'model_metadata.h')}")

    return 0


if __name__ == '__main__':
    exit(main())