/* Generated by python -m ml.six_sensor_forecast.export. Research forecast, not a hazard alarm. */
#ifndef INDRA_SIX_SENSOR_FORECAST_H
#define INDRA_SIX_SENSOR_FORECAST_H
#include <math.h>
#include <stddef.h>
#define INDRA_FORECAST_INPUTS 2
#define INDRA_FORECAST_OUTPUTS 2
#define INDRA_FORECAST_HORIZON_HOURS 6
#define INDRA_FORECAST_STATUS "OFFLINE_RESEARCH_ONLY"
/* Input/output order: pm25_ug_m3, pm10_ug_m3 */
static inline float indra_fc_0_0(const float *x) {
  if (x[0] < 180.0f) {
    if (x[0] < 100.0f) {
      if (x[0] < 83.5699997f) {
        return 2.71494436f;
      } else {
        return 0.958864808f;
      }
    } else {
      if (x[0] < 137.309998f) {
        return -1.74084187f;
      } else {
        return -5.13540459f;
      }
    }
  } else {
    if (x[0] < 487.140015f) {
      if (x[0] < 256.0f) {
        return -9.80655861f;
      } else {
        return -18.9896755f;
      }
    } else {
      return -51.4762764f;
    }
  }
}
static inline float indra_fc_0_1(const float *x) {
  if (x[0] < 156.5f) {
    if (x[0] < 105.800003f) {
      if (x[0] < 85.75f) {
        return 2.1545403f;
      } else {
        return 0.558171928f;
      }
    } else {
      if (x[0] < 121.790001f) {
        return -1.07532001f;
      } else {
        return -2.98435211f;
      }
    }
  } else {
    if (x[0] < 487.140015f) {
      if (x[0] < 246.25f) {
        return -6.50785446f;
      } else {
        return -14.7175512f;
      }
    } else {
      return -41.7093163f;
    }
  }
}
static inline float indra_fc_0_2(const float *x) {
  if (x[0] < 201.0f) {
    if (x[0] < 105.800003f) {
      if (x[0] < 76.5500031f) {
        return 1.81106782f;
      } else {
        return 0.621349573f;
      }
    } else {
      if (x[0] < 137.309998f) {
        return -1.40088308f;
      } else {
        return -3.59201503f;
      }
    }
  } else {
    if (x[0] < 487.140015f) {
      if (x[0] < 277.5f) {
        return -7.8164115f;
      } else {
        return -13.6535482f;
      }
    } else {
      return -34.2174873f;
    }
  }
}
static inline float indra_fc_0_3(const float *x) {
  if (x[0] < 180.0f) {
    if (x[0] < 107.790001f) {
      if (x[0] < 87.25f) {
        return 1.35860646f;
      } else {
        return 0.211996004f;
      }
    } else {
      if (x[0] < 120.5f) {
        return -0.670439422f;
      } else {
        return -2.09755874f;
      }
    }
  } else {
    if (x[0] < 487.140015f) {
      if (x[0] < 292.0f) {
        return -5.67452192f;
      } else {
        return -10.8682728f;
      }
    } else {
      return -28.8042507f;
    }
  }
}
static inline float indra_fc_0_4(const float *x) {
  if (x[0] < 192.0f) {
    if (x[0] < 112.269997f) {
      if (x[0] < 76.5500031f) {
        return 1.13980293f;
      } else {
        return 0.208384857f;
      }
    } else {
      if (x[0] < 153.809998f) {
        return -1.19706368f;
      } else {
        return -2.67974782f;
      }
    }
  } else {
    if (x[0] < 487.140015f) {
      if (x[0] < 237.25f) {
        return -4.06129646f;
      } else {
        return -7.72835255f;
      }
    } else {
      return -22.1637421f;
    }
  }
}
static inline float indra_fc_0_5(const float *x) {
  if (x[0] < 196.5f) {
    if (x[0] < 108.830002f) {
      if (x[0] < 24.25f) {
        return 0.225565076f;
      } else {
        return 0.974301636f;
      }
    } else {
      if (x[0] < 124.5f) {
        return -0.496941239f;
      } else {
        return -1.62112749f;
      }
    }
  } else {
    if (x[0] < 399.850006f) {
      if (x[0] < 277.5f) {
        return -3.84029269f;
      } else {
        return -6.13631201f;
      }
    } else {
      if (x[0] < 487.140015f) {
        return -9.97324848f;
      } else {
        return -16.2793331f;
      }
    }
  }
}
static inline float indra_fc_0_6(const float *x) {
  if (x[0] < 217.5f) {
    if (x[0] < 99.0f) {
      if (x[0] < 26.5f) {
        return 0.209217548f;
      } else {
        return 0.879074216f;
      }
    } else {
      if (x[0] < 153.809998f) {
        return -0.623930931f;
      } else {
        return -1.76939905f;
      }
    }
  } else {
    if (x[0] < 399.850006f) {
      if (x[0] < 307.5f) {
        return -3.78504372f;
      } else {
        return -5.15225697f;
      }
    } else {
      if (x[0] < 487.140015f) {
        return -9.25610733f;
      } else {
        return -13.9558172f;
      }
    }
  }
}
static inline float indra_fc_0_7(const float *x) {
  if (x[0] < 201.0f) {
    if (x[0] < 92.75f) {
      if (x[0] < 23.0f) {
        return 0.123462319f;
      } else {
        return 0.715556681f;
      }
    } else {
      if (x[0] < 156.5f) {
        return -0.371147066f;
      } else {
        return -1.38630521f;
      }
    }
  } else {
    if (x[0] < 399.850006f) {
      if (x[0] < 223.5f) {
        return -2.1449964f;
      } else {
        return -3.43297577f;
      }
    } else {
      if (x[0] < 487.140015f) {
        return -7.45506811f;
      } else {
        return -11.1643839f;
      }
    }
  }
}
static inline float indra_fc_0_8(const float *x) {
  if (x[0] < 153.809998f) {
    if (x[0] < 92.75f) {
      if (x[0] < 27.3799992f) {
        return 0.155689344f;
      } else {
        return 0.611215532f;
      }
    } else {
      if (x[0] < 121.790001f) {
        return -0.115998857f;
      } else {
        return -0.653825223f;
      }
    }
  } else {
    if (x[0] < 399.850006f) {
      if (x[0] < 237.25f) {
        return -1.38111985f;
      } else {
        return -3.01739502f;
      }
    } else {
      if (x[0] < 487.140015f) {
        return -4.7657299f;
      } else {
        return -8.60573101f;
      }
    }
  }
}
static inline float indra_fc_0_9(const float *x) {
  if (x[1] < 727.119995f) {
    if (x[1] < 292.5f) {
      if (x[1] < 94.0f) {
        return -0.298929065f;
      } else {
        return 0.639741778f;
      }
    } else {
      if (x[1] < 425.079987f) {
        return -1.39519191f;
      } else {
        return -3.18011308f;
      }
    }
  } else {
    return -14.895874f;
  }
}
static inline float indra_fc_0_10(const float *x) {
  if (x[0] < 118.019997f) {
    if (x[0] < 66.5f) {
      if (x[0] < 27.3799992f) {
        return 0.167744726f;
      } else {
        return 0.670429826f;
      }
    } else {
      if (x[0] < 111.25f) {
        return -0.243071198f;
      } else {
        return 0.037776757f;
      }
    }
  } else {
    if (x[0] < 487.140015f) {
      if (x[0] < 217.5f) {
        return -0.71196264f;
      } else {
        return -1.85653961f;
      }
    } else {
      return -6.80302906f;
    }
  }
}
static inline float indra_fc_0_11(const float *x) {
  if (x[0] < 180.0f) {
    if (x[0] < 66.5f) {
      if (x[0] < 31.0f) {
        return 0.146201149f;
      } else {
        return 0.532031238f;
      }
    } else {
      if (x[0] < 126.0f) {
        return -0.145697281f;
      } else {
        return -0.44470492f;
      }
    }
  } else {
    if (x[0] < 487.140015f) {
      if (x[0] < 307.5f) {
        return -1.07978606f;
      } else {
        return -2.07597065f;
      }
    } else {
      return -4.76816845f;
    }
  }
}
static inline float indra_fc_0_12(const float *x) {
  if (x[0] < 120.5f) {
    if (x[0] < 62.0f) {
      if (x[0] < 27.0f) {
        return 0.0797567442f;
      } else {
        return 0.448025286f;
      }
    } else {
      if (x[0] < 86.5f) {
        return 0.0159429554f;
      } else {
        return -0.183542252f;
      }
    }
  } else {
    if (x[0] < 399.850006f) {
      if (x[0] < 223.5f) {
        return -0.510125339f;
      } else {
        return -1.14589024f;
      }
    } else {
      return -3.55082965f;
    }
  }
}
static inline float indra_fc_0_13(const float *x) {
  if (x[0] < 180.0f) {
    if (x[0] < 66.5f) {
      if (x[0] < 26.0900002f) {
        return 0.0287849158f;
      } else {
        return 0.339273244f;
      }
    } else {
      if (x[0] < 70.75f) {
        return -0.364275545f;
      } else {
        return -0.0800078288f;
      }
    }
  } else {
    if (x[0] < 330.5f) {
      if (x[0] < 223.5f) {
        return -0.56177038f;
      } else {
        return -0.934262276f;
      }
    } else {
      if (x[0] < 359.190002f) {
        return -3.39194608f;
      } else {
        return -1.28957725f;
      }
    }
  }
}
static inline float indra_fc_0_14(const float *x) {
  if (x[0] < 487.140015f) {
    if (x[0] < 137.309998f) {
      if (x[0] < 62.0f) {
        return 0.200362444f;
      } else {
        return -0.026834771f;
      }
    } else {
      if (x[0] < 237.25f) {
        return -0.470062464f;
      } else {
        return -0.93582356f;
      }
    }
  } else {
    return -4.83296013f;
  }
}
static inline float indra_fc_0_15(const float *x) {
  if (x[1] < 727.119995f) {
    if (x[1] < 94.0f) {
      if (x[1] < 91.5500031f) {
        return -0.410246432f;
      } else {
        return -1.53190899f;
      }
    } else {
      if (x[1] < 275.75f) {
        return 0.595566571f;
      } else {
        return -0.540074229f;
      }
    }
  } else {
    return -9.71227646f;
  }
}
static inline float indra_fc_head_0(const float *x) {
  float residual = 0.7684574f;
  residual += indra_fc_0_0(x);
  residual += indra_fc_0_1(x);
  residual += indra_fc_0_2(x);
  residual += indra_fc_0_3(x);
  residual += indra_fc_0_4(x);
  residual += indra_fc_0_5(x);
  residual += indra_fc_0_6(x);
  residual += indra_fc_0_7(x);
  residual += indra_fc_0_8(x);
  residual += indra_fc_0_9(x);
  residual += indra_fc_0_10(x);
  residual += indra_fc_0_11(x);
  residual += indra_fc_0_12(x);
  residual += indra_fc_0_13(x);
  residual += indra_fc_0_14(x);
  residual += indra_fc_0_15(x);
  float value = x[0] + 0.0f * residual;
  return fminf(5000.0f, fmaxf(0.0f, value));
}
static inline float indra_fc_1_0(const float *x) {
  if (x[0] < 137.25f) {
    if (x[0] < 92.75f) {
      if (x[0] < 81.2600021f) {
        return 4.13015699f;
      } else {
        return 2.0480845f;
      }
    } else {
      if (x[0] < 107.75f) {
        return -0.246124774f;
      } else {
        return -4.03255415f;
      }
    }
  } else {
    if (x[0] < 246.0f) {
      if (x[0] < 176.509995f) {
        return -8.89680481f;
      } else {
        return -14.6398544f;
      }
    } else {
      if (x[0] < 485.75f) {
        return -26.4563236f;
      } else {
        return -47.0740471f;
      }
    }
  }
}
static inline float indra_fc_1_1(const float *x) {
  if (x[0] < 139.0f) {
    if (x[0] < 88.75f) {
      if (x[0] < 25.25f) {
        return 2.27995253f;
      } else {
        return 3.66825271f;
      }
    } else {
      if (x[0] < 120.5f) {
        return -0.697880387f;
      } else {
        return -4.40307617f;
      }
    }
  } else {
    if (x[0] < 255.759995f) {
      if (x[0] < 201.0f) {
        return -8.20615768f;
      } else {
        return -13.8337927f;
      }
    } else {
      if (x[0] < 485.75f) {
        return -21.7961235f;
      } else {
        return -36.6509743f;
      }
    }
  }
}
static inline float indra_fc_1_2(const float *x) {
  if (x[0] < 127.5f) {
    if (x[0] < 92.75f) {
      if (x[0] < 24.1499996f) {
        return 1.72773993f;
      } else {
        return 2.84162498f;
      }
    } else {
      if (x[0] < 113.349998f) {
        return -0.495861053f;
      } else {
        return -2.66578341f;
      }
    }
  } else {
    if (x[0] < 237.25f) {
      if (x[0] < 164.25f) {
        return -4.84898615f;
      } else {
        return -8.82140923f;
      }
    } else {
      if (x[0] < 485.75f) {
        return -16.1239834f;
      } else {
        return -29.6643581f;
      }
    }
  }
}
static inline float indra_fc_1_3(const float *x) {
  if (x[0] < 154.0f) {
    if (x[0] < 100.849998f) {
      if (x[0] < 74.5f) {
        return 2.26507449f;
      } else {
        return 0.721191585f;
      }
    } else {
      if (x[0] < 120.5f) {
        return -1.20283902f;
      } else {
        return -3.01713777f;
      }
    }
  } else {
    if (x[0] < 277.25f) {
      if (x[0] < 196.25f) {
        return -6.0789237f;
      } else {
        return -8.80226803f;
      }
    } else {
      if (x[0] < 402.0f) {
        return -14.7630568f;
      } else {
        return -19.3997555f;
      }
    }
  }
}
static inline float indra_fc_1_4(const float *x) {
  if (x[0] < 154.0f) {
    if (x[0] < 100.849998f) {
      if (x[0] < 75.7600021f) {
        return 1.84281313f;
      } else {
        return 0.593483508f;
      }
    } else {
      if (x[0] < 126.0f) {
        return -1.05910289f;
      } else {
        return -2.66040063f;
      }
    }
  } else {
    if (x[0] < 277.25f) {
      if (x[0] < 201.0f) {
        return -4.7171936f;
      } else {
        return -7.35976553f;
      }
    } else {
      if (x[0] < 485.75f) {
        return -11.8780231f;
      } else {
        return -20.2559185f;
      }
    }
  }
}
static inline float indra_fc_1_5(const float *x) {
  if (x[0] < 154.0f) {
    if (x[0] < 85.6299973f) {
      if (x[0] < 24.1499996f) {
        return 0.541409254f;
      } else {
        return 1.61794221f;
      }
    } else {
      if (x[0] < 105.75f) {
        return -0.0411582477f;
      } else {
        return -1.47564638f;
      }
    }
  } else {
    if (x[0] < 290.690002f) {
      if (x[0] < 201.0f) {
        return -3.87604022f;
      } else {
        return -5.86600494f;
      }
    } else {
      if (x[0] < 402.0f) {
        return -9.64735889f;
      } else {
        return -13.7489386f;
      }
    }
  }
}
static inline float indra_fc_1_6(const float *x) {
  if (x[0] < 127.5f) {
    if (x[0] < 76.5f) {
      if (x[0] < 28.5f) {
        return 0.596093714f;
      } else {
        return 1.46387374f;
      }
    } else {
      if (x[0] < 113.349998f) {
        return 0.0715530515f;
      } else {
        return -0.94204706f;
      }
    }
  } else {
    if (x[0] < 255.759995f) {
      if (x[0] < 173.5f) {
        return -2.13987327f;
      } else {
        return -3.9466877f;
      }
    } else {
      if (x[0] < 485.75f) {
        return -7.21892118f;
      } else {
        return -13.6891661f;
      }
    }
  }
}
static inline float indra_fc_1_7(const float *x) {
  if (x[0] < 156.5f) {
    if (x[0] < 100.849998f) {
      if (x[0] < 68.25f) {
        return 0.941146314f;
      } else {
        return 0.253087372f;
      }
    } else {
      if (x[0] < 126.0f) {
        return -0.577229023f;
      } else {
        return -1.39107215f;
      }
    }
  } else {
    if (x[0] < 277.25f) {
      if (x[0] < 237.25f) {
        return -2.79744625f;
      } else {
        return -4.63057995f;
      }
    } else {
      if (x[0] < 485.75f) {
        return -6.05189562f;
      } else {
        return -10.9511976f;
      }
    }
  }
}
static inline float indra_fc_1_8(const float *x) {
  if (x[0] < 120.5f) {
    if (x[0] < 85.6299973f) {
      if (x[0] < 28.5f) {
        return 0.189838216f;
      } else {
        return 0.918871045f;
      }
    } else {
      if (x[0] < 90.25f) {
        return -0.659432948f;
      } else {
        return -0.0238189958f;
      }
    }
  } else {
    if (x[0] < 277.25f) {
      if (x[0] < 167.25f) {
        return -1.35451901f;
      } else {
        return -2.55990577f;
      }
    } else {
      if (x[0] < 485.75f) {
        return -4.92943192f;
      } else {
        return -8.09977531f;
      }
    }
  }
}
static inline float indra_fc_1_9(const float *x) {
  if (x[1] < 554.830017f) {
    if (x[1] < 295.25f) {
      if (x[1] < 199.75f) {
        return 1.85155618f;
      } else {
        return -0.398694664f;
      }
    } else {
      if (x[1] < 424.5f) {
        return -5.8186121f;
      } else {
        return -14.4839706f;
      }
    }
  } else {
    if (x[1] < 725.179993f) {
      if (x[1] < 616.72998f) {
        return -23.7226219f;
      } else {
        return -31.6181774f;
      }
    } else {
      return -73.5786972f;
    }
  }
}
static inline float indra_fc_1_10(const float *x) {
  if (x[0] < 147.25f) {
    if (x[0] < 20.3199997f) {
      if (x[0] < 7.78000021f) {
        return 0.0687049851f;
      } else {
        return -0.471708357f;
      }
    } else {
      if (x[0] < 61.8400002f) {
        return 0.488362044f;
      } else {
        return -0.103983082f;
      }
    }
  } else {
    if (x[0] < 360.75f) {
      if (x[0] < 308.0f) {
        return -0.919614792f;
      } else {
        return -2.96641231f;
      }
    } else {
      if (x[0] < 402.0f) {
        return 0.897015035f;
      } else {
        return -0.326422423f;
      }
    }
  }
}
static inline float indra_fc_1_11(const float *x) {
  if (x[0] < 113.349998f) {
    if (x[0] < 24.1499996f) {
      if (x[0] < 14.1099997f) {
        return -0.0272419006f;
      } else {
        return -0.26402089f;
      }
    } else {
      if (x[0] < 67.5f) {
        return 0.435395867f;
      } else {
        return -0.103345834f;
      }
    }
  } else {
    if (x[0] < 147.25f) {
      if (x[0] < 114.5f) {
        return -1.90710545f;
      } else {
        return -0.340373993f;
      }
    } else {
      if (x[0] < 360.75f) {
        return -1.04130399f;
      } else {
        return -0.30600664f;
      }
    }
  }
}
static inline float indra_fc_1_12(const float *x) {
  if (x[0] < 105.75f) {
    if (x[0] < 24.1499996f) {
      if (x[0] < 14.1099997f) {
        return 0.0263302978f;
      } else {
        return -0.234559283f;
      }
    } else {
      if (x[0] < 67.5f) {
        return 0.353283226f;
      } else {
        return -0.061550241f;
      }
    }
  } else {
    if (x[0] < 360.75f) {
      if (x[0] < 329.75f) {
        return -0.466286421f;
      } else {
        return -3.99507332f;
      }
    } else {
      if (x[0] < 485.75f) {
        return 0.762911618f;
      } else {
        return 1.65488589f;
      }
    }
  }
}
static inline float indra_fc_1_13(const float *x) {
  if (x[0] < 105.75f) {
    if (x[0] < 35.5699997f) {
      if (x[0] < 35.2400017f) {
        return 0.0423860587f;
      } else {
        return -2.29513764f;
      }
    } else {
      if (x[0] < 67.5f) {
        return 0.462751836f;
      } else {
        return -0.0301138014f;
      }
    }
  } else {
    if (x[0] < 360.75f) {
      if (x[0] < 329.75f) {
        return -0.361207724f;
      } else {
        return -3.31770563f;
      }
    } else {
      if (x[0] < 402.0f) {
        return 0.211477637f;
      } else {
        return 0.896191597f;
      }
    }
  }
}
static inline float indra_fc_1_14(const float *x) {
  if (x[0] < 67.5f) {
    if (x[0] < 48.1199989f) {
      if (x[0] < 46.4300003f) {
        return 0.0979732201f;
      } else {
        return -1.35549378f;
      }
    } else {
      if (x[0] < 51.0f) {
        return 1.18192565f;
      } else {
        return 0.391297162f;
      }
    }
  } else {
    if (x[0] < 485.75f) {
      if (x[0] < 180.0f) {
        return -0.130728826f;
      } else {
        return -0.525635898f;
      }
    } else {
      return 2.08102584f;
    }
  }
}
static inline float indra_fc_1_15(const float *x) {
  if (x[1] < 616.72998f) {
    if (x[1] < 349.25f) {
      if (x[1] < 248.25f) {
        return 1.24419391f;
      } else {
        return -1.79438329f;
      }
    } else {
      if (x[1] < 492.0f) {
        return -7.22595358f;
      } else {
        return -15.6238012f;
      }
    }
  } else {
    if (x[1] < 725.179993f) {
      return -24.2150631f;
    } else {
      return -58.3960075f;
    }
  }
}
static inline float indra_fc_head_1(const float *x) {
  float residual = 0.11602286f;
  residual += indra_fc_1_0(x);
  residual += indra_fc_1_1(x);
  residual += indra_fc_1_2(x);
  residual += indra_fc_1_3(x);
  residual += indra_fc_1_4(x);
  residual += indra_fc_1_5(x);
  residual += indra_fc_1_6(x);
  residual += indra_fc_1_7(x);
  residual += indra_fc_1_8(x);
  residual += indra_fc_1_9(x);
  residual += indra_fc_1_10(x);
  residual += indra_fc_1_11(x);
  residual += indra_fc_1_12(x);
  residual += indra_fc_1_13(x);
  residual += indra_fc_1_14(x);
  residual += indra_fc_1_15(x);
  float value = x[1] + 0.25f * residual;
  return fminf(5000.0f, fmaxf(0.0f, value));
}
/* Returns 1 on success, 0 for null pointers, missing or out-of-range inputs.
 * Pass distinct arrays. Outputs are NAN on invalid sensor data. No heap allocation. */
static inline int indra_forecast_predict(const float *input, float *output) {
  if (!input || !output) return 0;
  float x[2];
  for (int i = 0; i < 2; ++i) x[i] = input[i];
  for (int i = 0; i < 2; ++i) output[i] = NAN;
  if (!isfinite(x[0]) || x[0] < 0.0f || x[0] > 5000.0f) return 0;
  if (!isfinite(x[1]) || x[1] < 0.0f || x[1] > 5000.0f) return 0;
  output[0] = indra_fc_head_0(x);
  output[1] = indra_fc_head_1(x);
  return 1;
}
#endif
