[platformio]
default_envs = operational-driver-preparation

[env:operational-driver-preparation]
platform = espressif32@7.0.1
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit BME280 Library@2.3.0
  adafruit/Adafruit INA219@1.2.3
  adafruit/RTClib@2.1.4
  https://github.com/mikalhart/TinyGPSPlus.git#v1.0.3a
