[platformio]
default_envs = esp32-s3-ml

[env:esp32-s3-ml]
platform = espressif32@7.0.1
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
extra_scripts = pre:tools/build_identity.py
build_flags =
    -std=gnu++17
    -I../../ml/models/uci_beijing_6h/esp32_student/export
    -I../../ml/models/uci_beijing_event_rules_6sensor/esp32_student/export
build_unflags = -std=gnu++11

[env:esp32-s3-ml-usb]
extends = env:esp32-s3-ml
build_flags =
    ${env:esp32-s3-ml.build_flags}
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
