/* Generated by python -m ml.six_sensor_forecast.export. Research forecast, not a hazard alarm. */
#ifndef INDRA_SIX_SENSOR_FORECAST_H
#define INDRA_SIX_SENSOR_FORECAST_H
#include <math.h>
#include <stddef.h>
#define INDRA_FORECAST_INPUTS 6
#define INDRA_FORECAST_OUTPUTS 6
#define INDRA_FORECAST_HORIZON_HOURS 6
#define INDRA_FORECAST_STATUS "OFFLINE_RESEARCH_ONLY"
/* Input/output order: temperature_c, relative_humidity_pct, pressure_hpa, pm25_ug_m3, pm10_ug_m3, wind_speed_mps */
static inline float indra_fc_0_0(const float *x) {
  if (x[5] < 1.60000002f) {
    if (x[0] < 25.7999992f) {
      if (x[0] < -4.0f) {
        return 0.913692176f;
      } else {
        return 0.303654492f;
      }
    } else {
      if (x[0] < 29.7999992f) {
        return -0.194590092f;
      } else {
        return -0.720504165f;
      }
    }
  } else {
    if (x[0] < 27.2999992f) {
      if (x[0] < -1.0f) {
        return 0.308117479f;
      } else {
        return -0.313015908f;
      }
    } else {
      if (x[0] < 32.2000008f) {
        return -0.680790246f;
      } else {
        return -0.972698331f;
      }
    }
  }
}
static inline float indra_fc_0_1(const float *x) {
  if (x[1] < 51.1287041f) {
    if (x[0] < 0.600000024f) {
      if (x[0] < -4.69999981f) {
        return 0.632137835f;
      } else {
        return 0.0862310901f;
      }
    } else {
      if (x[1] < 34.9684372f) {
        return -0.579047024f;
      } else {
        return -0.272601992f;
      }
    }
  } else {
    if (x[0] < 24.7999992f) {
      if (x[3] < 132.0f) {
        return 0.473697722f;
      } else {
        return 0.21183753f;
      }
    } else {
      if (x[0] < 28.7000008f) {
        return 0.0134289032f;
      } else {
        return -0.410626262f;
      }
    }
  }
}
static inline float indra_fc_0_2(const float *x) {
  if (x[1] < 57.0555687f) {
    if (x[0] < 0.0f) {
      if (x[0] < -6.5999999f) {
        return 0.865235984f;
      } else {
        return 0.177227944f;
      }
    } else {
      if (x[1] < 30.0456753f) {
        return -0.494033337f;
      } else {
        return -0.216705665f;
      }
    }
  } else {
    if (x[0] < 24.2999992f) {
      if (x[3] < 165.0f) {
        return 0.40656358f;
      } else {
        return 0.1585695f;
      }
    } else {
      if (x[1] < 75.9806213f) {
        return -0.137895599f;
      } else {
        return 0.190025672f;
      }
    }
  }
}
static inline float indra_fc_0_3(const float *x) {
  if (x[1] < 47.0298958f) {
    if (x[0] < 10.8999996f) {
      if (x[0] < -2.0999999f) {
        return 0.295249671f;
      } else {
        return -0.130178392f;
      }
    } else {
      if (x[0] < 21.2999992f) {
        return -0.311966568f;
      } else {
        return -0.527219236f;
      }
    }
  } else {
    if (x[0] < 19.3999996f) {
      if (x[3] < 137.0f) {
        return 0.405394763f;
      } else {
        return 0.140208215f;
      }
    } else {
      if (x[1] < 68.0346451f) {
        return -0.165909961f;
      } else {
        return 0.156153366f;
      }
    }
  }
}
static inline float indra_fc_0_4(const float *x) {
  if (x[1] < 60.9866409f) {
    if (x[0] < 1.70000005f) {
      if (x[2] < 1017.59998f) {
        return 0.470804423f;
      } else {
        return 0.0655697733f;
      }
    } else {
      if (x[1] < 26.0845718f) {
        return -0.387869924f;
      } else {
        return -0.151930496f;
      }
    }
  } else {
    if (x[5] < 1.89999998f) {
      if (x[0] < 19.3999996f) {
        return 0.312711895f;
      } else {
        return 0.124338739f;
      }
    } else {
      if (x[0] < 27.8999996f) {
        return -0.0237116534f;
      } else {
        return -0.360985816f;
      }
    }
  }
}
static inline float indra_fc_0_5(const float *x) {
  if (x[1] < 42.0148277f) {
    if (x[0] < 10.6999998f) {
      if (x[4] < 38.0999985f) {
        return 0.090126656f;
      } else {
        return -0.189531788f;
      }
    } else {
      if (x[0] < 21.6000004f) {
        return -0.231218606f;
      } else {
        return -0.405228227f;
      }
    }
  } else {
    if (x[0] < 26.2000008f) {
      if (x[5] < 2.0999999f) {
        return 0.185719684f;
      } else {
        return -0.115722708f;
      }
    } else {
      if (x[0] < 30.0f) {
        return -0.103991322f;
      } else {
        return -0.336819261f;
      }
    }
  }
}
static inline float indra_fc_0_6(const float *x) {
  if (x[1] < 63.9932823f) {
    if (x[0] < 17.3999996f) {
      if (x[1] < 26.0179157f) {
        return -0.184555069f;
      } else {
        return 0.0872539058f;
      }
    } else {
      if (x[1] < 35.8965683f) {
        return -0.327468723f;
      } else {
        return -0.1589614f;
      }
    }
  } else {
    if (x[3] < 36.0f) {
      if (x[0] < 17.2000008f) {
        return 0.472000331f;
      } else {
        return 0.184641495f;
      }
    } else {
      if (x[0] < -4.30000019f) {
        return 0.496891409f;
      } else {
        return 0.0997999534f;
      }
    }
  }
}
static inline float indra_fc_0_7(const float *x) {
  if (x[1] < 39.9852715f) {
    if (x[4] < 43.0f) {
      if (x[0] < 27.6000004f) {
        return 0.0202680472f;
      } else {
        return -0.313147515f;
      }
    } else {
      if (x[0] < -3.9000001f) {
        return 0.21210888f;
      } else {
        return -0.230745912f;
      }
    }
  } else {
    if (x[0] < 23.5f) {
      if (x[2] < 1003.0f) {
        return 0.345043451f;
      } else {
        return 0.0827173814f;
      }
    } else {
      if (x[5] < 2.20000005f) {
        return -0.0328029357f;
      } else {
        return -0.267982811f;
      }
    }
  }
}
static inline float indra_fc_0_8(const float *x) {
  if (x[5] < 1.29999995f) {
    if (x[0] < -6.5999999f) {
      if (x[0] < -8.0f) {
        return 0.942265034f;
      } else {
        return 0.596145093f;
      }
    } else {
      if (x[3] < 180.0f) {
        return 0.11739029f;
      } else {
        return -0.0921824649f;
      }
    }
  } else {
    if (x[4] < 47.0f) {
      if (x[1] < 24.0435333f) {
        return -0.124714315f;
      } else {
        return 0.116365433f;
      }
    } else {
      if (x[5] < 2.0999999f) {
        return -0.0644101948f;
      } else {
        return -0.225474879f;
      }
    }
  }
}
static inline float indra_fc_0_9(const float *x) {
  if (x[1] < 71.2236176f) {
    if (x[0] < -1.70000005f) {
      if (x[2] < 1017.59998f) {
        return 0.591652811f;
      } else {
        return 0.131762505f;
      }
    } else {
      if (x[3] < 198.0f) {
        return -0.0613435507f;
      } else {
        return -0.317993492f;
      }
    }
  } else {
    if (x[0] < 17.2000008f) {
      if (x[2] < 1017.70001f) {
        return 0.298393935f;
      } else {
        return 0.0170472134f;
      }
    } else {
      if (x[2] < 1007.09998f) {
        return 0.103082314f;
      } else {
        return -0.135639966f;
      }
    }
  }
}
static inline float indra_fc_0_10(const float *x) {
  if (x[0] < 28.0f) {
    if (x[5] < 1.89999998f) {
      if (x[0] < -6.5999999f) {
        return 0.540707767f;
      } else {
        return 0.0529616363f;
      }
    } else {
      if (x[4] < 54.0f) {
        return 0.0319557227f;
      } else {
        return -0.141870022f;
      }
    }
  } else {
    if (x[0] < 33.2999992f) {
      if (x[2] < 999.299988f) {
        return -0.240220815f;
      } else {
        return -0.0983411074f;
      }
    } else {
      if (x[2] < 990.799988f) {
        return -0.742379069f;
      } else {
        return -0.352147311f;
      }
    }
  }
}
static inline float indra_fc_0_11(const float *x) {
  if (x[1] < 33.879055f) {
    if (x[3] < 17.0f) {
      if (x[0] < 15.5f) {
        return 0.0463602208f;
      } else {
        return -0.199252591f;
      }
    } else {
      if (x[0] < -4.69999981f) {
        return 0.258355618f;
      } else {
        return -0.169748515f;
      }
    }
  } else {
    if (x[3] < 24.0f) {
      if (x[0] < 15.8000002f) {
        return 0.37167713f;
      } else {
        return 0.128917322f;
      }
    } else {
      if (x[5] < 2.4000001f) {
        return 0.0280661471f;
      } else {
        return -0.193881124f;
      }
    }
  }
}
static inline float indra_fc_0_12(const float *x) {
  if (x[0] < 26.5f) {
    if (x[2] < 1008.0f) {
      if (x[0] < 17.5f) {
        return 0.33313033f;
      } else {
        return 0.0446676649f;
      }
    } else {
      if (x[0] < 12.0f) {
        return 0.0330904648f;
      } else {
        return -0.127932712f;
      }
    }
  } else {
    if (x[0] < 32.5f) {
      if (x[3] < 114.0f) {
        return -0.121294133f;
      } else {
        return -0.00584902475f;
      }
    } else {
      if (x[2] < 991.700012f) {
        return -0.592774749f;
      } else {
        return -0.212009117f;
      }
    }
  }
}
static inline float indra_fc_0_13(const float *x) {
  if (x[1] < 23.0479851f) {
    if (x[5] < 1.60000002f) {
      if (x[5] < 0.600000024f) {
        return 0.035326656f;
      } else {
        return -0.316529125f;
      }
    } else {
      if (x[1] < 12.0174017f) {
        return -0.197828919f;
      } else {
        return -0.0689740404f;
      }
    }
  } else {
    if (x[3] < 31.0f) {
      if (x[1] < 35.8965683f) {
        return 0.0504937731f;
      } else {
        return 0.162154168f;
      }
    } else {
      if (x[1] < 73.9339828f) {
        return -0.0585636012f;
      } else {
        return 0.0657454506f;
      }
    }
  }
}
static inline float indra_fc_0_14(const float *x) {
  if (x[4] < 258.0f) {
    if (x[1] < 38.9503326f) {
      if (x[3] < 17.0f) {
        return 0.00675607566f;
      } else {
        return -0.0967793614f;
      }
    } else {
      if (x[5] < 2.4000001f) {
        return 0.0599700622f;
      } else {
        return -0.112979569f;
      }
    }
  } else {
    if (x[3] < 321.0f) {
      if (x[1] < 69.0801163f) {
        return -0.181081399f;
      } else {
        return 0.00329207862f;
      }
    } else {
      if (x[2] < 1013.79999f) {
        return -0.392443985f;
      } else {
        return -0.179527596f;
      }
    }
  }
}
static inline float indra_fc_0_15(const float *x) {
  if (x[0] < 19.5f) {
    if (x[1] < 26.0179157f) {
      if (x[5] < 1.60000002f) {
        return -0.192268461f;
      } else {
        return -0.0361294411f;
      }
    } else {
      if (x[3] < 125.0f) {
        return 0.116202392f;
      } else {
        return -0.0404494926f;
      }
    }
  } else {
    if (x[1] < 12.0174017f) {
      if (x[0] < 21.6000004f) {
        return -0.119548336f;
      } else {
        return -0.537025094f;
      }
    } else {
      if (x[4] < 56.0f) {
        return 0.00666534854f;
      } else {
        return -0.0756858662f;
      }
    }
  }
}
static inline float indra_fc_head_0(const float *x) {
  float residual = 0.007264564f;
  residual += indra_fc_0_0(x);
  residual += indra_fc_0_1(x);
  residual += indra_fc_0_2(x);
  residual += indra_fc_0_3(x);
  residual += indra_fc_0_4(x);
  residual += indra_fc_0_5(x);
  residual += indra_fc_0_6(x);
  residual += indra_fc_0_7(x);
  residual += indra_fc_0_8(x);
  residual += indra_fc_0_9(x);
  residual += indra_fc_0_10(x);
  residual += indra_fc_0_11(x);
  residual += indra_fc_0_12(x);
  residual += indra_fc_0_13(x);
  residual += indra_fc_0_14(x);
  residual += indra_fc_0_15(x);
  float value = x[0] + 1.0f * residual;
  return fminf(85.0f, fmaxf(-60.0f, value));
}
static inline float indra_fc_1_0(const float *x) {
  if (x[5] < 1.5f) {
    if (x[0] < 26.1000004f) {
      if (x[5] < 0.899999976f) {
        return -1.94380879f;
      } else {
        return -0.89176923f;
      }
    } else {
      if (x[3] < 64.9000015f) {
        return 2.58009362f;
      } else {
        return 0.582082331f;
      }
    }
  } else {
    if (x[0] < 26.5f) {
      if (x[0] < 1.70000005f) {
        return -0.285566717f;
      } else {
        return 1.11501396f;
      }
    } else {
      if (x[3] < 96.0f) {
        return 3.08614135f;
      } else {
        return 1.82482743f;
      }
    }
  }
}
static inline float indra_fc_1_1(const float *x) {
  if (x[1] < 63.9932823f) {
    if (x[0] < 0.0f) {
      if (x[1] < 44.0697098f) {
        return 0.0571578145f;
      } else {
        return -1.5542115f;
      }
    } else {
      if (x[1] < 47.0298958f) {
        return 2.10601306f;
      } else {
        return 0.743635237f;
      }
    }
  } else {
    if (x[0] < 23.2000008f) {
      if (x[1] < 78.9505386f) {
        return -1.7493118f;
      } else {
        return -2.8639605f;
      }
    } else {
      if (x[1] < 77.7292786f) {
        return 0.143788487f;
      } else {
        return -1.50647926f;
      }
    }
  }
}
static inline float indra_fc_1_2(const float *x) {
  if (x[1] < 60.9866409f) {
    if (x[0] < 1.39999998f) {
      if (x[0] < -5.69999981f) {
        return -1.85330963f;
      } else {
        return 0.0929075778f;
      }
    } else {
      if (x[0] < 20.5f) {
        return 1.10926592f;
      } else {
        return 2.00284338f;
      }
    }
  } else {
    if (x[0] < 24.2999992f) {
      if (x[1] < 73.9339828f) {
        return -1.09618843f;
      } else {
        return -2.16782045f;
      }
    } else {
      if (x[1] < 75.9806213f) {
        return 0.508432925f;
      } else {
        return -1.001261f;
      }
    }
  }
}
static inline float indra_fc_1_3(const float *x) {
  if (x[1] < 57.0555687f) {
    if (x[0] < 11.6000004f) {
      if (x[1] < 39.9852715f) {
        return 0.804749787f;
      } else {
        return -0.290174216f;
      }
    } else {
      if (x[1] < 46.1150894f) {
        return 1.76174891f;
      } else {
        return 0.952524304f;
      }
    }
  } else {
    if (x[0] < 19.2999992f) {
      if (x[3] < 142.0f) {
        return -2.11595845f;
      } else {
        return -0.931427896f;
      }
    } else {
      if (x[1] < 70.1881485f) {
        return 0.368632495f;
      } else {
        return -0.915191591f;
      }
    }
  }
}
static inline float indra_fc_1_4(const float *x) {
  if (x[1] < 67.1613235f) {
    if (x[0] < -1.70000005f) {
      if (x[0] < -6.5999999f) {
        return -2.29456306f;
      } else {
        return -0.582181156f;
      }
    } else {
      if (x[1] < 51.1287041f) {
        return 1.07978475f;
      } else {
        return 0.165671974f;
      }
    }
  } else {
    if (x[0] < 19.3999996f) {
      if (x[2] < 1003.5f) {
        return -3.46175194f;
      } else {
        return -1.40830421f;
      }
    } else {
      if (x[2] < 1007.09998f) {
        return -0.825912476f;
      } else {
        return 0.189759418f;
      }
    }
  }
}
static inline float indra_fc_1_5(const float *x) {
  if (x[1] < 68.0239792f) {
    if (x[0] < -1.0f) {
      if (x[1] < 52.0084305f) {
        return -0.266664207f;
      } else {
        return -1.35613716f;
      }
    } else {
      if (x[1] < 46.1150894f) {
        return 0.920498371f;
      } else {
        return 0.232351184f;
      }
    }
  } else {
    if (x[1] < 87.8255844f) {
      if (x[0] < -3.9000001f) {
        return -2.58958769f;
      } else {
        return -0.551736176f;
      }
    } else {
      if (x[0] < 17.2000008f) {
        return -1.91395402f;
      } else {
        return -1.03383434f;
      }
    }
  }
}
static inline float indra_fc_1_6(const float *x) {
  if (x[1] < 56.0153275f) {
    if (x[0] < 17.3999996f) {
      if (x[3] < 19.2999992f) {
        return -0.268238902f;
      } else {
        return 0.575195789f;
      }
    } else {
      if (x[2] < 1007.70001f) {
        return 0.889935493f;
      } else {
        return 1.42729962f;
      }
    }
  } else {
    if (x[0] < 25.5f) {
      if (x[3] < 132.0f) {
        return -0.992659509f;
      } else {
        return -0.271084428f;
      }
    } else {
      if (x[0] < 28.7000008f) {
        return 0.07329797f;
      } else {
        return 1.33902013f;
      }
    }
  }
}
static inline float indra_fc_1_7(const float *x) {
  if (x[1] < 71.2236176f) {
    if (x[0] < 0.600000024f) {
      if (x[2] < 1017.59998f) {
        return -1.6303618f;
      } else {
        return -0.112475097f;
      }
    } else {
      if (x[0] < 29.1000004f) {
        return 0.354710191f;
      } else {
        return 1.1341027f;
      }
    }
  } else {
    if (x[0] < 17.2000008f) {
      if (x[2] < 1020.5f) {
        return -1.48244858f;
      } else {
        return -0.113810591f;
      }
    } else {
      if (x[2] < 1007.59998f) {
        return -0.546964228f;
      } else {
        return 0.276182979f;
      }
    }
  }
}
static inline float indra_fc_1_8(const float *x) {
  if (x[1] < 52.1510239f) {
    if (x[5] < 3.4000001f) {
      if (x[1] < 34.9684372f) {
        return 0.863911629f;
      } else {
        return 0.227531776f;
      }
    } else {
      if (x[0] < 16.2999992f) {
        return -0.471356481f;
      } else {
        return 0.210653096f;
      }
    }
  } else {
    if (x[0] < 23.0f) {
      if (x[3] < 180.0f) {
        return -0.775385082f;
      } else {
        return 0.158151805f;
      }
    } else {
      if (x[0] < 29.2999992f) {
        return -0.00599513715f;
      } else {
        return 1.07517183f;
      }
    }
  }
}
static inline float indra_fc_1_9(const float *x) {
  if (x[1] < 75.9806213f) {
    if (x[0] < 11.6000004f) {
      if (x[2] < 1016.0f) {
        return -0.698523402f;
      } else {
        return 0.138192385f;
      }
    } else {
      if (x[2] < 1009.59998f) {
        return 0.279975832f;
      } else {
        return 0.802206457f;
      }
    }
  } else {
    if (x[0] < -3.9000001f) {
      if (x[1] < 85.9800186f) {
        return -1.80464423f;
      } else {
        return -3.18029952f;
      }
    } else {
      if (x[2] < 1021.0f) {
        return -0.617728829f;
      } else {
        return 0.400415957f;
      }
    }
  }
}
static inline float indra_fc_1_10(const float *x) {
  if (x[0] < 24.2999992f) {
    if (x[2] < 1002.40002f) {
      if (x[0] < 18.2000008f) {
        return -2.14013243f;
      } else {
        return -0.631805182f;
      }
    } else {
      if (x[0] < -4.30000019f) {
        return -1.22848976f;
      } else {
        return 0.0408190638f;
      }
    }
  } else {
    if (x[0] < 30.0f) {
      if (x[2] < 1008.5f) {
        return 0.202283382f;
      } else {
        return 1.10648477f;
      }
    } else {
      if (x[2] < 999.0f) {
        return 1.13264215f;
      } else {
        return 0.493103981f;
      }
    }
  }
}
static inline float indra_fc_1_11(const float *x) {
  if (x[1] < 42.0148277f) {
    if (x[5] < 3.0999999f) {
      if (x[0] < 2.4000001f) {
        return 0.0579414666f;
      } else {
        return 0.733646154f;
      }
    } else {
      if (x[3] < 23.0f) {
        return -0.415348619f;
      } else {
        return 0.103654005f;
      }
    }
  } else {
    if (x[3] < 24.0f) {
      if (x[0] < 16.2999992f) {
        return -1.79572392f;
      } else {
        return -0.589916706f;
      }
    } else {
      if (x[1] < 86.1757889f) {
        return 0.0605651513f;
      } else {
        return -0.592674971f;
      }
    }
  }
}
static inline float indra_fc_1_12(const float *x) {
  if (x[0] < 19.8999996f) {
    if (x[2] < 1009.59998f) {
      if (x[2] < 994.700012f) {
        return -3.30214763f;
      } else {
        return -0.724515498f;
      }
    } else {
      if (x[0] < -3.9000001f) {
        return -0.851341188f;
      } else {
        return 0.106006734f;
      }
    }
  } else {
    if (x[2] < 1006.59998f) {
      if (x[0] < 28.0f) {
        return -0.0668613836f;
      } else {
        return 0.514057696f;
      }
    } else {
      if (x[5] < 1.0f) {
        return 1.31466234f;
      } else {
        return 0.547086418f;
      }
    }
  }
}
static inline float indra_fc_1_13(const float *x) {
  if (x[1] < 51.8942757f) {
    if (x[3] < 18.0f) {
      if (x[1] < 29.0764313f) {
        return 0.109225176f;
      } else {
        return -0.590511739f;
      }
    } else {
      if (x[2] < 1020.0f) {
        return 0.286188751f;
      } else {
        return 0.834447086f;
      }
    }
  } else {
    if (x[5] < 2.0f) {
      if (x[3] < 31.0f) {
        return -0.938219726f;
      } else {
        return -0.189406052f;
      }
    } else {
      if (x[3] < 15.8999996f) {
        return -0.436910778f;
      } else {
        return 0.625498891f;
      }
    }
  }
}
static inline float indra_fc_1_14(const float *x) {
  if (x[1] < 95.8073196f) {
    if (x[1] < 38.9503326f) {
      if (x[5] < 2.9000001f) {
        return 0.486289501f;
      } else {
        return -0.185923845f;
      }
    } else {
      if (x[3] < 32.0f) {
        return -0.537988603f;
      } else {
        return 0.0281844139f;
      }
    }
  } else {
    if (x[3] < 394.0f) {
      if (x[5] < 1.29999995f) {
        return -1.15741241f;
      } else {
        return -0.20052126f;
      }
    } else {
      if (x[2] < 1013.70001f) {
        return 2.08969569f;
      } else {
        return 1.20937884f;
      }
    }
  }
}
static inline float indra_fc_1_15(const float *x) {
  if (x[0] < 12.0f) {
    if (x[1] < 80.8516235f) {
      if (x[3] < 35.0f) {
        return -0.408565372f;
      } else {
        return 0.0760976747f;
      }
    } else {
      if (x[5] < 1.0f) {
        return -1.28897989f;
      } else {
        return -0.136142671f;
      }
    }
  } else {
    if (x[3] < 214.0f) {
      if (x[1] < 48.9643478f) {
        return 0.314030141f;
      } else {
        return 0.0114244437f;
      }
    } else {
      if (x[5] < 0.800000012f) {
        return 1.67134118f;
      } else {
        return 0.544972897f;
      }
    }
  }
}
static inline float indra_fc_head_1(const float *x) {
  float residual = -0.0077665034f;
  residual += indra_fc_1_0(x);
  residual += indra_fc_1_1(x);
  residual += indra_fc_1_2(x);
  residual += indra_fc_1_3(x);
  residual += indra_fc_1_4(x);
  residual += indra_fc_1_5(x);
  residual += indra_fc_1_6(x);
  residual += indra_fc_1_7(x);
  residual += indra_fc_1_8(x);
  residual += indra_fc_1_9(x);
  residual += indra_fc_1_10(x);
  residual += indra_fc_1_11(x);
  residual += indra_fc_1_12(x);
  residual += indra_fc_1_13(x);
  residual += indra_fc_1_14(x);
  residual += indra_fc_1_15(x);
  float value = x[1] + 0.75f * residual;
  return fminf(100.0f, fmaxf(0.0f, value));
}
static inline float indra_fc_2_0(const float *x) {
  if (x[5] < 3.20000005f) {
    if (x[2] < 1015.09998f) {
      if (x[2] < 996.400024f) {
        return 0.130797684f;
      } else {
        return 0.00361074484f;
      }
    } else {
      if (x[2] < 1027.80005f) {
        return -0.0695322007f;
      } else {
        return -0.245479301f;
      }
    }
  } else {
    if (x[2] < 1026.80005f) {
      if (x[5] < 4.9000001f) {
        return 0.156912461f;
      } else {
        return 0.337457746f;
      }
    } else {
      if (x[2] < 1031.59998f) {
        return -0.0781981722f;
      } else {
        return -0.411040157f;
      }
    }
  }
}
static inline float indra_fc_2_1(const float *x) {
  if (x[5] < 2.5999999f) {
    if (x[2] < 1024.0f) {
      if (x[1] < 22.9271145f) {
        return 0.121510796f;
      } else {
        return -0.0153574487f;
      }
    } else {
      if (x[2] < 1030.0f) {
        return -0.115831695f;
      } else {
        return -0.25247249f;
      }
    }
  } else {
    if (x[2] < 1024.09998f) {
      if (x[5] < 5.69999981f) {
        return 0.119531728f;
      } else {
        return 0.357856721f;
      }
    } else {
      if (x[2] < 1031.0f) {
        return -0.0325365774f;
      } else {
        return -0.259422749f;
      }
    }
  }
}
static inline float indra_fc_2_2(const float *x) {
  if (x[5] < 4.0f) {
    if (x[0] < 30.0f) {
      if (x[1] < 16.9416828f) {
        return 0.114264682f;
      } else {
        return -0.0234390348f;
      }
    } else {
      if (x[1] < 38.9522972f) {
        return 0.150650486f;
      } else {
        return 0.048190482f;
      }
    }
  } else {
    if (x[4] < 40.2999992f) {
      if (x[0] < -0.200000003f) {
        return -0.0228262022f;
      } else {
        return 0.107707419f;
      }
    } else {
      if (x[1] < 13.0235758f) {
        return 0.434446335f;
      } else {
        return 0.195583269f;
      }
    }
  }
}
static inline float indra_fc_2_3(const float *x) {
  if (x[5] < 2.4000001f) {
    if (x[5] < 0.800000012f) {
      if (x[0] < 10.0f) {
        return -0.0171720758f;
      } else {
        return 0.055235602f;
      }
    } else {
      if (x[0] < 30.0f) {
        return -0.0407588445f;
      } else {
        return 0.070493266f;
      }
    }
  } else {
    if (x[1] < 13.0235758f) {
      if (x[4] < 52.7999992f) {
        return 0.0803245306f;
      } else {
        return 0.361872107f;
      }
    } else {
      if (x[5] < 5.0999999f) {
        return 0.0412192158f;
      } else {
        return 0.176884696f;
      }
    }
  }
}
static inline float indra_fc_2_4(const float *x) {
  if (x[2] < 1014.20001f) {
    if (x[1] < 20.0008793f) {
      if (x[2] < 1005.70001f) {
        return 0.315992564f;
      } else {
        return 0.143511206f;
      }
    } else {
      if (x[3] < 296.0f) {
        return 0.0136304619f;
      } else {
        return 0.229409859f;
      }
    }
  } else {
    if (x[2] < 1028.0f) {
      if (x[3] < 14.6999998f) {
        return 0.0458170883f;
      } else {
        return -0.0540473349f;
      }
    } else {
      if (x[0] < 7.0999999f) {
        return -0.140285209f;
      } else {
        return -0.559442341f;
      }
    }
  }
}
static inline float indra_fc_2_5(const float *x) {
  if (x[5] < 2.5999999f) {
    if (x[4] < 226.0f) {
      if (x[5] < 0.600000024f) {
        return 0.0268346649f;
      } else {
        return -0.0294149704f;
      }
    } else {
      if (x[3] < 286.0f) {
        return 0.0333532803f;
      } else {
        return 0.091277577f;
      }
    }
  } else {
    if (x[4] < 229.0f) {
      if (x[1] < 12.0174017f) {
        return 0.154787645f;
      } else {
        return 0.0370682292f;
      }
    } else {
      if (x[1] < 18.9366207f) {
        return 0.440154284f;
      } else {
        return 0.175109193f;
      }
    }
  }
}
static inline float indra_fc_2_6(const float *x) {
  if (x[2] < 1017.09998f) {
    if (x[1] < 33.0513496f) {
      if (x[0] < 12.3000002f) {
        return 0.166964442f;
      } else {
        return 0.0608259328f;
      }
    } else {
      if (x[2] < 997.5f) {
        return 0.0721987933f;
      } else {
        return -0.00896700658f;
      }
    }
  } else {
    if (x[2] < 1028.80005f) {
      if (x[0] < 11.3999996f) {
        return -0.0230831746f;
      } else {
        return -0.119982183f;
      }
    } else {
      if (x[0] < 6.5f) {
        return -0.122967146f;
      } else {
        return -0.506723642f;
      }
    }
  }
}
static inline float indra_fc_2_7(const float *x) {
  if (x[2] < 1013.09998f) {
    if (x[1] < 15.0189819f) {
      if (x[2] < 1007.09998f) {
        return 0.322235405f;
      } else {
        return 0.100496463f;
      }
    } else {
      if (x[4] < 249.0f) {
        return 0.00858725049f;
      } else {
        return 0.116358735f;
      }
    }
  } else {
    if (x[0] < 18.1000004f) {
      if (x[2] < 1025.80005f) {
        return -0.00743565662f;
      } else {
        return -0.0849236771f;
      }
    } else {
      if (x[1] < 73.7545242f) {
        return -0.172162056f;
      } else {
        return -0.0571155362f;
      }
    }
  }
}
static inline float indra_fc_2_8(const float *x) {
  if (x[1] < 33.9563255f) {
    if (x[0] < -0.200000003f) {
      if (x[1] < 23.0479851f) {
        return -0.0924260244f;
      } else {
        return -0.0200184602f;
      }
    } else {
      if (x[4] < 223.0f) {
        return 0.0397162549f;
      } else {
        return 0.199592486f;
      }
    }
  } else {
    if (x[5] < 0.899999976f) {
      if (x[4] < 223.0f) {
        return 0.00876816828f;
      } else {
        return 0.072428368f;
      }
    } else {
      if (x[5] < 2.0999999f) {
        return -0.0377361961f;
      } else {
        return 0.00962872803f;
      }
    }
  }
}
static inline float indra_fc_2_9(const float *x) {
  if (x[2] < 999.799988f) {
    if (x[1] < 64.8433533f) {
      if (x[0] < 14.5f) {
        return 0.26073119f;
      } else {
        return 0.080032289f;
      }
    } else {
      if (x[2] < 992.900024f) {
        return 0.0806109011f;
      } else {
        return 0.000369808462f;
      }
    }
  } else {
    if (x[5] < 4.0999999f) {
      if (x[1] < 87.2028656f) {
        return -0.0219712742f;
      } else {
        return 0.030864099f;
      }
    } else {
      if (x[2] < 1031.0f) {
        return 0.0831287876f;
      } else {
        return -0.236784026f;
      }
    }
  }
}
static inline float indra_fc_2_10(const float *x) {
  if (x[2] < 1023.09998f) {
    if (x[3] < 20.7000008f) {
      if (x[0] < 12.1000004f) {
        return 0.113745175f;
      } else {
        return 0.0129859364f;
      }
    } else {
      if (x[4] < 242.0f) {
        return -0.0106797535f;
      } else {
        return 0.0673687235f;
      }
    }
  } else {
    if (x[0] < 7.69999981f) {
      if (x[2] < 1031.59998f) {
        return -0.0297574904f;
      } else {
        return -0.134278476f;
      }
    } else {
      if (x[2] < 1026.19995f) {
        return -0.0960349143f;
      } else {
        return -0.332525164f;
      }
    }
  }
}
static inline float indra_fc_2_11(const float *x) {
  if (x[1] < 33.9563255f) {
    if (x[0] < 0.200000003f) {
      if (x[1] < 22.0513992f) {
        return -0.0598820038f;
      } else {
        return -0.00303418539f;
      }
    } else {
      if (x[0] < 11.6000004f) {
        return 0.0675000101f;
      } else {
        return 0.0124235628f;
      }
    }
  } else {
    if (x[1] < 88.9687347f) {
      if (x[5] < 0.5f) {
        return 0.0349113084f;
      } else {
        return -0.0224006008f;
      }
    } else {
      if (x[4] < 54.5f) {
        return -0.00414068764f;
      } else {
        return 0.0423334651f;
      }
    }
  }
}
static inline float indra_fc_2_12(const float *x) {
  if (x[2] < 1013.09998f) {
    if (x[0] < 7.0999999f) {
      if (x[2] < 995.0f) {
        return 0.921765327f;
      } else {
        return 0.0890552327f;
      }
    } else {
      if (x[2] < 995.299988f) {
        return 0.0807929486f;
      } else {
        return 0.00459011225f;
      }
    }
  } else {
    if (x[0] < 16.5f) {
      if (x[3] < 15.8999996f) {
        return 0.020015059f;
      } else {
        return -0.0273658633f;
      }
    } else {
      if (x[3] < 8.5f) {
        return 0.00889001228f;
      } else {
        return -0.113525905f;
      }
    }
  }
}
static inline float indra_fc_2_13(const float *x) {
  if (x[2] < 1003.40002f) {
    if (x[1] < 44.9844894f) {
      if (x[4] < 215.0f) {
        return 0.0685788915f;
      } else {
        return 0.23641102f;
      }
    } else {
      if (x[2] < 995.299988f) {
        return 0.0524418354f;
      } else {
        return 0.000246851094f;
      }
    }
  } else {
    if (x[3] < 223.0f) {
      if (x[3] < 23.7999992f) {
        return 0.0121522453f;
      } else {
        return -0.0257991981f;
      }
    } else {
      if (x[2] < 1022.0f) {
        return 0.0746883526f;
      } else {
        return -0.0503102951f;
      }
    }
  }
}
static inline float indra_fc_2_14(const float *x) {
  if (x[2] < 1015.09998f) {
    if (x[1] < 13.9674568f) {
      if (x[2] < 1007.09998f) {
        return 0.262799323f;
      } else {
        return 0.0681254342f;
      }
    } else {
      if (x[5] < 6.0999999f) {
        return 0.00656074611f;
      } else {
        return 0.234158441f;
      }
    }
  } else {
    if (x[2] < 1033.5f) {
      if (x[3] < 13.3999996f) {
        return 0.0123970816f;
      } else {
        return -0.0294535346f;
      }
    } else {
      if (x[1] < 31.9944839f) {
        return -0.43390733f;
      } else {
        return -0.0245224219f;
      }
    }
  }
}
static inline float indra_fc_2_15(const float *x) {
  if (x[5] < 2.0f) {
    if (x[1] < 79.8065567f) {
      if (x[5] < 0.400000006f) {
        return 0.0454773083f;
      } else {
        return -0.0239354931f;
      }
    } else {
      if (x[0] < 22.2999992f) {
        return 0.0295306724f;
      } else {
        return -0.0278536566f;
      }
    }
  } else {
    if (x[4] < 49.0f) {
      if (x[0] < 5.30000019f) {
        return 0.0330431722f;
      } else {
        return -0.0304101799f;
      }
    } else {
      if (x[3] < 23.6000004f) {
        return 0.14004308f;
      } else {
        return 0.0210124347f;
      }
    }
  }
}
static inline float indra_fc_head_2(const float *x) {
  float residual = -0.0018158033f;
  residual += indra_fc_2_0(x);
  residual += indra_fc_2_1(x);
  residual += indra_fc_2_2(x);
  residual += indra_fc_2_3(x);
  residual += indra_fc_2_4(x);
  residual += indra_fc_2_5(x);
  residual += indra_fc_2_6(x);
  residual += indra_fc_2_7(x);
  residual += indra_fc_2_8(x);
  residual += indra_fc_2_9(x);
  residual += indra_fc_2_10(x);
  residual += indra_fc_2_11(x);
  residual += indra_fc_2_12(x);
  residual += indra_fc_2_13(x);
  residual += indra_fc_2_14(x);
  residual += indra_fc_2_15(x);
  float value = x[2] + 1.0f * residual;
  return fminf(1100.0f, fmaxf(300.0f, value));
}
static inline float indra_fc_3_0(const float *x) {
  if (x[3] < 135.0f) {
    if (x[3] < 87.0f) {
      if (x[5] < 3.0999999f) {
        return 2.06855989f;
      } else {
        return 0.787812412f;
      }
    } else {
      if (x[5] < 2.4000001f) {
        return 0.230670407f;
      } else {
        return -3.04065013f;
      }
    }
  } else {
    if (x[3] < 319.0f) {
      if (x[5] < 2.20000005f) {
        return -3.68144417f;
      } else {
        return -10.3913879f;
      }
    } else {
      if (x[3] < 460.0f) {
        return -14.3517599f;
      } else {
        return -25.5083771f;
      }
    }
  }
}
static inline float indra_fc_3_1(const float *x) {
  if (x[3] < 162.0f) {
    if (x[3] < 94.0f) {
      if (x[1] < 60.1329689f) {
        return 1.73419416f;
      } else {
        return 0.884192467f;
      }
    } else {
      if (x[5] < 2.79999995f) {
        return -0.42844364f;
      } else {
        return -4.70107126f;
      }
    }
  } else {
    if (x[3] < 357.0f) {
      if (x[5] < 2.29999995f) {
        return -3.97997594f;
      } else {
        return -10.9374075f;
      }
    } else {
      if (x[2] < 998.099976f) {
        return -49.0084648f;
      } else {
        return -14.0193281f;
      }
    }
  }
}
static inline float indra_fc_3_2(const float *x) {
  if (x[3] < 191.0f) {
    if (x[3] < 123.0f) {
      if (x[3] < 71.0f) {
        return 1.31589234f;
      } else {
        return 0.249496505f;
      }
    } else {
      if (x[0] < 17.7999992f) {
        return -0.262446076f;
      } else {
        return -3.21700025f;
      }
    }
  } else {
    if (x[3] < 335.0f) {
      if (x[5] < 2.0999999f) {
        return -3.70319343f;
      } else {
        return -9.72156525f;
      }
    } else {
      if (x[0] < 25.6000004f) {
        return -11.3491621f;
      } else {
        return -47.0895462f;
      }
    }
  }
}
static inline float indra_fc_3_3(const float *x) {
  if (x[3] < 218.0f) {
    if (x[3] < 127.0f) {
      if (x[5] < 4.0f) {
        return 0.920519471f;
      } else {
        return -0.765865862f;
      }
    } else {
      if (x[0] < 17.7999992f) {
        return -0.271924347f;
      } else {
        return -3.13508677f;
      }
    }
  } else {
    if (x[4] < 451.0f) {
      if (x[5] < 2.20000005f) {
        return -4.0484271f;
      } else {
        return -11.3401432f;
      }
    } else {
      if (x[0] < 7.69999981f) {
        return -10.4704962f;
      } else {
        return -29.6833191f;
      }
    }
  }
}
static inline float indra_fc_3_4(const float *x) {
  if (x[3] < 254.0f) {
    if (x[3] < 108.0f) {
      if (x[1] < 23.0430832f) {
        return 1.51054668f;
      } else {
        return 0.549929559f;
      }
    } else {
      if (x[5] < 4.0f) {
        return -0.933328092f;
      } else {
        return -11.4963493f;
      }
    }
  } else {
    if (x[0] < -3.9000001f) {
      if (x[3] < 357.0f) {
        return -11.051198f;
      } else {
        return -25.021574f;
      }
    } else {
      if (x[0] < 26.1000004f) {
        return -4.44510984f;
      } else {
        return -19.3638229f;
      }
    }
  }
}
static inline float indra_fc_3_5(const float *x) {
  if (x[3] < 172.0f) {
    if (x[3] < 75.0f) {
      if (x[5] < 2.5999999f) {
        return 0.946741283f;
      } else {
        return 0.0540190898f;
      }
    } else {
      if (x[5] < 2.0999999f) {
        return 0.135555416f;
      } else {
        return -2.01142645f;
      }
    }
  } else {
    if (x[3] < 306.0f) {
      if (x[0] < 24.5f) {
        return -1.24133706f;
      } else {
        return -6.00600386f;
      }
    } else {
      if (x[5] < 2.20000005f) {
        return -5.46233034f;
      } else {
        return -20.4153404f;
      }
    }
  }
}
static inline float indra_fc_3_6(const float *x) {
  if (x[3] < 145.0f) {
    if (x[5] < 2.20000005f) {
      if (x[1] < 28.8792725f) {
        return 2.24056697f;
      } else {
        return 0.357297719f;
      }
    } else {
      if (x[3] < 70.3000031f) {
        return 0.168390438f;
      } else {
        return -1.36932409f;
      }
    }
  } else {
    if (x[5] < 3.20000005f) {
      if (x[3] < 295.0f) {
        return -1.08857048f;
      } else {
        return -4.43514061f;
      }
    } else {
      if (x[3] < 295.0f) {
        return -8.54059219f;
      } else {
        return -30.1407623f;
      }
    }
  }
}
static inline float indra_fc_3_7(const float *x) {
  if (x[4] < 261.0f) {
    if (x[2] < 1018.20001f) {
      if (x[4] < 142.0f) {
        return 0.176850408f;
      } else {
        return -0.694796503f;
      }
    } else {
      if (x[0] < -3.9000001f) {
        return -0.971295774f;
      } else {
        return 1.14005089f;
      }
    }
  } else {
    if (x[0] < -3.70000005f) {
      if (x[1] < 86.1729279f) {
        return -6.97180796f;
      } else {
        return -15.9680243f;
      }
    } else {
      if (x[4] < 523.0f) {
        return -1.75740516f;
      } else {
        return -7.49663019f;
      }
    }
  }
}
static inline float indra_fc_3_8(const float *x) {
  if (x[4] < 261.0f) {
    if (x[3] < 127.0f) {
      if (x[1] < 49.8529892f) {
        return 0.610788703f;
      } else {
        return 0.0238032341f;
      }
    } else {
      if (x[0] < 19.7999992f) {
        return 0.155020416f;
      } else {
        return -2.08281398f;
      }
    }
  } else {
    if (x[0] < -1.29999995f) {
      if (x[1] < 98.1253967f) {
        return -6.24898672f;
      } else {
        return 0.751072347f;
      }
    } else {
      if (x[3] < 460.0f) {
        return -1.0592649f;
      } else {
        return -9.43187332f;
      }
    }
  }
}
static inline float indra_fc_3_9(const float *x) {
  if (x[3] < 222.0f) {
    if (x[5] < 4.19999981f) {
      if (x[0] < 14.6999998f) {
        return 0.646770358f;
      } else {
        return -0.121414363f;
      }
    } else {
      if (x[3] < 74.3000031f) {
        return -0.747772276f;
      } else {
        return -5.90210438f;
      }
    }
  } else {
    if (x[5] < 4.0f) {
      if (x[0] < 26.5f) {
        return -1.38223219f;
      } else {
        return -9.5704813f;
      }
    } else {
      return -21.8259525f;
    }
  }
}
static inline float indra_fc_3_10(const float *x) {
  if (x[4] < 412.0f) {
    if (x[0] < -0.800000012f) {
      if (x[3] < 93.0f) {
        return 0.0408032946f;
      } else {
        return -2.22952127f;
      }
    } else {
      if (x[2] < 1020.20001f) {
        return -0.00902177859f;
      } else {
        return 1.12350357f;
      }
    }
  } else {
    if (x[2] < 998.400024f) {
      if (x[3] < 335.0f) {
        return -5.18945122f;
      } else {
        return -33.6382866f;
      }
    } else {
      if (x[0] < -4.30000019f) {
        return -16.2304516f;
      } else {
        return -1.78603363f;
      }
    }
  }
}
static inline float indra_fc_3_11(const float *x) {
  if (x[4] < 412.0f) {
    if (x[5] < 1.89999998f) {
      if (x[1] < 26.072649f) {
        return 1.91880381f;
      } else {
        return 0.134041131f;
      }
    } else {
      if (x[3] < 129.0f) {
        return -0.158543229f;
      } else {
        return -2.55266428f;
      }
    }
  } else {
    if (x[1] < 95.6966324f) {
      if (x[0] < -2.70000005f) {
        return -10.8976412f;
      } else {
        return -3.39248013f;
      }
    } else {
      if (x[0] < -0.200000003f) {
        return 9.94382381f;
      } else {
        return -10.5249958f;
      }
    }
  }
}
static inline float indra_fc_3_12(const float *x) {
  if (x[4] < 209.0f) {
    if (x[3] < 237.0f) {
      if (x[5] < 2.0999999f) {
        return 0.306874394f;
      } else {
        return -0.261236906f;
      }
    } else {
      if (x[4] < 176.0f) {
        return -19.3562927f;
      } else {
        return -4.1174655f;
      }
    }
  } else {
    if (x[0] < -3.9000001f) {
      if (x[3] < 357.0f) {
        return -3.68190932f;
      } else {
        return -11.5451593f;
      }
    } else {
      if (x[5] < 1.79999995f) {
        return -0.177750304f;
      } else {
        return -2.24726558f;
      }
    }
  }
}
static inline float indra_fc_3_13(const float *x) {
  if (x[1] < 83.7575378f) {
    if (x[3] < 392.0f) {
      if (x[5] < 2.9000001f) {
        return 0.298894405f;
      } else {
        return -0.515745342f;
      }
    } else {
      if (x[2] < 1017.0f) {
        return -15.9737701f;
      } else {
        return 0.683423936f;
      }
    }
  } else {
    if (x[3] < 185.0f) {
      if (x[2] < 1003.0f) {
        return 0.32760784f;
      } else {
        return -0.68142277f;
      }
    } else {
      if (x[2] < 995.0f) {
        return -10.0024443f;
      } else {
        return -1.63663864f;
      }
    }
  }
}
static inline float indra_fc_3_14(const float *x) {
  if (x[3] < 68.5999985f) {
    if (x[1] < 65.9690933f) {
      if (x[3] < 15.8999996f) {
        return -0.0406692438f;
      } else {
        return 0.653800964f;
      }
    } else {
      if (x[2] < 1003.59998f) {
        return 0.197299108f;
      } else {
        return -0.425967664f;
      }
    }
  } else {
    if (x[5] < 4.9000001f) {
      if (x[5] < 1.70000005f) {
        return -0.0324555375f;
      } else {
        return -0.880831242f;
      }
    } else {
      if (x[3] < 125.0f) {
        return -4.1787982f;
      } else {
        return -12.2872105f;
      }
    }
  }
}
static inline float indra_fc_3_15(const float *x) {
  if (x[0] < -3.9000001f) {
    if (x[3] < 84.4000015f) {
      if (x[1] < 87.8213425f) {
        return -0.0666290596f;
      } else {
        return 11.000515f;
      }
    } else {
      if (x[1] < 62.1243744f) {
        return -4.74416924f;
      } else {
        return -1.50334406f;
      }
    }
  } else {
    if (x[0] < 17.7999992f) {
      if (x[1] < 83.7575378f) {
        return 0.533537984f;
      } else {
        return -0.650559783f;
      }
    } else {
      if (x[3] < 460.0f) {
        return -0.215624526f;
      } else {
        return -27.5480556f;
      }
    }
  }
}
static inline float indra_fc_head_3(const float *x) {
  float residual = 0.14403468f;
  residual += indra_fc_3_0(x);
  residual += indra_fc_3_1(x);
  residual += indra_fc_3_2(x);
  residual += indra_fc_3_3(x);
  residual += indra_fc_3_4(x);
  residual += indra_fc_3_5(x);
  residual += indra_fc_3_6(x);
  residual += indra_fc_3_7(x);
  residual += indra_fc_3_8(x);
  residual += indra_fc_3_9(x);
  residual += indra_fc_3_10(x);
  residual += indra_fc_3_11(x);
  residual += indra_fc_3_12(x);
  residual += indra_fc_3_13(x);
  residual += indra_fc_3_14(x);
  residual += indra_fc_3_15(x);
  float value = x[3] + 0.75f * residual;
  return fminf(5000.0f, fmaxf(0.0f, value));
}
static inline float indra_fc_4_0(const float *x) {
  if (x[4] < 174.0f) {
    if (x[4] < 105.0f) {
      if (x[0] < 29.1000004f) {
        return 3.08740687f;
      } else {
        return 6.28698826f;
      }
    } else {
      if (x[3] < 31.0f) {
        return -6.51241302f;
      } else {
        return -0.487048864f;
      }
    }
  } else {
    if (x[4] < 412.0f) {
      if (x[4] < 261.0f) {
        return -5.20707226f;
      } else {
        return -11.2271967f;
      }
    } else {
      if (x[5] < 3.0999999f) {
        return -25.1496029f;
      } else {
        return -65.8171082f;
      }
    }
  }
}
static inline float indra_fc_4_1(const float *x) {
  if (x[3] < 132.0f) {
    if (x[1] < 50.0849228f) {
      if (x[5] < 3.5999999f) {
        return 3.1476059f;
      } else {
        return -1.50344861f;
      }
    } else {
      if (x[3] < 70.0f) {
        return 0.720308125f;
      } else {
        return -0.716929734f;
      }
    }
  } else {
    if (x[3] < 319.0f) {
      if (x[0] < 16.5f) {
        return -2.38189673f;
      } else {
        return -5.62044764f;
      }
    } else {
      if (x[0] < -4.0f) {
        return -32.0352898f;
      } else {
        return -13.2706146f;
      }
    }
  }
}
static inline float indra_fc_4_2(const float *x) {
  if (x[4] < 188.0f) {
    if (x[4] < 92.0f) {
      if (x[1] < 44.0550766f) {
        return 3.68213654f;
      } else {
        return 1.58949244f;
      }
    } else {
      if (x[4] < 142.0f) {
        return 0.409044802f;
      } else {
        return -1.78053701f;
      }
    }
  } else {
    if (x[4] < 451.0f) {
      if (x[5] < 2.29999995f) {
        return -4.81606865f;
      } else {
        return -12.4736357f;
      }
    } else {
      if (x[1] < 30.8797913f) {
        return -55.236805f;
      } else {
        return -20.8906975f;
      }
    }
  }
}
static inline float indra_fc_4_3(const float *x) {
  if (x[4] < 207.0f) {
    if (x[4] < 116.0f) {
      if (x[1] < 34.0380554f) {
        return 3.10587311f;
      } else {
        return 1.21067846f;
      }
    } else {
      if (x[3] < 64.9000015f) {
        return -3.52744484f;
      } else {
        return -0.550930858f;
      }
    }
  } else {
    if (x[4] < 523.0f) {
      if (x[3] < 110.0f) {
        return -13.660903f;
      } else {
        return -4.60429001f;
      }
    } else {
      if (x[0] < 3.9000001f) {
        return -17.7433472f;
      } else {
        return -55.1156311f;
      }
    }
  }
}
static inline float indra_fc_4_4(const float *x) {
  if (x[3] < 268.0f) {
    if (x[3] < 74.3000031f) {
      if (x[5] < 4.4000001f) {
        return 1.18622148f;
      } else {
        return -2.56421447f;
      }
    } else {
      if (x[0] < 16.5f) {
        return 0.21358107f;
      } else {
        return -1.83940089f;
      }
    }
  } else {
    if (x[3] < 357.0f) {
      if (x[2] < 1014.0f) {
        return -2.48485327f;
      } else {
        return -5.9988184f;
      }
    } else {
      if (x[2] < 997.799988f) {
        return -40.1582756f;
      } else {
        return -8.76246262f;
      }
    }
  }
}
static inline float indra_fc_4_5(const float *x) {
  if (x[4] < 231.0f) {
    if (x[4] < 136.0f) {
      if (x[1] < 23.0437584f) {
        return 2.98917437f;
      } else {
        return 0.893855274f;
      }
    } else {
      if (x[3] < 84.4000015f) {
        return -3.97784591f;
      } else {
        return -0.676916182f;
      }
    }
  } else {
    if (x[5] < 3.5f) {
      if (x[4] < 366.0f) {
        return -3.58230591f;
      } else {
        return -10.0255508f;
      }
    } else {
      if (x[4] < 523.0f) {
        return -18.0306873f;
      } else {
        return -49.230011f;
      }
    }
  }
}
static inline float indra_fc_4_6(const float *x) {
  if (x[1] < 51.8721352f) {
    if (x[5] < 2.9000001f) {
      if (x[0] < 0.200000003f) {
        return -1.48143005f;
      } else {
        return 2.15833354f;
      }
    } else {
      if (x[0] < 20.7000008f) {
        return -2.13965821f;
      } else {
        return 1.00892437f;
      }
    }
  } else {
    if (x[3] < 306.0f) {
      if (x[5] < 2.20000005f) {
        return -0.336418957f;
      } else {
        return -3.15589547f;
      }
    } else {
      if (x[0] < -4.0f) {
        return -16.2370167f;
      } else {
        return -4.05024767f;
      }
    }
  }
}
static inline float indra_fc_4_7(const float *x) {
  if (x[4] < 168.0f) {
    if (x[4] < 72.0f) {
      if (x[0] < 28.2000008f) {
        return 1.19439924f;
      } else {
        return 3.72493291f;
      }
    } else {
      if (x[5] < 4.0f) {
        return 0.164390951f;
      } else {
        return -2.89169574f;
      }
    }
  } else {
    if (x[4] < 339.0f) {
      if (x[0] < 19.3999996f) {
        return -0.925107479f;
      } else {
        return -4.23159218f;
      }
    } else {
      if (x[5] < 2.20000005f) {
        return -5.62312317f;
      } else {
        return -24.0605679f;
      }
    }
  }
}
static inline float indra_fc_4_8(const float *x) {
  if (x[4] < 228.0f) {
    if (x[4] < 79.0f) {
      if (x[1] < 19.0454273f) {
        return 2.85538673f;
      } else {
        return 0.868056893f;
      }
    } else {
      if (x[3] < 31.0f) {
        return -4.1215601f;
      } else {
        return -0.0682786033f;
      }
    }
  } else {
    if (x[3] < 110.0f) {
      if (x[4] < 523.0f) {
        return -10.4266682f;
      } else {
        return -32.2056389f;
      }
    } else {
      if (x[0] < 24.7000008f) {
        return -2.04160953f;
      } else {
        return -9.58481884f;
      }
    }
  }
}
static inline float indra_fc_4_9(const float *x) {
  if (x[1] < 62.84758f) {
    if (x[0] < -0.600000024f) {
      if (x[3] < 209.0f) {
        return -1.7468226f;
      } else {
        return -7.17679739f;
      }
    } else {
      if (x[5] < 2.0f) {
        return 1.77474976f;
      } else {
        return -0.216209605f;
      }
    }
  } else {
    if (x[5] < 2.20000005f) {
      if (x[0] < 19.7999992f) {
        return -0.0735494345f;
      } else {
        return -1.17342842f;
      }
    } else {
      if (x[3] < 88.9000015f) {
        return -1.81641543f;
      } else {
        return -5.38876772f;
      }
    }
  }
}
static inline float indra_fc_4_10(const float *x) {
  if (x[4] < 295.0f) {
    if (x[4] < 145.0f) {
      if (x[3] < 15.8999996f) {
        return -0.153608575f;
      } else {
        return 0.879983246f;
      }
    } else {
      if (x[3] < 96.0f) {
        return -3.61115956f;
      } else {
        return -0.399292767f;
      }
    }
  } else {
    if (x[3] < 209.0f) {
      if (x[4] < 523.0f) {
        return -9.94071865f;
      } else {
        return -27.9568005f;
      }
    } else {
      if (x[0] < 25.7000008f) {
        return -2.37402177f;
      } else {
        return -24.730175f;
      }
    }
  }
}
static inline float indra_fc_4_11(const float *x) {
  if (x[4] < 242.0f) {
    if (x[1] < 34.0380554f) {
      if (x[0] < 1.60000002f) {
        return -1.32277083f;
      } else {
        return 1.75632942f;
      }
    } else {
      if (x[0] < 10.0f) {
        return 0.629479825f;
      } else {
        return -0.404754639f;
      }
    }
  } else {
    if (x[3] < 194.0f) {
      if (x[4] < 523.0f) {
        return -6.21286535f;
      } else {
        return -22.3633919f;
      }
    } else {
      if (x[0] < 26.1000004f) {
        return -0.932076454f;
      } else {
        return -12.2157269f;
      }
    }
  }
}
static inline float indra_fc_4_12(const float *x) {
  if (x[4] < 152.0f) {
    if (x[4] < 70.0f) {
      if (x[0] < 26.5f) {
        return 0.529518604f;
      } else {
        return 2.23377848f;
      }
    } else {
      if (x[3] < 15.8999996f) {
        return -5.92815924f;
      } else {
        return 0.15614903f;
      }
    }
  } else {
    if (x[5] < 2.9000001f) {
      if (x[0] < 25.2000008f) {
        return -0.360497117f;
      } else {
        return -3.6320591f;
      }
    } else {
      if (x[4] < 276.0f) {
        return -3.30844951f;
      } else {
        return -11.3078203f;
      }
    }
  }
}
static inline float indra_fc_4_13(const float *x) {
  if (x[4] < 318.0f) {
    if (x[1] < 12.9778881f) {
      if (x[2] < 1024.19995f) {
        return 3.69649553f;
      } else {
        return -0.731284261f;
      }
    } else {
      if (x[5] < 2.4000001f) {
        return 0.293753713f;
      } else {
        return -0.908906937f;
      }
    }
  } else {
    if (x[2] < 1003.59998f) {
      if (x[4] < 412.0f) {
        return -5.2639966f;
      } else {
        return -25.1730309f;
      }
    } else {
      if (x[1] < 13.0230036f) {
        return -25.1647663f;
      } else {
        return -2.06709409f;
      }
    }
  }
}
static inline float indra_fc_4_14(const float *x) {
  if (x[4] < 127.0f) {
    if (x[1] < 21.9949532f) {
      if (x[3] < 17.0f) {
        return 0.0501463525f;
      } else {
        return 3.38968325f;
      }
    } else {
      if (x[5] < 2.0f) {
        return 0.434158623f;
      } else {
        return -0.338283837f;
      }
    }
  } else {
    if (x[3] < 88.9000015f) {
      if (x[4] < 198.0f) {
        return -1.83214653f;
      } else {
        return -5.84201193f;
      }
    } else {
      if (x[4] < 451.0f) {
        return -0.187110111f;
      } else {
        return -5.21294117f;
      }
    }
  }
}
static inline float indra_fc_4_15(const float *x) {
  if (x[0] < -3.9000001f) {
    if (x[4] < 351.0f) {
      if (x[4] < 93.0f) {
        return -0.070593372f;
      } else {
        return -3.52367091f;
      }
    } else {
      if (x[1] < 85.989975f) {
        return -11.3598127f;
      } else {
        return -18.3375645f;
      }
    }
  } else {
    if (x[1] < 65.9690933f) {
      if (x[5] < 2.0999999f) {
        return 1.04518354f;
      } else {
        return -0.333938807f;
      }
    } else {
      if (x[5] < 1.60000002f) {
        return -0.266754568f;
      } else {
        return -1.72329044f;
      }
    }
  }
}
static inline float indra_fc_head_4(const float *x) {
  float residual = 0.058695953f;
  residual += indra_fc_4_0(x);
  residual += indra_fc_4_1(x);
  residual += indra_fc_4_2(x);
  residual += indra_fc_4_3(x);
  residual += indra_fc_4_4(x);
  residual += indra_fc_4_5(x);
  residual += indra_fc_4_6(x);
  residual += indra_fc_4_7(x);
  residual += indra_fc_4_8(x);
  residual += indra_fc_4_9(x);
  residual += indra_fc_4_10(x);
  residual += indra_fc_4_11(x);
  residual += indra_fc_4_12(x);
  residual += indra_fc_4_13(x);
  residual += indra_fc_4_14(x);
  residual += indra_fc_4_15(x);
  float value = x[4] + 0.75f * residual;
  return fminf(5000.0f, fmaxf(0.0f, value));
}
static inline float indra_fc_5_0(const float *x) {
  if (x[5] < 2.0999999f) {
    if (x[5] < 1.20000005f) {
      if (x[5] < 0.800000012f) {
        return 0.169363156f;
      } else {
        return 0.0981704071f;
      }
    } else {
      if (x[5] < 1.60000002f) {
        return 0.0378771201f;
      } else {
        return -0.0271062013f;
      }
    }
  } else {
    if (x[5] < 3.9000001f) {
      if (x[5] < 2.79999995f) {
        return -0.114350215f;
      } else {
        return -0.213708475f;
      }
    } else {
      if (x[5] < 5.5999999f) {
        return -0.336674064f;
      } else {
        return -0.564142168f;
      }
    }
  }
}
static inline float indra_fc_5_1(const float *x) {
  if (x[5] < 2.0f) {
    if (x[5] < 1.10000002f) {
      if (x[5] < 0.5f) {
        return 0.162439048f;
      } else {
        return 0.0968830958f;
      }
    } else {
      if (x[5] < 1.5f) {
        return 0.0435101576f;
      } else {
        return -0.0108245611f;
      }
    }
  } else {
    if (x[5] < 3.5f) {
      if (x[5] < 2.5999999f) {
        return -0.075707905f;
      } else {
        return -0.147399232f;
      }
    } else {
      if (x[5] < 5.30000019f) {
        return -0.244256139f;
      } else {
        return -0.429709673f;
      }
    }
  }
}
static inline float indra_fc_5_2(const float *x) {
  if (x[5] < 2.29999995f) {
    if (x[5] < 1.29999995f) {
      if (x[5] < 0.600000024f) {
        return 0.124513566f;
      } else {
        return 0.0652833506f;
      }
    } else {
      if (x[5] < 1.79999995f) {
        return 0.0103313746f;
      } else {
        return -0.0368423536f;
      }
    }
  } else {
    if (x[5] < 4.4000001f) {
      if (x[0] < 16.1000004f) {
        return -0.0831622407f;
      } else {
        return -0.16005753f;
      }
    } else {
      if (x[5] < 6.69999981f) {
        return -0.251088768f;
      } else {
        return -0.494625717f;
      }
    }
  }
}
static inline float indra_fc_5_3(const float *x) {
  if (x[5] < 2.20000005f) {
    if (x[5] < 1.0f) {
      if (x[5] < 0.400000006f) {
        return 0.110681869f;
      } else {
        return 0.0704515651f;
      }
    } else {
      if (x[5] < 1.5f) {
        return 0.0293777231f;
      } else {
        return -0.012986213f;
      }
    }
  } else {
    if (x[5] < 3.5999999f) {
      if (x[3] < 17.0f) {
        return -0.0317329913f;
      } else {
        return -0.0987274274f;
      }
    } else {
      if (x[0] < 4.0999999f) {
        return -0.0876361877f;
      } else {
        return -0.229816109f;
      }
    }
  }
}
static inline float indra_fc_5_4(const float *x) {
  if (x[5] < 1.89999998f) {
    if (x[5] < 1.0f) {
      if (x[0] < 15.3000002f) {
        return 0.07908988f;
      } else {
        return 0.0481630825f;
      }
    } else {
      if (x[5] < 1.39999998f) {
        return 0.0275898725f;
      } else {
        return 0.000588518975f;
      }
    }
  } else {
    if (x[5] < 3.29999995f) {
      if (x[0] < 12.1000004f) {
        return -0.0139018269f;
      } else {
        return -0.0644922405f;
      }
    } else {
      if (x[5] < 6.5999999f) {
        return -0.133094952f;
      } else {
        return -0.351405114f;
      }
    }
  }
}
static inline float indra_fc_5_5(const float *x) {
  if (x[5] < 2.4000001f) {
    if (x[5] < 1.29999995f) {
      if (x[5] < 0.600000024f) {
        return 0.068326503f;
      } else {
        return 0.0328704827f;
      }
    } else {
      if (x[3] < 17.0f) {
        return 0.0366759077f;
      } else {
        return -0.0122740967f;
      }
    }
  } else {
    if (x[5] < 4.9000001f) {
      if (x[0] < 2.5999999f) {
        return 5.85490561e-05f;
      } else {
        return -0.0823503211f;
      }
    } else {
      if (x[0] < 16.0f) {
        return -0.125962228f;
      } else {
        return -0.29956314f;
      }
    }
  }
}
static inline float indra_fc_5_6(const float *x) {
  if (x[5] < 2.5999999f) {
    if (x[5] < 1.10000002f) {
      if (x[0] < 12.0f) {
        return 0.0527473986f;
      } else {
        return 0.0280509349f;
      }
    } else {
      if (x[0] < 23.5f) {
        return 0.00945411157f;
      } else {
        return -0.0243779384f;
      }
    }
  } else {
    if (x[5] < 7.69999981f) {
      if (x[0] < 15.5f) {
        return -0.0392688178f;
      } else {
        return -0.106203549f;
      }
    } else {
      if (x[0] < 16.7999992f) {
        return -0.333524436f;
      } else {
        return -0.628219545f;
      }
    }
  }
}
static inline float indra_fc_5_7(const float *x) {
  if (x[5] < 1.89999998f) {
    if (x[5] < 0.899999976f) {
      if (x[0] < 13.6999998f) {
        return 0.0498451404f;
      } else {
        return 0.0263737887f;
      }
    } else {
      if (x[0] < 20.0f) {
        return 0.0180531628f;
      } else {
        return -0.00339076295f;
      }
    }
  } else {
    if (x[5] < 4.0f) {
      if (x[4] < 40.2999992f) {
        return -0.0014533241f;
      } else {
        return -0.0449274294f;
      }
    } else {
      if (x[0] < 10.5f) {
        return -0.0470023304f;
      } else {
        return -0.14942196f;
      }
    }
  }
}
static inline float indra_fc_5_8(const float *x) {
  if (x[5] < 2.9000001f) {
    if (x[5] < 1.70000005f) {
      if (x[5] < 0.400000006f) {
        return 0.0468094647f;
      } else {
        return 0.0145581337f;
      }
    } else {
      if (x[3] < 18.2999992f) {
        return 0.0159013998f;
      } else {
        return -0.0227859076f;
      }
    }
  } else {
    if (x[0] < -1.0f) {
      if (x[3] < 8.0f) {
        return 0.110564426f;
      } else {
        return -0.000110188033f;
      }
    } else {
      if (x[5] < 5.9000001f) {
        return -0.0593652241f;
      } else {
        return -0.174178898f;
      }
    }
  }
}
static inline float indra_fc_5_9(const float *x) {
  if (x[5] < 2.9000001f) {
    if (x[5] < 1.39999998f) {
      if (x[3] < 195.0f) {
        return 0.0224101469f;
      } else {
        return -0.0101713287f;
      }
    } else {
      if (x[0] < 23.2000008f) {
        return 0.00298094144f;
      } else {
        return -0.0242691673f;
      }
    }
  } else {
    if (x[5] < 7.80000019f) {
      if (x[0] < 15.6000004f) {
        return -0.0189976282f;
      } else {
        return -0.0747641996f;
      }
    } else {
      if (x[0] < 0.600000024f) {
        return -0.12441887f;
      } else {
        return -0.383315921f;
      }
    }
  }
}
static inline float indra_fc_5_10(const float *x) {
  if (x[5] < 3.0999999f) {
    if (x[5] < 0.800000012f) {
      if (x[0] < 10.1000004f) {
        return 0.0385843478f;
      } else {
        return 0.0154127628f;
      }
    } else {
      if (x[3] < 14.0f) {
        return 0.0290039871f;
      } else {
        return -0.00380918733f;
      }
    }
  } else {
    if (x[0] < 1.39999998f) {
      if (x[2] < 1019.09998f) {
        return 0.119688928f;
      } else {
        return 0.00607978133f;
      }
    } else {
      if (x[5] < 4.80000019f) {
        return -0.0393688045f;
      } else {
        return -0.107464187f;
      }
    }
  }
}
static inline float indra_fc_5_11(const float *x) {
  if (x[5] < 1.70000005f) {
    if (x[3] < 244.0f) {
      if (x[0] < 19.3999996f) {
        return 0.0209152605f;
      } else {
        return 0.00163148751f;
      }
    } else {
      if (x[0] < -3.9000001f) {
        return 0.0367372409f;
      } else {
        return -0.0249529388f;
      }
    }
  } else {
    if (x[0] < -1.70000005f) {
      if (x[3] < 10.0f) {
        return 0.10252782f;
      } else {
        return 0.00637050858f;
      }
    } else {
      if (x[5] < 5.4000001f) {
        return -0.0177502595f;
      } else {
        return -0.094907105f;
      }
    }
  }
}
static inline float indra_fc_5_12(const float *x) {
  if (x[5] < 2.29999995f) {
    if (x[3] < 17.0f) {
      if (x[0] < 15.6000004f) {
        return 0.0676601082f;
      } else {
        return -0.0190314278f;
      }
    } else {
      if (x[2] < 1016.29999f) {
        return 0.0104782041f;
      } else {
        return -0.0150876017f;
      }
    }
  } else {
    if (x[3] < 9.0f) {
      if (x[0] < 17.2000008f) {
        return 0.0387140848f;
      } else {
        return -0.0382614732f;
      }
    } else {
      if (x[5] < 7.69999981f) {
        return -0.0267753545f;
      } else {
        return -0.229565933f;
      }
    }
  }
}
static inline float indra_fc_5_13(const float *x) {
  if (x[5] < 3.20000005f) {
    if (x[5] < 0.899999976f) {
      if (x[3] < 137.0f) {
        return 0.0200021025f;
      } else {
        return 0.000773687498f;
      }
    } else {
      if (x[1] < 15.9581518f) {
        return 0.0448358916f;
      } else {
        return -0.00310932333f;
      }
    }
  } else {
    if (x[1] < 40.890358f) {
      if (x[5] < 7.80000019f) {
        return -0.0117237428f;
      } else {
        return -0.20199196f;
      }
    } else {
      if (x[4] < 26.6000004f) {
        return -0.00164591742f;
      } else {
        return -0.113214053f;
      }
    }
  }
}
static inline float indra_fc_5_14(const float *x) {
  if (x[5] < 1.79999995f) {
    if (x[3] < 15.8999996f) {
      if (x[2] < 1009.20001f) {
        return -0.00958119798f;
      } else {
        return 0.0511495657f;
      }
    } else {
      if (x[2] < 1020.5f) {
        return 0.00859884731f;
      } else {
        return -0.0162128191f;
      }
    }
  } else {
    if (x[5] < 6.4000001f) {
      if (x[3] < 11.1999998f) {
        return 0.0128837889f;
      } else {
        return -0.0158733986f;
      }
    } else {
      if (x[2] < 1002.79999f) {
        return -0.238752171f;
      } else {
        return -0.0657006949f;
      }
    }
  }
}
static inline float indra_fc_5_15(const float *x) {
  if (x[0] < 24.5f) {
    if (x[0] < -1.70000005f) {
      if (x[3] < 32.2000008f) {
        return 0.0599745288f;
      } else {
        return 0.0104037179f;
      }
    } else {
      if (x[5] < 4.5f) {
        return 0.00363323907f;
      } else {
        return -0.0390786044f;
      }
    }
  } else {
    if (x[3] < 100.0f) {
      if (x[5] < 3.29999995f) {
        return -0.0213599335f;
      } else {
        return -0.0666119903f;
      }
    } else {
      if (x[1] < 55.8844719f) {
        return 0.0384314135f;
      } else {
        return -0.00460550282f;
      }
    }
  }
}
static inline float indra_fc_head_5(const float *x) {
  float residual = 0.0011150935f;
  residual += indra_fc_5_0(x);
  residual += indra_fc_5_1(x);
  residual += indra_fc_5_2(x);
  residual += indra_fc_5_3(x);
  residual += indra_fc_5_4(x);
  residual += indra_fc_5_5(x);
  residual += indra_fc_5_6(x);
  residual += indra_fc_5_7(x);
  residual += indra_fc_5_8(x);
  residual += indra_fc_5_9(x);
  residual += indra_fc_5_10(x);
  residual += indra_fc_5_11(x);
  residual += indra_fc_5_12(x);
  residual += indra_fc_5_13(x);
  residual += indra_fc_5_14(x);
  residual += indra_fc_5_15(x);
  float value = x[5] + 1.0f * residual;
  return fminf(100.0f, fmaxf(0.0f, value));
}
/* Returns 1 on success, 0 for null pointers, missing or out-of-range inputs.
 * Pass distinct arrays. Outputs are NAN on invalid sensor data. No heap allocation. */
static inline int indra_forecast_predict(const float *input, float *output) {
  if (!input || !output) return 0;
  float x[6];
  for (int i = 0; i < 6; ++i) x[i] = input[i];
  for (int i = 0; i < 6; ++i) output[i] = NAN;
  if (!isfinite(x[0]) || x[0] < -60.0f || x[0] > 85.0f) return 0;
  if (!isfinite(x[1]) || x[1] < 0.0f || x[1] > 100.0f) return 0;
  if (!isfinite(x[2]) || x[2] < 300.0f || x[2] > 1100.0f) return 0;
  if (!isfinite(x[3]) || x[3] < 0.0f || x[3] > 5000.0f) return 0;
  if (!isfinite(x[4]) || x[4] < 0.0f || x[4] > 5000.0f) return 0;
  if (!isfinite(x[5]) || x[5] < 0.0f || x[5] > 100.0f) return 0;
  output[0] = indra_fc_head_0(x);
  output[1] = indra_fc_head_1(x);
  output[2] = indra_fc_head_2(x);
  output[3] = indra_fc_head_3(x);
  output[4] = indra_fc_head_4(x);
  output[5] = indra_fc_head_5(x);
  return 1;
}
#endif
