"""Generate deterministic on-board self-test references from the saved Python models."""
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import xgboost as xgb

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))
from ml.event_classifier.features import ALL_EVENT_FEATURE_COLS, build_features
from ml.six_sensor_forecast.contract import RAW_SENSOR_COLUMNS
from ml.six_sensor_forecast.predict import predict


def main():
    raw = np.array([[20 + i * .5, 50 + i, 1013 - i * .25,
                     35 + i * 2, 60 + i, 2 + i * .125] for i in range(7)], dtype=np.float32)
    frame = pd.DataFrame(raw, columns=RAW_SENSOR_COLUMNS)
    frame['timestamp_utc'] = pd.date_range('2026-01-01', periods=7, freq='h', tz='UTC')
    frame['location_id'] = 'synthetic_board_self_test'
    _, features = build_features(frame)
    row = features[ALL_EVENT_FEATURE_COLS].iloc[[-1]].astype(np.float32)
    model_dir = ROOT / 'ml/models/uci_beijing_event_rules_6sensor'
    report = json.loads((model_dir / 'event_training_report.json').read_text())
    events = []
    for name in report['event_names']:
        entry = report['models'][name]
        if entry.get('skipped'):
            events.append(float('nan'))
        else:
            booster = xgb.Booster()
            booster.load_model(model_dir / entry['student_file'])
            events.append(float(booster.predict(xgb.DMatrix(row))[0]))
    forecast = predict(frame, ROOT / 'ml/models/uci_beijing_6h', 'student').iloc[-1]
    def values(xs):
        return ', '.join('NAN' if not np.isfinite(x) else f'{float(x):.9e}f' for x in xs)
    text = '// Synthetic software self-test; generated by tools/generate_fixture.py.\n#pragma once\n'
    text += 'static const float kTestRows[7][6] = {\n'
    text += ''.join('  {' + values(r) + '},\n' for r in raw) + '};\n'
    text += 'static const float kExpectedForecast[6] = {' + values([forecast['forecast_' + k] for k in RAW_SENSOR_COLUMNS]) + '};\n'
    text += 'static const float kExpectedEvents[12] = {' + values(events) + '};\n'
    (ROOT / 'esp32/ml_integration/include/self_test_fixture.h').write_text(text)
    payload = {
        'provenance': 'SYNTHETIC_SOFTWARE_TEST_NOT_FIELD_DATA',
        'timestamps': [1767225600 + i * 3600 for i in range(7)],
        'readings': raw.tolist(),
        'forecast_last': [float(forecast['forecast_' + k]) for k in RAW_SENSOR_COLUMNS],
        'events_last': [float(v) if np.isfinite(v) else None for v in events],
        'event_valid_mask': sum(1 << i for i, name in enumerate(report['event_names'])
                                if not report['models'][name].get('skipped')),
    }
    (ROOT / 'esp32/ml_integration/self_test_fixture.json').write_text(
        json.dumps(payload, indent=2, allow_nan=False) + '\n')
    print('Generated Python-model board references')

if __name__ == '__main__':
    main()
