"""Export compact regression students as standalone ESP32-compatible C99."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd
import xgboost as xgb

from ml.six_sensor_forecast.c_codegen import _c_float, _parse_tree, _tree_depth
from ml.six_sensor_forecast.contract import PHYSICAL_RANGES, RAW_SENSOR_COLUMNS
from ml.six_sensor_forecast.data import SCHEMA, sha256


def export(
    model_dir: Path, observations: Path, output: Path, tolerance: float = 2e-4
) -> dict:
    if not np.isfinite(tolerance) or not 0 < tolerance <= 2e-4:
        raise ValueError("Parity tolerance must be in (0, 2e-4]")
    compiler = shutil.which("cc")
    if compiler is None:
        raise RuntimeError("A C compiler is required to verify exported predictions")
    report = json.loads((model_dir / "training_report.json").read_text())
    if report["schema_version"] != SCHEMA or set(report["models"]) != set(
        RAW_SENSOR_COLUMNS
    ):
        raise ValueError("Incomplete or incompatible forecast model")
    if report["architecture"]["student_features"] != RAW_SENSOR_COLUMNS:
        raise ValueError(
            "Student must use exactly the six funded inputs in canonical order"
        )
    source = pd.read_csv(observations)
    sample = source[RAW_SENSOR_COLUMNS].dropna()
    sample = sample[np.isfinite(sample).all(axis=1)]
    if sample.empty:
        raise ValueError("No complete observations for parity")
    sample = sample.sample(n=min(2048, len(sample)), random_state=42).to_numpy(
        dtype=np.float32
    )
    boundary_rows = []
    models = []
    lines = [
        "/* Generated by python -m ml.six_sensor_forecast.export. Research forecast, not a hazard alarm. */",
        "#ifndef INDRA_SIX_SENSOR_FORECAST_H",
        "#define INDRA_SIX_SENSOR_FORECAST_H",
        "#include <math.h>",
        "#include <stddef.h>",
        "#define INDRA_FORECAST_INPUTS 6",
        "#define INDRA_FORECAST_OUTPUTS 6",
        f"#define INDRA_FORECAST_HORIZON_HOURS {int(report['horizon_hours'])}",
        '#define INDRA_FORECAST_STATUS "OFFLINE_RESEARCH_ONLY"',
        "/* Input/output order: " + ", ".join(RAW_SENSOR_COLUMNS) + " */",
    ]
    total_nodes = 0
    for target_index, target in enumerate(RAW_SENSOR_COLUMNS):
        entry = report["models"][target]
        path = model_dir / entry["student_file"]
        if sha256(path) != entry["student_sha256"]:
            raise ValueError(f"Student checksum mismatch: {target}")
        model = xgb.Booster()
        model.load_model(path)
        if model.feature_names != RAW_SENSOR_COLUMNS:
            raise ValueError("Student model feature order mismatch")
        config = json.loads(model.save_config())["learner"]
        if config["objective"]["name"] != "reg:squarederror":
            raise ValueError("Exporter supports square-error regression only")
        base = float(str(config["learner_model_param"]["base_score"]).strip("[]"))
        trees = [json.loads(t) for t in model.get_dump(dump_format="json")]
        if len(trees) > 16 or any(_tree_depth(tree) > 3 for tree in trees):
            raise ValueError("Student exceeds 16-tree / depth-3 budget")
        models.append(model)
        for tree_index, tree in enumerate(trees):
            nodes = _parse_tree(tree, RAW_SENSOR_COLUMNS)
            total_nodes += len(nodes)
            lines.append(
                f"static inline float indra_fc_{target_index}_{tree_index}(const float *x) {{"
            )

            def emit(index: int, indent: str, tree_nodes: list[dict]) -> None:
                node = tree_nodes[index]
                if node["feature_index"] == -1:
                    lines.append(f"{indent}return {_c_float(node['leaf_value'])};")
                    return
                feature = node["feature_index"]
                threshold = np.float32(node["threshold"])
                for value in (
                    np.nextafter(threshold, np.float32(-np.inf)),
                    threshold,
                    np.nextafter(threshold, np.float32(np.inf)),
                ):
                    row = sample[len(boundary_rows) % len(sample)].copy()
                    row[feature] = value
                    boundary_rows.append(row)
                lines.append(f"{indent}if (x[{feature}] < {_c_float(threshold)}) {{")
                emit(node["left_child"], indent + "  ", tree_nodes)
                lines.append(f"{indent}}} else {{")
                emit(node["right_child"], indent + "  ", tree_nodes)
                lines.append(f"{indent}}}")

            emit(0, "  ", nodes)
            lines.append("}")
        lines.append(
            f"static inline float indra_fc_head_{target_index}(const float *x) {{"
        )
        lines.append(f"  float residual = {_c_float(base)};")
        for tree_index in range(len(trees)):
            lines.append(f"  residual += indra_fc_{target_index}_{tree_index}(x);")
        lower, upper = PHYSICAL_RANGES[target]
        lines.append(
            f"  float value = x[{target_index}] + {_c_float(entry['student_weight'])} * residual;"
        )
        lines.append(
            f"  return fminf({_c_float(upper)}, fmaxf({_c_float(lower)}, value));"
        )
        lines.append("}")
    lines.extend(
        [
            "/* Returns 1 on success, 0 for null pointers, missing or out-of-range inputs.",
            " * Pass distinct arrays. Outputs are NAN on invalid sensor data. No heap allocation. */",
            "static inline int indra_forecast_predict(const float *input, float *output) {",
            "  if (!input || !output) return 0;",
            "  float x[6];",
            "  for (int i = 0; i < 6; ++i) x[i] = input[i];",
            "  for (int i = 0; i < 6; ++i) output[i] = NAN;",
        ]
    )
    for index, target in enumerate(RAW_SENSOR_COLUMNS):
        lower, upper = PHYSICAL_RANGES[target]
        lines.append(
            f"  if (!isfinite(x[{index}]) || x[{index}] < {_c_float(lower)} || x[{index}] > {_c_float(upper)}) return 0;"
        )
    for index in range(6):
        lines.append(f"  output[{index}] = indra_fc_head_{index}(x);")
    lines.extend(["  return 1;", "}", "#endif", ""])
    samples = np.vstack([sample, boundary_rows]).astype(np.float32)
    # Physical boundary cases are tested as accepted inputs too.
    samples = np.vstack(
        [
            samples,
            [PHYSICAL_RANGES[t][0] for t in RAW_SENSOR_COLUMNS],
            [PHYSICAL_RANGES[t][1] for t in RAW_SENSOR_COLUMNS],
        ]
    ).astype(np.float32)
    dmatrix = xgb.DMatrix(samples, feature_names=RAW_SENSOR_COLUMNS)
    expected = np.column_stack(
        [
            np.clip(
                samples[:, i]
                + report["models"][t]["student_weight"] * model.predict(dmatrix),
                *PHYSICAL_RANGES[t],
            )
            for i, (t, model) in enumerate(zip(RAW_SENSOR_COLUMNS, models))
        ]
    )
    invalid_samples = np.tile(sample[0], (18, 1))
    for i, target in enumerate(RAW_SENSOR_COLUMNS):
        invalid_samples[i, i] = np.nan
        invalid_samples[6 + i, i] = np.inf
        invalid_samples[12 + i, i] = PHYSICAL_RANGES[target][1] + 1
    all_samples = np.vstack([samples, invalid_samples])
    runner = """#include <stdio.h>
#include "indra_six_sensor_forecast.h"
int main(void) {
  float x[6], y[6];
  while (scanf("%f %f %f %f %f %f", x, x+1, x+2, x+3, x+4, x+5) == 6) {
    int ok = indra_forecast_predict(x, y);
    printf("%d", ok);
    for (int i=0; i<6; ++i) printf(" %.9g", y[i]);
    puts("");
  }
  return 0;
}
"""
    with tempfile.TemporaryDirectory() as directory:
        temporary = Path(directory)
        header = temporary / "indra_six_sensor_forecast.h"
        header.write_text("\n".join(lines))
        (temporary / "runner.c").write_text(runner)
        binary = temporary / "runner"
        subprocess.run(
            [
                compiler,
                "-std=c99",
                "-O2",
                "-Wall",
                "-Wextra",
                "-Werror",
                str(temporary / "runner.c"),
                "-lm",
                "-o",
                str(binary),
            ],
            check=True,
            capture_output=True,
        )
        stdin = (
            "\n".join(" ".join(f"{float(v):.9g}" for v in row) for row in all_samples)
            + "\n"
        )
        process = subprocess.run(
            [str(binary)], input=stdin, text=True, capture_output=True, check=True
        )
        actual = np.array(
            [[float(v) for v in line.split()] for line in process.stdout.splitlines()]
        )
        if (
            actual.shape != (len(all_samples), 7)
            or not (actual[: len(samples), 0] == 1).all()
        ):
            raise RuntimeError(
                "C runner rejected valid input or returned incomplete predictions"
            )
        if (
            not (actual[len(samples) :, 0] == 0).all()
            or not np.isnan(actual[len(samples) :, 1:]).all()
        ):
            raise RuntimeError("C runner failed invalid-input rejection")
        error = np.max(np.abs(expected - actual[: len(samples), 1:]), axis=0)
        if not np.isfinite(error).all() or error.max() > tolerance:
            raise RuntimeError(f"Python/C parity failed: {error.tolist()}")
        output.mkdir(parents=True, exist_ok=True)
        # Publish only after compiling and executing parity checks.
        shutil.copyfile(header, output / header.name)
    metadata = {
        "schema_version": SCHEMA,
        "status": "OFFLINE_RESEARCH_ONLY",
        "input_features": RAW_SENSOR_COLUMNS,
        "horizon_hours": report["horizon_hours"],
        "heads": 6,
        "trees_per_head": 16,
        "max_depth": 3,
        "total_nodes": total_nodes,
        "header_bytes": (output / header.name).stat().st_size,
        "header_sha256": sha256(output / header.name),
        "model_report_sha256": sha256(model_dir / "training_report.json"),
        "parity": {
            "valid_rows": len(samples),
            "invalid_rows": len(invalid_samples),
            "absolute_tolerance": tolerance,
            "max_absolute_error_by_target": dict(
                zip(RAW_SENSOR_COLUMNS, error.tolist())
            ),
            "passed": True,
        },
    }
    (output / "c_export_report.json").write_text(json.dumps(metadata, indent=2) + "\n")
    return metadata


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", type=Path, default=Path("ml/models/uci_beijing_6h"))
    parser.add_argument(
        "--observations",
        type=Path,
        default=Path("data/uci_beijing_air_quality/observations.csv"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("ml/models/uci_beijing_6h/esp32_student/export"),
    )
    args = parser.parse_args()
    print(json.dumps(export(args.model, args.observations, args.output), indent=2))


if __name__ == "__main__":
    main()
