/**
 * ml.h - Machine Learning Inference Engine
 *
 * Embedded XGBoost inference for the ESP32-S3.
 * Loads a pre-trained boosted-tree model (generated by code/ml/convert_to_c.py)
 * and runs iterative (non-recursive) inference on normalized feature vectors.
 *
 * Model loading:     ml_init()
 * Normalize inputs:  ml_normalize()
 * Run inference:     ml_predict()
 * Get confidence:    ml_confidence()
 *
 * All functions return esp_err_t and use static buffers — no malloc.
 */

#ifndef ML_H
#define ML_H

#include <stdint.h>
#include <stdbool.h>
#include "esp_err.h"
#include "common.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Maximum number of hazard classes the model can detect */
#define ML_MAX_CLASSES      4

/* Maximum tree depth supported by the inference engine */
#define ML_MAX_DEPTH        8

/* Input feature count — must match the trained model */
#define ML_FEATURE_COUNT    14

/**
 * @brief Initialize the ML inference engine.
 * Loads model parameters (tree nodes, thresholds, leaf values)
 * from compiled-in constants.
 * @return ESP_OK on success, ESP_ERR_INVALID_STATE if model data is corrupt.
 */
esp_err_t ml_init(void);

/**
 * @brief Normalize a raw feature vector using pre-computed z-score
 *        (mean, stddev) parameters from the training dataset.
 * @param raw   Raw sensor features (must have ML_FEATURE_COUNT elements).
 * @param norm  Output — normalized features, ready for ml_predict().
 * @return ESP_OK on success, ESP_ERR_INVALID_ARG if either pointer is NULL.
 */
esp_err_t ml_normalize(const float *raw, float *norm);

/**
 * @brief Run XGBoost model inference on a normalized feature vector.
 *        Uses iterative (stack-based) traversal — no recursion.
 * @param features  Normalized feature vector (ML_FEATURE_COUNT elements).
 * @param class_id  Hazard class index to evaluate (0..ML_MAX_CLASSES-1).
 * @param output    Raw model output (log-odds before sigmoid).
 * @return ESP_OK on success.
 */
esp_err_t ml_predict(const float *features, uint8_t class_id, float *output);

/**
 * @brief Convert raw model output to a confidence probability [0.0, 1.0].
 * @param raw_output  Log-odds value from ml_predict().
 * @return Sigmoid-transformed probability.
 */
float ml_confidence(float raw_output);

/**
 * @brief Get total RAM used by model data (flash-mapped or SRAM).
 * @return Size in bytes.
 */
size_t ml_model_ram_usage(void);

/**
 * @brief Get total flash used by model data.
 * @return Size in bytes.
 */
size_t ml_model_flash_usage(void);

/**
 * @brief Get the last inference time in microseconds.
 * @return Last inference duration in µs.
 */
uint32_t ml_last_inference_us(void);

#ifdef __cplusplus
}
#endif

#endif /* ML_H */
