"""Self-contained offline SVG viewer; no external tiles, APIs, scripts or alerts."""
import json
from pathlib import Path

TEMPLATE=r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>INDRA | Weather between nodes</title>
<style>
:root{font-family:system-ui,sans-serif;color:#dbe7ef;background:#0b1420;color-scheme:dark}*{box-sizing:border-box}body{margin:0}header{padding:22px 28px;border-bottom:1px solid #26384a}h1{margin:0;font-size:27px}p{line-height:1.5}header p{margin:7px 0 0;color:#a7bdcd}.badge{background:#183747;color:#8fe0dc;padding:4px 9px;border-radius:5px;font-size:12px}.notice{background:#352c14;border:1px solid #786537;color:#f5dda1;padding:12px 18px;margin:18px 28px;border-radius:8px}main{padding:0 28px 26px;display:grid;grid-template-columns:minmax(500px,1fr) 340px;gap:20px}.panel{border:1px solid #26384a;background:#101e2e;border-radius:10px;padding:18px}label{font-size:13px;color:#a9c0d0}select{padding:8px;border:1px solid #405a70;border-radius:6px;background:#142638;margin:5px 18px 8px 0}.controls{display:flex;flex-wrap:wrap;align-items:center;gap:8px}svg{width:100%;height:auto;max-height:570px;background:#091827;border-radius:8px;margin-top:10px;border:1px solid #30485b}.legend{display:flex;gap:15px;flex-wrap:wrap;margin:15px 0 0;font-size:12px}.swatch{display:inline-block;width:12px;height:12px;margin-right:5px;vertical-align:middle}h2{font-size:16px;margin:0 0 12px}.metric{font-size:24px;font-weight:600}.meta{font-size:12px;color:#a9bdcd}.node{padding:12px 0;border-top:1px solid #26384a}.node:first-of-type{border-top:0}.status{font-size:11px;border-radius:4px;padding:3px 6px;background:#344759}#detail{white-space:pre-line;font-size:13px;line-height:1.55}footer{padding:8px 28px 24px;color:#91aabd;font-size:12px}.toggle{display:flex;align-items:center;gap:5px}#scale{height:8px;background:linear-gradient(90deg,#3569ac,#3bafba,#e9c85e,#df6945);border-radius:4px}.scale-labels{display:flex;justify-content:space-between;font-size:12px;margin-top:6px}@media(max-width:900px){main{grid-template-columns:1fr;padding:0 12px}header{padding:16px}.notice{margin:12px}aside{display:grid;gap:12px}}</style></head>
<body><header><h1>INDRA <span class="badge">READ-ONLY RESEARCH DEMO</span></h1><p>Weather estimates between sensor nodes · GPS coordinates · elevation-aware physics and guarded model corrections</p></header>
<div id="notice" class="notice"></div><main><section class="panel"><div class="controls"><label>Channel<br><select id="channel" aria-label="Channel"></select></label><label>Layer<br><select id="layer" aria-label="Map layer"><option value="estimate">Weather estimate</option><option value="terrain">Elevation</option><option value="status">Prediction status</option><option value="uncertainty">Checked interval width</option></select></label><label class="toggle"><input id="support" type="checkbox" checked>Supported area</label><label class="toggle"><input id="sensors" type="checkbox" checked>Sensor locations</label></div><svg id="map" viewBox="0 0 900 500" role="img" aria-label="GPS weather map"><defs><pattern id="unsupported" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M0 8L8 0" stroke="#233a4e" stroke-width="1"/></pattern></defs><g id="grid"></g><g id="positions"></g><g id="axes"></g></svg><p id="mapnote" class="meta"></p><div id="scale"></div><div class="scale-labels"><span id="scale-low"></span><span id="scale-high"></span></div><div class="legend"><span><i class="swatch" style="background:#edf8ff;border-radius:50%"></i>Observed node</span><span><i class="swatch" style="background:#3bafba"></i>Model / physics estimate</span><span><i class="swatch" style="background:#79643d"></i>Stale / unauthenticated</span><span><i class="swatch" style="background:#243b50"></i>Unsupported / missing</span><span><i class="swatch" style="border:1px solid #70dbc5"></i>Checked interval, when available</span></div></section><aside><section class="panel"><h2>Snapshot and provenance</h2><div id="clock" class="meta"></div><p id="coverage" class="metric"></p><div id="model" class="meta"></div><p id="bandnote" class="meta"></p></section><section class="panel"><h2>Sensor observations</h2><div id="nodes"></div></section><section class="panel"><h2>Inspect a grid cell</h2><div id="detail">Select a cell to inspect its coordinates, estimate, status and sources.</div></section></aside></main><footer>Static snapshot; ages use the displayed reference clock, not a live connection. No disaster detection or field-validated accuracy. Grid colors estimate conditions; they do not create measurements at unobserved locations. No external map services or data transmission.</footer>
<script type="application/json" id="data">__DATA__</script><script>
'use strict'; const data=JSON.parse(document.getElementById('data').textContent);window.indraMapData=data;
const channels={temperature_c:['Temperature','°C'],relative_humidity_pct:['Relative humidity','%'],pressure_hpa:['Station pressure','hPa'],pm25_ug_m3:['PM2.5','µg/m³'],pm10_ug_m3:['PM10','µg/m³'],wind_speed_mps:['Wind speed','m/s']};
const $=id=>document.getElementById(id);for(const [key,[name,unit]] of Object.entries(channels)){const o=document.createElement('option');o.value=key;o.textContent=name+' ('+unit+')';$('channel').appendChild(o)}
$('notice').textContent=(data.mode==='fixture'?'SYNTHETIC WEATHER READINGS — cached terrain may be real; this is a software demonstration.':'Recorded/verified readings — authentication and quality are shown per observation.')+' Disaster outputs: DISABLED. '+(data.model_status==='model_unavailable_physics_fallback'?'Learned model unavailable; physics fallback.':'');
const b=data.bounds, cos=Math.cos((b.north+b.south)*Math.PI/360),ratio=(b.east-b.west)*cos/(b.north-b.south);let w=820,h=Math.min(420,w/ratio);if(w/h>4)h=220;
const x=lon=>40+(lon-b.west)/(b.east-b.west)*w,y=lat=>35+(b.north-lat)/(b.north-b.south)*h;
$('map').setAttribute('viewBox',`0 0 900 ${h+95}`);
function svg(tag,attrs,parent){let e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(let [k,v] of Object.entries(attrs))e.setAttribute(k,v);parent.appendChild(e);return e}
function number(v){return v===null||v===undefined?'unavailable':Number(v).toFixed(2)}
function color(v,lo,hi){const t=Math.max(0,Math.min(1,(v-lo)/(hi-lo||1)));const stops=[[53,105,172],[59,175,186],[233,200,94],[223,105,69]],index=Math.min(2,Math.floor(t*3)),q=t*3-index;return 'rgb('+stops[index].map((a,k)=>Math.round(a+(stops[index+1][k]-a)*q)).join(',')+')'}
function show(cell){const c=$('channel').value,r=cell.channels[c];$('detail').textContent=`${cell.latitude.toFixed(5)}°N, ${cell.longitude.toFixed(5)}°E\nQuery elevation: ${number(cell.elevation_m)} m EGM96\n${channels[c][0]}: ${number(r.estimate)} ${r.unit}\nStatus: ${r.status_flag}\nContributors: ${r.contributing_nodes}\nInterval: ${r.uncertainty_available?number(r.lower)+' to '+number(r.upper)+' '+r.unit:'unavailable — no checked band'}\nTerrain source: ${cell.terrain.source}\nModel: ${r.model_version}`}
function render(){const c=$('channel').value,layer=$('layer').value,values=data.cells.map(q=>layer==='terrain'?q.elevation_m:layer==='uncertainty'?(q.channels[c].uncertainty_available?q.channels[c].upper-q.channels[c].lower:null):q.channels[c].estimate).filter(v=>v!==null);const lo=values.length?Math.min(...values):0,hi=values.length?Math.max(...values):1;let available=0,bands=0;
$('grid').replaceChildren();$('positions').replaceChildren();$('axes').replaceChildren();let cw=w/(data.grid_shape[1]-1),ch=h/(data.grid_shape[0]-1);
for(const q of data.cells){const r=q.channels[c],valid=r.estimate!==null;if(valid)available++;if(r.uncertainty_available)bands++;let v=layer==='terrain'?q.elevation_m:layer==='uncertainty'?(r.uncertainty_available?r.upper-r.lower:null):r.estimate;let fill=v===null?'url(#unsupported)':color(v,lo,hi);if(layer==='status'){fill=valid?(r.residual_fallback?'#ab8244':'#42a793'):'#20394d'}const cell=svg('rect',{x:x(q.longitude)-cw/2,y:y(q.latitude)-ch/2,width:cw+1,height:ch+1,fill,stroke:$('support').checked&&valid?'#59d6b1':'none','stroke-width':.4,'data-grid-id':q.grid_id},$('grid'));cell.addEventListener('click',()=>show(q))}
if($('sensors').checked)for(const n of data.nodes){const r=n.channels[c],good=r.status==='healthy';svg('circle',{cx:x(n.longitude),cy:y(n.latitude),r:8,fill:layer==='status'?({healthy:'#42b88d',stale:'#e8a64b',unauthenticated:'#e8c380',fixture:'#b89bec',rejected:'#e05d63',missing:'#748394'}[r.status]||'#e05d63'):good?'#effaff':'#e8c380',stroke:'#0b1d2b','stroke-width':3},$('positions'));const label=svg('text',{x:x(n.longitude)+12,y:y(n.latitude)-10,fill:'#f4f9fc','font-size':15,'font-weight':600},$('positions'));label.textContent=n.node_id}
for(const [text,xx,yy] of [[b.west.toFixed(4)+'°E',40,h+75],[b.east.toFixed(4)+'°E',w-40,h+75],[b.north.toFixed(4)+'°N',40,18],[b.south.toFixed(4)+'°N',40,h+55]])svg('text',{x:xx,y:yy,fill:'#8cabbf','font-size':12},$('axes')).textContent=text;
const unit=layer==='terrain'?'m EGM96':channels[c][1];$('scale-low').textContent=values.length?number(lo)+' '+unit:'No available values';$('scale-high').textContent=values.length?number(hi)+' '+unit:'';$('scale').style.display=layer==='status'?'none':'block';
$('coverage').textContent=layer==='uncertainty'?`${bands} / ${data.cells.length} checked bands`:layer==='terrain'?`${values.length} / ${data.cells.length} terrain pixels`:`${available} / ${data.cells.length} prediction cells`;$('model').textContent=data.model_version+' · '+(data.model_status==='loaded_with_per_cell_OOD_and_fallback'?'Ensemble loaded; physics fallback when required':data.model_status==='physics_baseline_only'?'Physics baseline only':'Model unavailable; physics fallback');$('bandnote').textContent=bands?`${bands} cells have checked archive intervals; field coverage unverified.`:'No uncertainty available: checked intervals are absent. Color shading is not confidence.';
$('mapnote').textContent=(data.nodes.length===2?'Two-node corridor checks; outside/end/distance limits refuse estimates.':'Three-or-more-node hull and maximum-distance checks; outside estimates refuse.')+' '+(layer==='terrain'?'Elevation is a separate static layer, not measured weather.':layer==='uncertainty'?'Blank cells have no checked interval.':'Each channel uses its own scale and coverage.')+' '+unit;
$('clock').textContent='Reference UTC: '+data.reference_time_utc+' | IST: '+new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'}).format(new Date(data.reference_time_utc))+' | generated '+data.generated_at_utc;
$('nodes').replaceChildren();for(const n of data.nodes){const r=n.channels[c],box=document.createElement('div');box.className='node';const title=document.createElement('strong');title.textContent=n.node_id+' · '+number(r.value)+' '+channels[c][1];box.appendChild(title);const p=document.createElement('p');p.className='meta';p.textContent=r.status+' | age '+(r.age_seconds===null?'unknown':r.age_seconds+' s')+' | auth '+(r.authenticated?'verified':'unverified')+' | '+r.quality_flag+' | '+r.source+' | observed '+(r.timestamp_utc||'unknown');box.appendChild(p);$('nodes').appendChild(box)}}
for(const id of ['channel','layer','support','sensors'])$(id).addEventListener('change',render);render();
</script></body></html>'''


def write_html(data,path):
    payload=json.dumps(data,allow_nan=False,separators=(',',':')).replace('<','\\u003c').replace('>','\\u003e').replace('&','\\u0026').replace('\u2028','\\u2028').replace('\u2029','\\u2029')
    Path(path).write_text(TEMPLATE.replace('__DATA__',payload))
