/* Generated by python -m ml.six_sensor_forecast.export. Research forecast, not a hazard alarm. */
#ifndef INDRA_SIX_SENSOR_FORECAST_H
#define INDRA_SIX_SENSOR_FORECAST_H
#include <math.h>
#include <stddef.h>
#define INDRA_FORECAST_INPUTS 5
#define INDRA_FORECAST_OUTPUTS 5
#define INDRA_FORECAST_HORIZON_HOURS 6
#define INDRA_FORECAST_STATUS "OFFLINE_RESEARCH_ONLY"
/* Input/output order: temperature_c, relative_humidity_pct, pm25_ug_m3, pm10_ug_m3, wind_speed_mps */
static inline float indra_fc_0_0(const float *x) {
  if (x[0] < 22.2399998f) {
    if (x[1] < 88.5299988f) {
      if (x[3] < 98.6100006f) {
        return -0.00607611798f;
      } else {
        return 0.363855809f;
      }
    } else {
      if (x[3] < 268.850006f) {
        return 0.776933849f;
      } else {
        return 0.373263896f;
      }
    }
  } else {
    if (x[1] < 78.8399963f) {
      if (x[1] < 20.7700005f) {
        return -0.817369401f;
      } else {
        return -0.19433032f;
      }
    } else {
      if (x[1] < 87.5f) {
        return 0.102986537f;
      } else {
        return 0.340362877f;
      }
    }
  }
}
static inline float indra_fc_0_1(const float *x) {
  if (x[0] < 21.8199997f) {
    if (x[2] < 159.330002f) {
      if (x[2] < 42.0800018f) {
        return 0.124639526f;
      } else {
        return 0.508451164f;
      }
    } else {
      if (x[0] < 12.6999998f) {
        return 0.895464063f;
      } else {
        return -0.153203756f;
      }
    }
  } else {
    if (x[0] < 36.5699997f) {
      if (x[2] < 80.2799988f) {
        return -0.128725424f;
      } else {
        return 0.139183626f;
      }
    } else {
      if (x[0] < 38.6399994f) {
        return -0.348262876f;
      } else {
        return -0.605414093f;
      }
    }
  }
}
static inline float indra_fc_0_2(const float *x) {
  if (x[1] < 79.8899994f) {
    if (x[2] < 53.8899994f) {
      if (x[1] < 36.7299995f) {
        return -0.681434512f;
      } else {
        return -0.207678154f;
      }
    } else {
      if (x[0] < 35.9799995f) {
        return 0.126520708f;
      } else {
        return -0.311251521f;
      }
    }
  } else {
    if (x[2] < 165.949997f) {
      if (x[0] < 18.8600006f) {
        return 0.604235351f;
      } else {
        return 0.231094033f;
      }
    } else {
      if (x[1] < 91.5f) {
        return -0.339558393f;
      } else {
        return -0.0118579241f;
      }
    }
  }
}
static inline float indra_fc_0_3(const float *x) {
  if (x[0] < 18.9799995f) {
    if (x[2] < 35.6699982f) {
      if (x[4] < 0.670000017f) {
        return 0.145741358f;
      } else {
        return -0.156774029f;
      }
    } else {
      if (x[2] < 150.630005f) {
        return 0.511121631f;
      } else {
        return -0.0390307717f;
      }
    }
  } else {
    if (x[0] < 37.1899986f) {
      if (x[2] < 88.0899963f) {
        return -0.0778276771f;
      } else {
        return 0.114936315f;
      }
    } else {
      if (x[4] < 1.0f) {
        return -0.464491129f;
      } else {
        return -0.263577759f;
      }
    }
  }
}
static inline float indra_fc_0_4(const float *x) {
  if (x[1] < 75.0f) {
    if (x[2] < 41.6699982f) {
      if (x[1] < 38.8100014f) {
        return -0.608133376f;
      } else {
        return -0.264643401f;
      }
    } else {
      if (x[1] < 29.0300007f) {
        return -0.217723355f;
      } else {
        return 0.0801439583f;
      }
    }
  } else {
    if (x[2] < 139.0f) {
      if (x[0] < 26.2199993f) {
        return 0.339485198f;
      } else {
        return 0.084808439f;
      }
    } else {
      if (x[0] < 14.0900002f) {
        return 0.232922897f;
      } else {
        return -0.243216231f;
      }
    }
  }
}
static inline float indra_fc_0_5(const float *x) {
  if (x[0] < 19.6599998f) {
    if (x[2] < 189.929993f) {
      if (x[2] < 37.1699982f) {
        return 0.0627925321f;
      } else {
        return 0.331773639f;
      }
    } else {
      if (x[0] < 13.6300001f) {
        return 0.283334881f;
      } else {
        return -0.245749503f;
      }
    }
  } else {
    if (x[0] < 36.1199989f) {
      if (x[2] < 92.6200027f) {
        return -0.0581320301f;
      } else {
        return 0.111544214f;
      }
    } else {
      if (x[0] < 39.7700005f) {
        return -0.157634869f;
      } else {
        return -0.348552287f;
      }
    }
  }
}
static inline float indra_fc_0_6(const float *x) {
  if (x[1] < 84.4899979f) {
    if (x[3] < 158.550003f) {
      if (x[1] < 39.0699997f) {
        return -0.332419217f;
      } else {
        return -0.0559961461f;
      }
    } else {
      if (x[1] < 32.8100014f) {
        return -0.0664914995f;
      } else {
        return 0.125745222f;
      }
    }
  } else {
    if (x[1] < 89.25f) {
      if (x[3] < 145.449997f) {
        return 0.210286289f;
      } else {
        return -0.0277860817f;
      }
    } else {
      if (x[0] < 7.76000023f) {
        return 0.0101545891f;
      } else {
        return 0.311234027f;
      }
    }
  }
}
static inline float indra_fc_0_7(const float *x) {
  if (x[1] < 77.4700012f) {
    if (x[3] < 79.8799973f) {
      if (x[1] < 67.1399994f) {
        return -0.366272777f;
      } else {
        return -0.0236962605f;
      }
    } else {
      if (x[1] < 21.8999996f) {
        return -0.295964956f;
      } else {
        return 0.0243364889f;
      }
    }
  } else {
    if (x[3] < 225.800003f) {
      if (x[0] < 23.5599995f) {
        return 0.266666055f;
      } else {
        return 0.0988892913f;
      }
    } else {
      if (x[1] < 91.25f) {
        return -0.110188805f;
      } else {
        return 0.200929761f;
      }
    }
  }
}
static inline float indra_fc_0_8(const float *x) {
  if (x[1] < 84.4899979f) {
    if (x[2] < 27.5499992f) {
      if (x[1] < 66.7099991f) {
        return -0.390608191f;
      } else {
        return -0.0173102655f;
      }
    } else {
      if (x[0] < 16.7600002f) {
        return 0.283252895f;
      } else {
        return -0.0193323866f;
      }
    }
  } else {
    if (x[2] < 131.589996f) {
      if (x[0] < 18.2999992f) {
        return 0.270781279f;
      } else {
        return 0.129590377f;
      }
    } else {
      if (x[0] < 13.8599997f) {
        return 0.178784996f;
      } else {
        return -0.174007446f;
      }
    }
  }
}
static inline float indra_fc_0_9(const float *x) {
  if (x[1] < 33.9799995f) {
    if (x[2] < 67.7200012f) {
      if (x[1] < 23.4599991f) {
        return -0.458540767f;
      } else {
        return -0.198571265f;
      }
    } else {
      if (x[0] < 40.5699997f) {
        return 0.000579028216f;
      } else {
        return -0.222765759f;
      }
    }
  } else {
    if (x[0] < 15.8699999f) {
      if (x[2] < 58.2900009f) {
        return 0.0481928661f;
      } else {
        return 0.396128893f;
      }
    } else {
      if (x[1] < 89.0299988f) {
        return -0.00342912413f;
      } else {
        return 0.139637604f;
      }
    }
  }
}
static inline float indra_fc_0_10(const float *x) {
  if (x[1] < 23.1200008f) {
    if (x[3] < 142.220001f) {
      if (x[3] < 52.1399994f) {
        return -0.926714897f;
      } else {
        return -0.392802805f;
      }
    } else {
      if (x[0] < 26.9300003f) {
        return -0.44153896f;
      } else {
        return -0.0518206246f;
      }
    }
  } else {
    if (x[4] < 0.930000007f) {
      if (x[0] < 33.8899994f) {
        return 0.0753241703f;
      } else {
        return -0.183329791f;
      }
    } else {
      if (x[0] < 29.7299995f) {
        return -0.127211556f;
      } else {
        return 0.033416342f;
      }
    }
  }
}
static inline float indra_fc_0_11(const float *x) {
  if (x[0] < 16.4300003f) {
    if (x[2] < 54.4000015f) {
      if (x[4] < 0.140000001f) {
        return -0.328989685f;
      } else {
        return 0.0567420796f;
      }
    } else {
      if (x[2] < 211.089996f) {
        return 0.336453736f;
      } else {
        return -0.244568661f;
      }
    }
  } else {
    if (x[3] < 348.820007f) {
      if (x[2] < 97.3499985f) {
        return -0.0311346594f;
      } else {
        return 0.0885483176f;
      }
    } else {
      if (x[4] < 0.209999993f) {
        return -0.461397141f;
      } else {
        return -0.0824299082f;
      }
    }
  }
}
static inline float indra_fc_0_12(const float *x) {
  if (x[1] < 39.5600014f) {
    if (x[3] < 141.199997f) {
      if (x[0] < 34.0999985f) {
        return -0.306292534f;
      } else {
        return -0.0554992631f;
      }
    } else {
      if (x[0] < 23.6499996f) {
        return 0.11989975f;
      } else {
        return -0.0276111756f;
      }
    }
  } else {
    if (x[4] < 1.20000005f) {
      if (x[0] < 35.8400002f) {
        return 0.0778238699f;
      } else {
        return -0.31381309f;
      }
    } else {
      if (x[1] < 70.7200012f) {
        return -0.129609272f;
      } else {
        return 0.046145115f;
      }
    }
  }
}
static inline float indra_fc_0_13(const float *x) {
  if (x[2] < 30.3199997f) {
    if (x[4] < 0.170000002f) {
      if (x[0] < 27.4899998f) {
        return -0.341665089f;
      } else {
        return 0.112869956f;
      }
    } else {
      if (x[0] < 27.3299999f) {
        return 0.0036535617f;
      } else {
        return -0.119468562f;
      }
    }
  } else {
    if (x[0] < 15.3100004f) {
      if (x[0] < 9.80000019f) {
        return -0.230232835f;
      } else {
        return 0.259914607f;
      }
    } else {
      if (x[0] < 39.4900017f) {
        return 0.017798407f;
      } else {
        return -0.153390273f;
      }
    }
  }
}
static inline float indra_fc_0_14(const float *x) {
  if (x[1] < 25.8600006f) {
    if (x[2] < 92.6200027f) {
      if (x[3] < 79.8799973f) {
        return -0.512723625f;
      } else {
        return -0.167895675f;
      }
    } else {
      if (x[0] < 26.4500008f) {
        return -0.288523108f;
      } else {
        return 0.122290909f;
      }
    }
  } else {
    if (x[3] < 348.820007f) {
      if (x[2] < 30.3199997f) {
        return -0.0404345319f;
      } else {
        return 0.0516460352f;
      }
    } else {
      if (x[0] < 28.6700001f) {
        return -0.210104749f;
      } else {
        return 0.0455073826f;
      }
    }
  }
}
static inline float indra_fc_0_15(const float *x) {
  if (x[1] < 40.0800018f) {
    if (x[2] < 67.7200012f) {
      if (x[4] < 0.850000024f) {
        return -0.243500039f;
      } else {
        return -0.0469695143f;
      }
    } else {
      if (x[4] < 1.66999996f) {
        return 0.0359919034f;
      } else {
        return -0.221200019f;
      }
    }
  } else {
    if (x[2] < 178.889999f) {
      if (x[4] < 0.579999983f) {
        return 0.106953457f;
      } else {
        return -0.00371336751f;
      }
    } else {
      if (x[3] < 282.149994f) {
        return 0.232600808f;
      } else {
        return -0.224737644f;
      }
    }
  }
}
static inline float indra_fc_head_0(const float *x) {
  float residual = -0.08034244f;
  residual += indra_fc_0_0(x);
  residual += indra_fc_0_1(x);
  residual += indra_fc_0_2(x);
  residual += indra_fc_0_3(x);
  residual += indra_fc_0_4(x);
  residual += indra_fc_0_5(x);
  residual += indra_fc_0_6(x);
  residual += indra_fc_0_7(x);
  residual += indra_fc_0_8(x);
  residual += indra_fc_0_9(x);
  residual += indra_fc_0_10(x);
  residual += indra_fc_0_11(x);
  residual += indra_fc_0_12(x);
  residual += indra_fc_0_13(x);
  residual += indra_fc_0_14(x);
  residual += indra_fc_0_15(x);
  float value = x[0] + 1.0f * residual;
  return fminf(85.0f, fmaxf(-60.0f, value));
}
static inline float indra_fc_1_0(const float *x) {
  if (x[1] < 83.1600037f) {
    if (x[3] < 80.2200012f) {
      if (x[1] < 69.3199997f) {
        return 2.39931273f;
      } else {
        return 0.18015103f;
      }
    } else {
      if (x[0] < 22.0699997f) {
        return -0.388493776f;
      } else {
        return 0.368444055f;
      }
    }
  } else {
    if (x[0] < 19.2999992f) {
      if (x[3] < 232.350006f) {
        return -3.66628623f;
      } else {
        return -1.30801308f;
      }
    } else {
      if (x[1] < 89.1100006f) {
        return -0.756866634f;
      } else {
        return -1.74295413f;
      }
    }
  }
}
static inline float indra_fc_1_1(const float *x) {
  if (x[0] < 19.0300007f) {
    if (x[2] < 159.660004f) {
      if (x[2] < 36.6199989f) {
        return -0.565575361f;
      } else {
        return -1.75012434f;
      }
    } else {
      if (x[0] < 13.8999996f) {
        return -1.05975294f;
      } else {
        return 0.592613459f;
      }
    }
  } else {
    if (x[2] < 81.7799988f) {
      if (x[4] < 1.51999998f) {
        return 0.287932873f;
      } else {
        return 0.867031217f;
      }
    } else {
      if (x[0] < 35.9900017f) {
        return -0.242415771f;
      } else {
        return 0.459805459f;
      }
    }
  }
}
static inline float indra_fc_1_2(const float *x) {
  if (x[1] < 79.6999969f) {
    if (x[2] < 35.4700012f) {
      if (x[1] < 66.8600006f) {
        return 2.02376056f;
      } else {
        return 0.533477843f;
      }
    } else {
      if (x[2] < 77.9100037f) {
        return 0.387698472f;
      } else {
        return -0.136523798f;
      }
    }
  } else {
    if (x[0] < 15.9399996f) {
      if (x[2] < 159.660004f) {
        return -2.89488959f;
      } else {
        return 0.373608321f;
      }
    } else {
      if (x[1] < 87.8600006f) {
        return -0.522971034f;
      } else {
        return -1.50293958f;
      }
    }
  }
}
static inline float indra_fc_1_3(const float *x) {
  if (x[0] < 20.2099991f) {
    if (x[2] < 163.070007f) {
      if (x[2] < 41.0f) {
        return -0.333743304f;
      } else {
        return -1.13890731f;
      }
    } else {
      if (x[3] < 273.119995f) {
        return -1.29898131f;
      } else {
        return 0.526905477f;
      }
    }
  } else {
    if (x[4] < 1.36000001f) {
      if (x[0] < 35.1800003f) {
        return 0.0248962026f;
      } else {
        return 0.448500961f;
      }
    } else {
      if (x[0] < 32.3899994f) {
        return 0.698346853f;
      } else {
        return 0.126402661f;
      }
    }
  }
}
static inline float indra_fc_1_4(const float *x) {
  if (x[1] < 76.5699997f) {
    if (x[2] < 30.5f) {
      if (x[1] < 62.8600006f) {
        return 1.953969f;
      } else {
        return 0.762127757f;
      }
    } else {
      if (x[2] < 71.8799973f) {
        return 0.411231041f;
      } else {
        return -0.0676169023f;
      }
    }
  } else {
    if (x[1] < 89.1100006f) {
      if (x[2] < 145.910004f) {
        return -0.660463989f;
      } else {
        return 0.802346051f;
      }
    } else {
      if (x[0] < 22.1700001f) {
        return -2.0732944f;
      } else {
        return -0.997206688f;
      }
    }
  }
}
static inline float indra_fc_1_5(const float *x) {
  if (x[0] < 22.0699997f) {
    if (x[4] < 0.680000007f) {
      if (x[2] < 184.360001f) {
        return -0.651530027f;
      } else {
        return 0.39689514f;
      }
    } else {
      if (x[0] < 9.64000034f) {
        return 1.5149709f;
      } else {
        return -0.0709659979f;
      }
    }
  } else {
    if (x[2] < 22.5100002f) {
      if (x[0] < 28.0499992f) {
        return 0.0983938649f;
      } else {
        return 0.860572338f;
      }
    } else {
      if (x[0] < 36.4300003f) {
        return 0.0566548482f;
      } else {
        return 0.300293744f;
      }
    }
  }
}
static inline float indra_fc_1_6(const float *x) {
  if (x[1] < 84.8799973f) {
    if (x[3] < 95.3899994f) {
      if (x[1] < 70.5100021f) {
        return 1.09149778f;
      } else {
        return -0.166276336f;
      }
    } else {
      if (x[1] < 38.75f) {
        return 0.245044857f;
      } else {
        return -0.12993668f;
      }
    }
  } else {
    if (x[0] < 15.54f) {
      if (x[0] < 6.51999998f) {
        return -0.666105807f;
      } else {
        return -1.97644961f;
      }
    } else {
      if (x[1] < 92.0899963f) {
        return -0.590428352f;
      } else {
        return -1.21041274f;
      }
    }
  }
}
static inline float indra_fc_1_7(const float *x) {
  if (x[1] < 79.3399963f) {
    if (x[3] < 74.4000015f) {
      if (x[1] < 61.0900002f) {
        return 1.36574292f;
      } else {
        return 0.328543276f;
      }
    } else {
      if (x[0] < 11.2299995f) {
        return 1.60711348f;
      } else {
        return 0.0609592497f;
      }
    }
  } else {
    if (x[0] < 23.2000008f) {
      if (x[3] < 228.380005f) {
        return -1.28563154f;
      } else {
        return -0.0130311204f;
      }
    } else {
      if (x[1] < 86.7799988f) {
        return -0.116744556f;
      } else {
        return -0.545146167f;
      }
    }
  }
}
static inline float indra_fc_1_8(const float *x) {
  if (x[1] < 74.7900009f) {
    if (x[2] < 24.75f) {
      if (x[1] < 51.7400017f) {
        return 1.7883606f;
      } else {
        return 0.768733799f;
      }
    } else {
      if (x[2] < 92.8099976f) {
        return 0.21016109f;
      } else {
        return -0.17163828f;
      }
    }
  } else {
    if (x[2] < 150.770004f) {
      if (x[0] < 22.3799992f) {
        return -1.04188025f;
      } else {
        return -0.239777848f;
      }
    } else {
      if (x[0] < 21.3199997f) {
        return 0.84951508f;
      } else {
        return -0.699125469f;
      }
    }
  }
}
static inline float indra_fc_1_9(const float *x) {
  if (x[1] < 72.8899994f) {
    if (x[2] < 27.3400002f) {
      if (x[0] < 29.2199993f) {
        return 1.37100029f;
      } else {
        return 0.286753535f;
      }
    } else {
      if (x[3] < 158.0f) {
        return 0.216501117f;
      } else {
        return -0.0976996869f;
      }
    }
  } else {
    if (x[0] < 26.2399998f) {
      if (x[2] < 139.110001f) {
        return -0.705207527f;
      } else {
        return 0.445489734f;
      }
    } else {
      if (x[1] < 84.5800018f) {
        return 0.136074528f;
      } else {
        return -0.24018307f;
      }
    }
  }
}
static inline float indra_fc_1_10(const float *x) {
  if (x[1] < 90.6200027f) {
    if (x[3] < 32.7999992f) {
      if (x[1] < 58.8499985f) {
        return 2.0590713f;
      } else {
        return 0.270235837f;
      }
    } else {
      if (x[1] < 42.9199982f) {
        return 0.191003636f;
      } else {
        return -0.0975958183f;
      }
    }
  } else {
    if (x[4] < 0.579999983f) {
      if (x[0] < 23.1200008f) {
        return -1.23530138f;
      } else {
        return -0.525335193f;
      }
    } else {
      if (x[0] < 8.61999989f) {
        return 1.20802104f;
      } else {
        return -0.271519631f;
      }
    }
  }
}
static inline float indra_fc_1_11(const float *x) {
  if (x[0] < 16.9699993f) {
    if (x[0] < 8.61999989f) {
      if (x[3] < 65.1999969f) {
        return -0.232893974f;
      } else {
        return 0.839129448f;
      }
    } else {
      if (x[4] < 1.26999998f) {
        return -0.530998707f;
      } else {
        return 1.09521711f;
      }
    }
  } else {
    if (x[4] < 1.79999995f) {
      if (x[2] < 18.1800003f) {
        return 0.236587763f;
      } else {
        return -0.012435223f;
      }
    } else {
      if (x[0] < 30.9500008f) {
        return 0.600323498f;
      } else {
        return -0.02427499f;
      }
    }
  }
}
static inline float indra_fc_1_12(const float *x) {
  if (x[1] < 72.8899994f) {
    if (x[3] < 110.68f) {
      if (x[0] < 29.2199993f) {
        return 0.946676373f;
      } else {
        return -0.156616062f;
      }
    } else {
      if (x[1] < 34.5999985f) {
        return 0.163365468f;
      } else {
        return -0.140280008f;
      }
    }
  } else {
    if (x[4] < 0.50999999f) {
      if (x[0] < 27.0300007f) {
        return -0.639514208f;
      } else {
        return 0.124142863f;
      }
    } else {
      if (x[0] < 8.61999989f) {
        return 1.04607356f;
      } else {
        return -0.13130264f;
      }
    }
  }
}
static inline float indra_fc_1_13(const float *x) {
  if (x[4] < 1.20000005f) {
    if (x[2] < 42.2700005f) {
      if (x[4] < 0.189999998f) {
        return 0.848963737f;
      } else {
        return -0.0206925701f;
      }
    } else {
      if (x[0] < 15.1499996f) {
        return -0.637730956f;
      } else {
        return -0.0680282712f;
      }
    }
  } else {
    if (x[0] < 30.6000004f) {
      if (x[3] < 56.0999985f) {
        return 0.139320835f;
      } else {
        return 0.664631784f;
      }
    } else {
      if (x[3] < 47.3800011f) {
        return 0.521262765f;
      } else {
        return -0.215694338f;
      }
    }
  }
}
static inline float indra_fc_1_14(const float *x) {
  if (x[1] < 85.6999969f) {
    if (x[2] < 15.8400002f) {
      if (x[1] < 63.6699982f) {
        return 1.27873409f;
      } else {
        return 0.178472251f;
      }
    } else {
      if (x[1] < 41.3199997f) {
        return 0.156478286f;
      } else {
        return -0.0782216638f;
      }
    }
  } else {
    if (x[2] < 114.309998f) {
      if (x[0] < 18.4699993f) {
        return -0.795139492f;
      } else {
        return -0.273429245f;
      }
    } else {
      if (x[0] < 13.8999996f) {
        return -0.572750032f;
      } else {
        return 0.743962526f;
      }
    }
  }
}
static inline float indra_fc_1_15(const float *x) {
  if (x[1] < 92.0899963f) {
    if (x[1] < 27.7299995f) {
      if (x[3] < 56.0999985f) {
        return 1.77438343f;
      } else {
        return 0.221058115f;
      }
    } else {
      if (x[2] < 41.4700012f) {
        return 0.126599237f;
      } else {
        return -0.0857193023f;
      }
    }
  } else {
    if (x[4] < 0.430000007f) {
      if (x[2] < 166.0f) {
        return -0.894782066f;
      } else {
        return 0.671506345f;
      }
    } else {
      if (x[3] < 63.25f) {
        return -0.114963822f;
      } else {
        return -0.573821485f;
      }
    }
  }
}
static inline float indra_fc_head_1(const float *x) {
  float residual = 0.25541604f;
  residual += indra_fc_1_0(x);
  residual += indra_fc_1_1(x);
  residual += indra_fc_1_2(x);
  residual += indra_fc_1_3(x);
  residual += indra_fc_1_4(x);
  residual += indra_fc_1_5(x);
  residual += indra_fc_1_6(x);
  residual += indra_fc_1_7(x);
  residual += indra_fc_1_8(x);
  residual += indra_fc_1_9(x);
  residual += indra_fc_1_10(x);
  residual += indra_fc_1_11(x);
  residual += indra_fc_1_12(x);
  residual += indra_fc_1_13(x);
  residual += indra_fc_1_14(x);
  residual += indra_fc_1_15(x);
  float value = x[1] + 1.0f * residual;
  return fminf(100.0f, fmaxf(0.0f, value));
}
static inline float indra_fc_2_0(const float *x) {
  if (x[3] < 290.899994f) {
    if (x[1] < 71.4800034f) {
      if (x[3] < 159.399994f) {
        return 4.15885115f;
      } else {
        return -0.0276731886f;
      }
    } else {
      if (x[3] < 152.779999f) {
        return -0.211380124f;
      } else {
        return -4.44120884f;
      }
    }
  } else {
    if (x[3] < 427.899994f) {
      if (x[4] < 1.22000003f) {
        return -9.82476807f;
      } else {
        return -1.74246562f;
      }
    } else {
      if (x[4] < 1.90999997f) {
        return -21.0962067f;
      } else {
        return -7.15654898f;
      }
    }
  }
}
static inline float indra_fc_2_1(const float *x) {
  if (x[2] < 179.309998f) {
    if (x[2] < 100.220001f) {
      if (x[2] < 76.0699997f) {
        return 2.68768406f;
      } else {
        return 0.341001987f;
      }
    } else {
      if (x[2] < 133.699997f) {
        return -3.15228963f;
      } else {
        return -7.2299118f;
      }
    }
  } else {
    if (x[2] < 349.970001f) {
      if (x[2] < 253.5f) {
        return -13.5535936f;
      } else {
        return -26.0734081f;
      }
    } else {
      if (x[3] < 399.5f) {
        return -94.1859589f;
      } else {
        return -51.4050484f;
      }
    }
  }
}
static inline float indra_fc_2_2(const float *x) {
  if (x[2] < 221.889999f) {
    if (x[2] < 106.32f) {
      if (x[1] < 67.0699997f) {
        return 3.33089256f;
      } else {
        return -0.49683696f;
      }
    } else {
      if (x[2] < 156.800003f) {
        return -3.67204833f;
      } else {
        return -8.05753517f;
      }
    }
  } else {
    if (x[2] < 349.970001f) {
      if (x[2] < 300.459991f) {
        return -16.4946728f;
      } else {
        return -26.5339851f;
      }
    } else {
      if (x[4] < 0.689999998f) {
        return -39.1961136f;
      } else {
        return -69.7495117f;
      }
    }
  }
}
static inline float indra_fc_2_3(const float *x) {
  if (x[2] < 196.410004f) {
    if (x[2] < 92.9800034f) {
      if (x[0] < 18.8999996f) {
        return -0.00166700676f;
      } else {
        return 1.92888546f;
      }
    } else {
      if (x[2] < 131.910004f) {
        return -1.7803576f;
      } else {
        return -5.11421537f;
      }
    }
  } else {
    if (x[2] < 349.970001f) {
      if (x[2] < 274.0f) {
        return -10.818408f;
      } else {
        return -19.2318268f;
      }
    } else {
      if (x[3] < 399.5f) {
        return -74.1640854f;
      } else {
        return -30.9328499f;
      }
    }
  }
}
static inline float indra_fc_2_4(const float *x) {
  if (x[2] < 221.889999f) {
    if (x[2] < 87.7200012f) {
      if (x[1] < 62.1500015f) {
        return 3.13049865f;
      } else {
        return -0.433708876f;
      }
    } else {
      if (x[0] < 37.3400002f) {
        return -2.84920669f;
      } else {
        return 1.76792908f;
      }
    }
  } else {
    if (x[2] < 349.970001f) {
      if (x[2] < 300.459991f) {
        return -11.10816f;
      } else {
        return -18.1909389f;
      }
    } else {
      if (x[3] < 349.269989f) {
        return -59.8970757f;
      } else {
        return -26.3877144f;
      }
    }
  }
}
static inline float indra_fc_2_5(const float *x) {
  if (x[2] < 119.0f) {
    if (x[2] < 66.3399963f) {
      if (x[3] < 113.620003f) {
        return 0.851604879f;
      } else {
        return 2.99913239f;
      }
    } else {
      if (x[3] < 174.179993f) {
        return -1.6010586f;
      } else {
        return 0.755174816f;
      }
    }
  } else {
    if (x[2] < 300.459991f) {
      if (x[0] < 34.4399986f) {
        return -4.92654133f;
      } else {
        return 0.0190402176f;
      }
    } else {
      if (x[3] < 317.279999f) {
        return -45.6040611f;
      } else {
        return -16.493f;
      }
    }
  }
}
static inline float indra_fc_2_6(const float *x) {
  if (x[1] < 77.4100037f) {
    if (x[3] < 349.269989f) {
      if (x[1] < 37.1300011f) {
        return 1.76122272f;
      } else {
        return 0.26300934f;
      }
    } else {
      if (x[4] < 2.5f) {
        return -3.51454091f;
      } else {
        return 10.2550344f;
      }
    }
  } else {
    if (x[3] < 290.899994f) {
      if (x[3] < 50.0f) {
        return -0.408109516f;
      } else {
        return -1.92480874f;
      }
    } else {
      if (x[3] < 621.900024f) {
        return -5.06254768f;
      } else {
        return -13.6751757f;
      }
    }
  }
}
static inline float indra_fc_2_7(const float *x) {
  if (x[1] < 74.9100037f) {
    if (x[3] < 135.899994f) {
      if (x[1] < 22.7199993f) {
        return 6.75615263f;
      } else {
        return 1.1531167f;
      }
    } else {
      if (x[1] < 40.2200012f) {
        return 0.613129795f;
      } else {
        return -1.51811218f;
      }
    }
  } else {
    if (x[3] < 323.720001f) {
      if (x[3] < 41.0f) {
        return -0.16316177f;
      } else {
        return -1.45319223f;
      }
    } else {
      if (x[3] < 621.900024f) {
        return -4.31435966f;
      } else {
        return -10.5683823f;
      }
    }
  }
}
static inline float indra_fc_2_8(const float *x) {
  if (x[2] < 174.639999f) {
    if (x[2] < 76.7600021f) {
      if (x[1] < 63.0499992f) {
        return 2.22200561f;
      } else {
        return -0.247299299f;
      }
    } else {
      if (x[4] < 0.159999996f) {
        return 2.43194938f;
      } else {
        return -1.30132723f;
      }
    }
  } else {
    if (x[2] < 349.970001f) {
      if (x[4] < 2.3900001f) {
        return -5.7022624f;
      } else {
        return 7.74786377f;
      }
    } else {
      if (x[4] < 0.670000017f) {
        return -12.5378523f;
      } else {
        return -32.3345451f;
      }
    }
  }
}
static inline float indra_fc_2_9(const float *x) {
  if (x[2] < 133.699997f) {
    if (x[1] < 67.8899994f) {
      if (x[2] < 59.5600014f) {
        return 2.23515916f;
      } else {
        return -0.0753939375f;
      }
    } else {
      if (x[2] < 36.0800018f) {
        return 0.147335738f;
      } else {
        return -1.2755307f;
      }
    }
  } else {
    if (x[2] < 274.0f) {
      if (x[0] < 36.7200012f) {
        return -3.26663375f;
      } else {
        return 1.64336264f;
      }
    } else {
      if (x[3] < 261.149994f) {
        return -34.1050873f;
      } else {
        return -8.68602085f;
      }
    }
  }
}
static inline float indra_fc_2_10(const float *x) {
  if (x[4] < 1.27999997f) {
    if (x[1] < 21.5200005f) {
      if (x[3] < 218.949997f) {
        return 3.89601445f;
      } else {
        return -4.08767462f;
      }
    } else {
      if (x[4] < 0.0799999982f) {
        return 2.35767317f;
      } else {
        return -0.567339301f;
      }
    }
  } else {
    if (x[1] < 61.25f) {
      if (x[0] < 29.7800007f) {
        return 6.33169937f;
      } else {
        return 0.632626534f;
      }
    } else {
      if (x[3] < 745.940002f) {
        return -0.481256545f;
      } else {
        return -14.5216341f;
      }
    }
  }
}
static inline float indra_fc_2_11(const float *x) {
  if (x[2] < 221.889999f) {
    if (x[2] < 60.0699997f) {
      if (x[3] < 133.75f) {
        return 0.441739768f;
      } else {
        return 2.76048827f;
      }
    } else {
      if (x[4] < 0.159999996f) {
        return 1.67896807f;
      } else {
        return -0.830819428f;
      }
    }
  } else {
    if (x[2] < 349.970001f) {
      if (x[3] < 427.899994f) {
        return -8.20718384f;
      } else {
        return -3.67868543f;
      }
    } else {
      if (x[0] < 33.2599983f) {
        return -17.6883106f;
      } else {
        return 3.44016814f;
      }
    }
  }
}
static inline float indra_fc_2_12(const float *x) {
  if (x[1] < 38.7599983f) {
    if (x[4] < 2.42000008f) {
      if (x[4] < 0.330000013f) {
        return 2.48368955f;
      } else {
        return 0.332458019f;
      }
    } else {
      if (x[1] < 37.8300018f) {
        return 7.19180679f;
      } else {
        return 40.405468f;
      }
    }
  } else {
    if (x[4] < 1.0f) {
      if (x[1] < 63.4500008f) {
        return -1.15660655f;
      } else {
        return -0.323828727f;
      }
    } else {
      if (x[0] < 29.4099998f) {
        return 1.32003069f;
      } else {
        return -0.849069238f;
      }
    }
  }
}
static inline float indra_fc_2_13(const float *x) {
  if (x[2] < 203.5f) {
    if (x[2] < 101.970001f) {
      if (x[3] < 184.720001f) {
        return 0.208517388f;
      } else {
        return 1.87201273f;
      }
    } else {
      if (x[3] < 302.730011f) {
        return -1.76290262f;
      } else {
        return 0.763945937f;
      }
    }
  } else {
    if (x[3] < 170.309998f) {
      if (x[4] < 1.14999998f) {
        return -0.513253391f;
      } else {
        return -38.203701f;
      }
    } else {
      if (x[4] < 2.67000008f) {
        return -5.00981188f;
      } else {
        return 13.1472425f;
      }
    }
  }
}
static inline float indra_fc_2_14(const float *x) {
  if (x[2] < 156.800003f) {
    if (x[3] < 387.0f) {
      if (x[1] < 78.1100006f) {
        return 0.487845987f;
      } else {
        return -0.577072382f;
      }
    } else {
      if (x[2] < 9.69999981f) {
        return 17.3779049f;
      } else {
        return 4.1987257f;
      }
    }
  } else {
    if (x[2] < 349.970001f) {
      if (x[0] < 36.7200012f) {
        return -2.90326452f;
      } else {
        return 1.93104732f;
      }
    } else {
      if (x[3] < 399.5f) {
        return -34.2632217f;
      } else {
        return -6.74054193f;
      }
    }
  }
}
static inline float indra_fc_2_15(const float *x) {
  if (x[2] < 113.370003f) {
    if (x[1] < 33.9300003f) {
      if (x[2] < 53.0800018f) {
        return 3.37595606f;
      } else {
        return 0.418980807f;
      }
    } else {
      if (x[4] < 1.32000005f) {
        return -0.212976724f;
      } else {
        return 0.784552634f;
      }
    }
  } else {
    if (x[2] < 349.970001f) {
      if (x[3] < 218.949997f) {
        return -3.17862797f;
      } else {
        return -0.816742539f;
      }
    } else {
      if (x[4] < 0.939999998f) {
        return -3.70803261f;
      } else {
        return -24.2736244f;
      }
    }
  }
}
static inline float indra_fc_head_2(const float *x) {
  float residual = 0.7632242f;
  residual += indra_fc_2_0(x);
  residual += indra_fc_2_1(x);
  residual += indra_fc_2_2(x);
  residual += indra_fc_2_3(x);
  residual += indra_fc_2_4(x);
  residual += indra_fc_2_5(x);
  residual += indra_fc_2_6(x);
  residual += indra_fc_2_7(x);
  residual += indra_fc_2_8(x);
  residual += indra_fc_2_9(x);
  residual += indra_fc_2_10(x);
  residual += indra_fc_2_11(x);
  residual += indra_fc_2_12(x);
  residual += indra_fc_2_13(x);
  residual += indra_fc_2_14(x);
  residual += indra_fc_2_15(x);
  float value = x[2] + 0.75f * residual;
  return fminf(5000.0f, fmaxf(0.0f, value));
}
static inline float indra_fc_3_0(const float *x) {
  if (x[3] < 349.0f) {
    if (x[3] < 199.860001f) {
      if (x[1] < 70.4899979f) {
        return 8.24703598f;
      } else {
        return -0.317976385f;
      }
    } else {
      if (x[1] < 57.9300003f) {
        return -3.81888509f;
      } else {
        return -15.4622898f;
      }
    }
  } else {
    if (x[3] < 556.200012f) {
      if (x[3] < 428.059998f) {
        return -24.6140709f;
      } else {
        return -38.9454918f;
      }
    } else {
      if (x[3] < 747.780029f) {
        return -64.4725494f;
      } else {
        return -98.2778091f;
      }
    }
  }
}
static inline float indra_fc_3_1(const float *x) {
  if (x[3] < 294.25f) {
    if (x[3] < 159.300003f) {
      if (x[0] < 19.5499992f) {
        return 1.76959991f;
      } else {
        return 5.38183641f;
      }
    } else {
      if (x[0] < 28.3299999f) {
        return -4.25757742f;
      } else {
        return 0.718020439f;
      }
    }
  } else {
    if (x[3] < 556.200012f) {
      if (x[3] < 399.670013f) {
        return -15.4513779f;
      } else {
        return -28.8276768f;
      }
    } else {
      if (x[3] < 747.780029f) {
        return -50.6421623f;
      } else {
        return -76.3959351f;
      }
    }
  }
}
static inline float indra_fc_3_2(const float *x) {
  if (x[2] < 128.679993f) {
    if (x[1] < 72.8300018f) {
      if (x[2] < 88.3899994f) {
        return 5.99525023f;
      } else {
        return -1.18827415f;
      }
    } else {
      if (x[2] < 61.4799995f) {
        return -1.18189061f;
      } else {
        return -7.13214827f;
      }
    }
  } else {
    if (x[2] < 234.5f) {
      if (x[0] < 36.8499985f) {
        return -12.9263372f;
      } else {
        return 1.20202303f;
      }
    } else {
      if (x[2] < 298.75f) {
        return -27.6739712f;
      } else {
        return -42.8185043f;
      }
    }
  }
}
static inline float indra_fc_3_3(const float *x) {
  if (x[3] < 312.390015f) {
    if (x[3] < 144.0f) {
      if (x[4] < 1.32000005f) {
        return 3.0307014f;
      } else {
        return 5.47977209f;
      }
    } else {
      if (x[3] < 248.380005f) {
        return -0.247631028f;
      } else {
        return -5.98304844f;
      }
    }
  } else {
    if (x[3] < 556.200012f) {
      if (x[0] < 36.0999985f) {
        return -16.6435204f;
      } else {
        return -1.37703753f;
      }
    } else {
      if (x[3] < 747.780029f) {
        return -37.9908257f;
      } else {
        return -60.1830254f;
      }
    }
  }
}
static inline float indra_fc_3_4(const float *x) {
  if (x[3] < 376.399994f) {
    if (x[1] < 65.0800018f) {
      if (x[3] < 135.699997f) {
        return 6.92787504f;
      } else {
        return 0.0588955171f;
      }
    } else {
      if (x[3] < 128.789993f) {
        return -0.241154268f;
      } else {
        return -7.15121984f;
      }
    }
  } else {
    if (x[3] < 619.219971f) {
      if (x[0] < 36.5299988f) {
        return -18.1016293f;
      } else {
        return -4.06004047f;
      }
    } else {
      if (x[0] < 36.8499985f) {
        return -44.7142372f;
      } else {
        return -11.0455904f;
      }
    }
  }
}
static inline float indra_fc_3_5(const float *x) {
  if (x[3] < 269.829987f) {
    if (x[3] < 140.779999f) {
      if (x[0] < 18.75f) {
        return 0.445066512f;
      } else {
        return 2.69287395f;
      }
    } else {
      if (x[0] < 23.4899998f) {
        return -2.2341969f;
      } else {
        return 1.06465912f;
      }
    }
  } else {
    if (x[3] < 486.100006f) {
      if (x[0] < 34.1899986f) {
        return -9.13738537f;
      } else {
        return -1.40215933f;
      }
    } else {
      if (x[0] < 37.8499985f) {
        return -26.6138954f;
      } else {
        return -1.09798324f;
      }
    }
  }
}
static inline float indra_fc_3_6(const float *x) {
  if (x[3] < 283.019989f) {
    if (x[1] < 61.9000015f) {
      if (x[3] < 121.0f) {
        return 5.8002224f;
      } else {
        return 1.29524159f;
      }
    } else {
      if (x[3] < 107.919998f) {
        return -0.226065829f;
      } else {
        return -4.16269779f;
      }
    }
  } else {
    if (x[3] < 443.399994f) {
      if (x[1] < 85.3300018f) {
        return -4.82639647f;
      } else {
        return -13.3988066f;
      }
    } else {
      if (x[3] < 747.780029f) {
        return -15.6588354f;
      } else {
        return -35.127449f;
      }
    }
  }
}
static inline float indra_fc_3_7(const float *x) {
  if (x[3] < 267.070007f) {
    if (x[1] < 36.2799988f) {
      if (x[1] < 21.8799992f) {
        return 8.731884f;
      } else {
        return 3.14824057f;
      }
    } else {
      if (x[1] < 78.25f) {
        return 0.952922761f;
      } else {
        return -2.05946064f;
      }
    }
  } else {
    if (x[3] < 619.219971f) {
      if (x[0] < 36.7099991f) {
        return -6.48148727f;
      } else {
        return 1.08621347f;
      }
    } else {
      if (x[0] < 36.0999985f) {
        return -25.0898857f;
      } else {
        return -5.65243483f;
      }
    }
  }
}
static inline float indra_fc_3_8(const float *x) {
  if (x[2] < 106.379997f) {
    if (x[1] < 38.3499985f) {
      if (x[1] < 23.0900002f) {
        return 7.22597742f;
      } else {
        return 2.80744576f;
      }
    } else {
      if (x[4] < 1.10000002f) {
        return -1.16442382f;
      } else {
        return 1.55235469f;
      }
    }
  } else {
    if (x[2] < 221.229996f) {
      if (x[0] < 37.4900017f) {
        return -3.39759564f;
      } else {
        return 3.08359027f;
      }
    } else {
      if (x[2] < 346.0f) {
        return -8.19179153f;
      } else {
        return -16.0906239f;
      }
    }
  }
}
static inline float indra_fc_3_9(const float *x) {
  if (x[3] < 243.800003f) {
    if (x[1] < 76.8700027f) {
      if (x[3] < 98.0f) {
        return 3.61720586f;
      } else {
        return 0.744184434f;
      }
    } else {
      if (x[3] < 73.0f) {
        return 0.0232017785f;
      } else {
        return -3.16934896f;
      }
    }
  } else {
    if (x[3] < 511.670013f) {
      if (x[1] < 87.75f) {
        return -2.58239222f;
      } else {
        return -9.92676449f;
      }
    } else {
      if (x[3] < 747.780029f) {
        return -10.813405f;
      } else {
        return -22.3395348f;
      }
    }
  }
}
static inline float indra_fc_3_10(const float *x) {
  if (x[3] < 349.0f) {
    if (x[1] < 62.3899994f) {
      if (x[3] < 85.1500015f) {
        return 5.04925489f;
      } else {
        return 0.570717454f;
      }
    } else {
      if (x[3] < 98.8799973f) {
        return -0.0335009396f;
      } else {
        return -2.56962633f;
      }
    }
  } else {
    if (x[3] < 619.219971f) {
      if (x[4] < 2.29999995f) {
        return -5.22843218f;
      } else {
        return 8.71812534f;
      }
    } else {
      if (x[1] < 84.5100021f) {
        return -16.7080688f;
      } else {
        return 2.95854449f;
      }
    }
  }
}
static inline float indra_fc_3_11(const float *x) {
  if (x[3] < 230.449997f) {
    if (x[4] < 0.140000001f) {
      if (x[2] < 53.0f) {
        return 1.18503487f;
      } else {
        return 5.88689756f;
      }
    } else {
      if (x[3] < 111.599998f) {
        return 1.09235084f;
      } else {
        return -0.34029302f;
      }
    }
  } else {
    if (x[3] < 443.399994f) {
      if (x[4] < 2.18000007f) {
        return -2.21593928f;
      } else {
        return 7.92137384f;
      }
    } else {
      if (x[0] < 37.4900017f) {
        return -8.39459801f;
      } else {
        return 4.90419006f;
      }
    }
  }
}
static inline float indra_fc_3_12(const float *x) {
  if (x[3] < 230.449997f) {
    if (x[1] < 23.0900002f) {
      if (x[3] < 140.779999f) {
        return 10.8998384f;
      } else {
        return 1.63734436f;
      }
    } else {
      if (x[1] < 81.5199966f) {
        return 0.710233331f;
      } else {
        return -1.32416856f;
      }
    }
  } else {
    if (x[3] < 443.399994f) {
      if (x[4] < 2.55999994f) {
        return -1.73669934f;
      } else {
        return 11.6358528f;
      }
    } else {
      if (x[4] < 0.939999998f) {
        return -4.15610838f;
      } else {
        return -11.4430695f;
      }
    }
  }
}
static inline float indra_fc_3_13(const float *x) {
  if (x[3] < 230.449997f) {
    if (x[4] < 1.44000006f) {
      if (x[4] < 0.140000001f) {
        return 2.63669991f;
      } else {
        return -0.0730390325f;
      }
    } else {
      if (x[0] < 29.6700001f) {
        return 3.8196876f;
      } else {
        return -0.308155507f;
      }
    }
  } else {
    if (x[3] < 747.780029f) {
      if (x[4] < 1.86000001f) {
        return -1.99680829f;
      } else {
        return 3.27370834f;
      }
    } else {
      if (x[2] < 74.8099976f) {
        return 3.18401623f;
      } else {
        return -18.9827061f;
      }
    }
  }
}
static inline float indra_fc_3_14(const float *x) {
  if (x[1] < 38.3499985f) {
    if (x[2] < 96.0400009f) {
      if (x[0] < 35.1500015f) {
        return 3.79668427f;
      } else {
        return 0.39139986f;
      }
    } else {
      if (x[1] < 24.5300007f) {
        return -4.50722647f;
      } else {
        return 0.21927622f;
      }
    }
  } else {
    if (x[3] < 110.599998f) {
      if (x[1] < 62.8100014f) {
        return 2.18153262f;
      } else {
        return -0.336867541f;
      }
    } else {
      if (x[2] < 63.0900002f) {
        return -4.14865541f;
      } else {
        return -0.976355493f;
      }
    }
  }
}
static inline float indra_fc_3_15(const float *x) {
  if (x[1] < 36.7299995f) {
    if (x[2] < 67.9400024f) {
      if (x[1] < 22.7099991f) {
        return 7.2731905f;
      } else {
        return 1.7398628f;
      }
    } else {
      if (x[4] < 1.32000005f) {
        return -0.531962574f;
      } else {
        return 3.01296544f;
      }
    }
  } else {
    if (x[3] < 91.6399994f) {
      if (x[1] < 62.8100014f) {
        return 2.276721f;
      } else {
        return -0.154802993f;
      }
    } else {
      if (x[2] < 49.0699997f) {
        return -3.67031336f;
      } else {
        return -0.701894879f;
      }
    }
  }
}
static inline float indra_fc_head_3(const float *x) {
  float residual = 0.427158f;
  residual += indra_fc_3_0(x);
  residual += indra_fc_3_1(x);
  residual += indra_fc_3_2(x);
  residual += indra_fc_3_3(x);
  residual += indra_fc_3_4(x);
  residual += indra_fc_3_5(x);
  residual += indra_fc_3_6(x);
  residual += indra_fc_3_7(x);
  residual += indra_fc_3_8(x);
  residual += indra_fc_3_9(x);
  residual += indra_fc_3_10(x);
  residual += indra_fc_3_11(x);
  residual += indra_fc_3_12(x);
  residual += indra_fc_3_13(x);
  residual += indra_fc_3_14(x);
  residual += indra_fc_3_15(x);
  float value = x[3] + 0.75f * residual;
  return fminf(5000.0f, fmaxf(0.0f, value));
}
static inline float indra_fc_4_0(const float *x) {
  if (x[4] < 1.32000005f) {
    if (x[4] < 0.670000017f) {
      if (x[1] < 75.0299988f) {
        return 0.0364834033f;
      } else {
        return 0.0889474452f;
      }
    } else {
      if (x[1] < 72.4100037f) {
        return -0.0162689742f;
      } else {
        return 0.0340017192f;
      }
    }
  } else {
    if (x[4] < 2.3599999f) {
      if (x[4] < 1.75999999f) {
        return -0.0705176443f;
      } else {
        return -0.136055902f;
      }
    } else {
      if (x[4] < 3.05999994f) {
        return -0.227019951f;
      } else {
        return -0.444267839f;
      }
    }
  }
}
static inline float indra_fc_4_1(const float *x) {
  if (x[4] < 1.47000003f) {
    if (x[4] < 0.810000002f) {
      if (x[4] < 0.50999999f) {
        return 0.0513014756f;
      } else {
        return 0.0247443523f;
      }
    } else {
      if (x[4] < 1.10000002f) {
        return 0.000507084304f;
      } else {
        return -0.0301753823f;
      }
    }
  } else {
    if (x[4] < 3.05999994f) {
      if (x[4] < 2.11999989f) {
        return -0.0792899579f;
      } else {
        return -0.166054204f;
      }
    } else {
      if (x[4] < 3.44000006f) {
        return -0.263268888f;
      } else {
        return -0.442304194f;
      }
    }
  }
}
static inline float indra_fc_4_2(const float *x) {
  if (x[4] < 1.23000002f) {
    if (x[1] < 70.4400024f) {
      if (x[4] < 0.460000008f) {
        return 0.0315760933f;
      } else {
        return -0.00730053056f;
      }
    } else {
      if (x[0] < 10.6199999f) {
        return -0.00866952073f;
      } else {
        return 0.0579141788f;
      }
    }
  } else {
    if (x[4] < 2.18000007f) {
      if (x[4] < 1.69000006f) {
        return -0.0384970196f;
      } else {
        return -0.08014559f;
      }
    } else {
      if (x[4] < 3.44000006f) {
        return -0.143806264f;
      } else {
        return -0.338684738f;
      }
    }
  }
}
static inline float indra_fc_4_3(const float *x) {
  if (x[4] < 1.30999994f) {
    if (x[4] < 0.600000024f) {
      if (x[0] < 11.3199997f) {
        return -0.00384989125f;
      } else {
        return 0.0354882441f;
      }
    } else {
      if (x[4] < 0.939999998f) {
        return 0.010230666f;
      } else {
        return -0.0129102888f;
      }
    }
  } else {
    if (x[4] < 2.46000004f) {
      if (x[4] < 1.88999999f) {
        return -0.0380612426f;
      } else {
        return -0.0815123692f;
      }
    } else {
      if (x[4] < 3.44000006f) {
        return -0.136440814f;
      } else {
        return -0.28071335f;
      }
    }
  }
}
static inline float indra_fc_4_4(const float *x) {
  if (x[1] < 84.2600021f) {
    if (x[2] < 50.2900009f) {
      if (x[1] < 74.3099976f) {
        return -0.0346349962f;
      } else {
        return 0.00169942656f;
      }
    } else {
      if (x[1] < 29.0799999f) {
        return -0.0120976297f;
      } else {
        return 0.00676548714f;
      }
    }
  } else {
    if (x[2] < 150.389999f) {
      if (x[0] < 9.86999989f) {
        return -0.00699359272f;
      } else {
        return 0.0463229455f;
      }
    } else {
      if (x[3] < 276.269989f) {
        return 0.0118741943f;
      } else {
        return -0.0312036108f;
      }
    }
  }
}
static inline float indra_fc_4_5(const float *x) {
  if (x[4] < 1.08000004f) {
    if (x[4] < 0.579999983f) {
      if (x[0] < 11.8699999f) {
        return 0.000487615645f;
      } else {
        return 0.0287731923f;
      }
    } else {
      if (x[3] < 46.4000015f) {
        return 0.0269083418f;
      } else {
        return 0.00141640322f;
      }
    }
  } else {
    if (x[4] < 1.97000003f) {
      if (x[4] < 1.59000003f) {
        return -0.0186670609f;
      } else {
        return -0.0419777445f;
      }
    } else {
      if (x[0] < 32.7599983f) {
        return -0.11900685f;
      } else {
        return -0.0267400984f;
      }
    }
  }
}
static inline float indra_fc_4_6(const float *x) {
  if (x[4] < 1.54999995f) {
    if (x[1] < 77.2200012f) {
      if (x[4] < 0.360000014f) {
        return 0.0201539155f;
      } else {
        return -0.00637226412f;
      }
    } else {
      if (x[3] < 223.699997f) {
        return 0.0350415967f;
      } else {
        return -0.00524519337f;
      }
    }
  } else {
    if (x[4] < 2.82999992f) {
      if (x[0] < 31.7999992f) {
        return -0.059943147f;
      } else {
        return -0.0148806591f;
      }
    } else {
      if (x[3] < 179.720001f) {
        return -0.168701202f;
      } else {
        return -0.0527552925f;
      }
    }
  }
}
static inline float indra_fc_4_7(const float *x) {
  if (x[4] < 0.910000026f) {
    if (x[1] < 59.6100006f) {
      if (x[4] < 0.289999992f) {
        return 0.0198847875f;
      } else {
        return -0.00444103545f;
      }
    } else {
      if (x[0] < 20.3099995f) {
        return 0.00991626643f;
      } else {
        return 0.0449384339f;
      }
    }
  } else {
    if (x[4] < 2.16000009f) {
      if (x[4] < 1.63999999f) {
        return -0.0116770491f;
      } else {
        return -0.0300674718f;
      }
    } else {
      if (x[3] < 286.200012f) {
        return -0.0907040685f;
      } else {
        return 0.0285663307f;
      }
    }
  }
}
static inline float indra_fc_4_8(const float *x) {
  if (x[4] < 1.00999999f) {
    if (x[1] < 60.5200005f) {
      if (x[2] < 38.6800003f) {
        return -0.0222842153f;
      } else {
        return 0.00572443986f;
      }
    } else {
      if (x[0] < 11.8699999f) {
        return -0.0111374324f;
      } else {
        return 0.0272727311f;
      }
    }
  } else {
    if (x[4] < 3.05999994f) {
      if (x[0] < 32.0900002f) {
        return -0.0264793783f;
      } else {
        return -0.00612754142f;
      }
    } else {
      if (x[0] < 21.4300003f) {
        return -0.36901924f;
      } else {
        return -0.112081066f;
      }
    }
  }
}
static inline float indra_fc_4_9(const float *x) {
  if (x[1] < 88.5599976f) {
    if (x[2] < 78.8000031f) {
      if (x[1] < 72.4100037f) {
        return -0.015422388f;
      } else {
        return 0.00469987793f;
      }
    } else {
      if (x[0] < 30.5699997f) {
        return -0.00018878252f;
      } else {
        return 0.0181439798f;
      }
    }
  } else {
    if (x[0] < 28.4500008f) {
      if (x[0] < 8.96000004f) {
        return -0.0139029874f;
      } else {
        return 0.0345839225f;
      }
    } else {
      if (x[0] < 32.0900002f) {
        return -0.0363575481f;
      } else {
        return -0.00088294188f;
      }
    }
  }
}
static inline float indra_fc_4_10(const float *x) {
  if (x[4] < 1.13999999f) {
    if (x[1] < 44.5299988f) {
      if (x[4] < 0.340000004f) {
        return 0.0148514975f;
      } else {
        return -0.0070618107f;
      }
    } else {
      if (x[0] < 19.0100002f) {
        return 0.00110717176f;
      } else {
        return 0.0197114553f;
      }
    }
  } else {
    if (x[4] < 2.82999992f) {
      if (x[3] < 218.0f) {
        return -0.0207019821f;
      } else {
        return 0.00920025632f;
      }
    } else {
      if (x[0] < 21.4300003f) {
        return -0.237623766f;
      } else {
        return -0.0744173676f;
      }
    }
  }
}
static inline float indra_fc_4_11(const float *x) {
  if (x[4] < 0.819999993f) {
    if (x[2] < 29.1700001f) {
      if (x[0] < 24.3999996f) {
        return -0.0195219498f;
      } else {
        return 0.0202846769f;
      }
    } else {
      if (x[2] < 189.929993f) {
        return 0.0139238238f;
      } else {
        return -0.0157396682f;
      }
    }
  } else {
    if (x[4] < 2.51999998f) {
      if (x[0] < 25.0900002f) {
        return -0.0189982057f;
      } else {
        return -0.00490171835f;
      }
    } else {
      if (x[3] < 178.300003f) {
        return -0.0747522935f;
      } else {
        return -0.00360193336f;
      }
    }
  }
}
static inline float indra_fc_4_12(const float *x) {
  if (x[4] < 1.45000005f) {
    if (x[1] < 87.5599976f) {
      if (x[1] < 22.3600006f) {
        return -0.0184074678f;
      } else {
        return 0.00182642718f;
      }
    } else {
      if (x[0] < 28.1700001f) {
        return 0.024053961f;
      } else {
        return -0.0203072336f;
      }
    }
  } else {
    if (x[0] < 30.5699997f) {
      if (x[1] < 66.7900009f) {
        return -0.0607973151f;
      } else {
        return -0.013204108f;
      }
    } else {
      if (x[3] < 81.5599976f) {
        return -0.0398967154f;
      } else {
        return 0.0113878651f;
      }
    }
  }
}
static inline float indra_fc_4_13(const float *x) {
  if (x[4] < 1.88f) {
    if (x[4] < 0.479999989f) {
      if (x[2] < 40.3400002f) {
        return -1.9236868e-05f;
      } else {
        return 0.0160345547f;
      }
    } else {
      if (x[0] < 10.6199999f) {
        return -0.0531492718f;
      } else {
        return -0.000818575732f;
      }
    }
  } else {
    if (x[3] < 181.199997f) {
      if (x[4] < 3.44000006f) {
        return -0.031349916f;
      } else {
        return -0.100356817f;
      }
    } else {
      if (x[0] < 30.3899994f) {
        return -0.0631820187f;
      } else {
        return 0.0311312117f;
      }
    }
  }
}
static inline float indra_fc_4_14(const float *x) {
  if (x[1] < 88.5599976f) {
    if (x[2] < 27.8099995f) {
      if (x[1] < 67.2200012f) {
        return -0.0307244156f;
      } else {
        return 0.00278370571f;
      }
    } else {
      if (x[1] < 29.0799999f) {
        return -0.0108833415f;
      } else {
        return 0.0029731628f;
      }
    }
  } else {
    if (x[2] < 156.25f) {
      if (x[0] < 28.4500008f) {
        return 0.0228026584f;
      } else {
        return -0.0217930581f;
      }
    } else {
      if (x[3] < 247.800003f) {
        return -0.00270052184f;
      } else {
        return -0.0421212316f;
      }
    }
  }
}
static inline float indra_fc_4_15(const float *x) {
  if (x[4] < 1.40999997f) {
    if (x[1] < 38.6199989f) {
      if (x[3] < 85.0f) {
        return -0.0266172681f;
      } else {
        return -0.00227262871f;
      }
    } else {
      if (x[2] < 211.089996f) {
        return 0.00754158292f;
      } else {
        return -0.0276707765f;
      }
    }
  } else {
    if (x[3] < 238.369995f) {
      if (x[4] < 3.44000006f) {
        return -0.0151384044f;
      } else {
        return -0.0855855495f;
      }
    } else {
      if (x[1] < 30.3099995f) {
        return -0.0338992141f;
      } else {
        return 0.0310766399f;
      }
    }
  }
}
static inline float indra_fc_head_4(const float *x) {
  float residual = -0.0010280897f;
  residual += indra_fc_4_0(x);
  residual += indra_fc_4_1(x);
  residual += indra_fc_4_2(x);
  residual += indra_fc_4_3(x);
  residual += indra_fc_4_4(x);
  residual += indra_fc_4_5(x);
  residual += indra_fc_4_6(x);
  residual += indra_fc_4_7(x);
  residual += indra_fc_4_8(x);
  residual += indra_fc_4_9(x);
  residual += indra_fc_4_10(x);
  residual += indra_fc_4_11(x);
  residual += indra_fc_4_12(x);
  residual += indra_fc_4_13(x);
  residual += indra_fc_4_14(x);
  residual += indra_fc_4_15(x);
  float value = x[4] + 0.75f * residual;
  return fminf(100.0f, fmaxf(0.0f, value));
}
/* Returns 1 on success, 0 for null pointers, missing or out-of-range inputs.
 * Pass distinct arrays. Outputs are NAN on invalid sensor data. No heap allocation. */
static inline int indra_forecast_predict(const float *input, float *output) {
  if (!input || !output) return 0;
  float x[5];
  for (int i = 0; i < 5; ++i) x[i] = input[i];
  for (int i = 0; i < 5; ++i) output[i] = NAN;
  if (!isfinite(x[0]) || x[0] < -60.0f || x[0] > 85.0f) return 0;
  if (!isfinite(x[1]) || x[1] < 0.0f || x[1] > 100.0f) return 0;
  if (!isfinite(x[2]) || x[2] < 0.0f || x[2] > 5000.0f) return 0;
  if (!isfinite(x[3]) || x[3] < 0.0f || x[3] > 5000.0f) return 0;
  if (!isfinite(x[4]) || x[4] < 0.0f || x[4] > 100.0f) return 0;
  output[0] = indra_fc_head_0(x);
  output[1] = indra_fc_head_1(x);
  output[2] = indra_fc_head_2(x);
  output[3] = indra_fc_head_3(x);
  output[4] = indra_fc_head_4(x);
  return 1;
}
#endif
