[platformio]
default_envs = esp32-s3-devkitc-1

[env]
test_framework = unity
lib_ldf_mode = deep+
build_flags =
    -I../ml/generated

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

[env:native]
platform = native
build_flags =
    ${env.build_flags}
    -std=c++17

